HPL = [
# 0
"Maszeruj w miejscu w wygodnym tempie, ręce swobodnie kołyszą się w przód i w tył.","Stopy na szerokość barków, kolana miękkie; powolne krążenia biodrami w jedną i drugą stronę.","Kolana lekko ugięte, biodra w tył, plecy proste, dłonie zsuwają się po udach do kolan; przy powrocie napnij pośladki.","Leżąc na plecach, stopy na szerokość bioder; unieś biodra na wydechu, opuść na wdechu.","Unoś biodra tylko trochę.","Krzesło za tobą; biodra w tył, zejdź do połowy przysiadu i wstań na wydechu.","Oprzyj dłonie na udach.","Stopy na szerokość barków, biodra w tył, kolana w tę samą stronę co palce; dotknij krzesła i wstań na wydechu.","Usiądź całkowicie i wstań, pomagając sobie rękami; przy bólu kolana — tylko do wygodnej głębokości.","Kolana lekko ugięte, plecy proste, hantle zsuwają się wzdłuż ud do połowy goleni; przy powrocie napnij pośladki, wydech.",
# 10
"Bez obciążenia, dłonie do kolan; przy bólu pleców — mniejszy zakres.","Ręka na oparciu, krok w tył, zejdź w dół; kolano przedniej nogi nad stopą; odepchnij się przednią nogą.","Mały krok w tył, płytko.","Trzymając się krzesła, wspinaj się na palce i miękko opadaj na pięty — lekkie uderzenie służy kościom.","Opuszczaj powoli, bez uderzenia.","Leżąc, stopy na szerokość bioder; wydech i unieś dno miednicy — biodra w górę, pauza 1 s, opuść na wdechu.","Siedząc prosto, wdech nosem, wydech dłuższy niż wdech — barki opadają.","Ręka na krześle, chwyć stopę i przyciągnij piętę do pośladka; kolana obok siebie, bez wyginania lędźwi.","Przyciągnij stopę paskiem lub ręcznikiem.","Pięta na krześle lub na podłodze przed tobą, noga prosta; pochyl się z prostymi plecami do lekkiego rozciągnięcia.",
# 20
"Dłonie na kolanach, łagodne krążenia kolanami i biodrami w obie strony.","Ręka na krześle, mały krok w tył, zejdź nieco w dół i wróć.","Leżąc, wydech i unieś dno miednicy — biodra w górę, opuść na wdechu.","Stopy na szerokość barków, biodra w tył, kolana w linii palców, plecy proste; wstań na wydechu.","Przysiad do krzesła.","Hantla przy klatce, biodra w tył, kolana w linii palców, plecy proste; wstań na wydechu.","Przysiad do krzesła; przy bólu kolana — głębokość wygodna.","Plecy proste, hantle wzdłuż ud do połowy goleni; przy powrocie napnij pośladki. Z ciężarem nigdy nie zaokrąglaj pleców.","Tylko do kolan, lżejszy ciężar.","Krok w tył, zejdź w dół; kolano przedniej nogi nad stopą; odepchnij się przednią nogą.",
# 30
"Z ręką na oparciu krzesła, płytko.","Niskie podskoki, miękkie lądowanie na przodzie stopy, kolana lekko ugięte.","Wspięcia na palce z miękkim opuszczaniem na pięty.","Druga noga zgięta w powietrzu; wydech i unieś dno miednicy — biodra w górę.","Mostek na dwóch nogach.","Cała stopa na stopniu, odepchnij się piętą, schodź powoli.","Bez hantli, ręka na ścianie.","Wdech nosem, wydech dłuższy niż wdech — ciało się rozluźnia.","Siedząc na krześle, kostka na przeciwnym kolanie; pochyl się z prostymi plecami.","Marsz w miejscu, kolana wyżej niż zwykle, ręce pracują.",
# 40
"Łagodne krążenia biodrami, potem kolanami, potem stopami — w obie strony.","Krok w tył do wykroku i jednocześnie ręce w górę; wróć, ręce w dół.","Bez rąk, z oparciem o krzesło.","Biodra w górę, pauza 2–3 s, pośladki napięte, żebra nie wypychają się.","Krótsza pauza.","Przysiad, a na końcu kilka miękkich podskoków w miejscu.","Bez podskoków.","Hantle przy barkach lub wzdłuż ciała; schodź powoli na 3, wstawaj pewnie na wydechu.","Jedna hantla przy klatce, zwykłe tempo.","Ręka na krześle, hantla w drugiej ręce; plecy i biodra równo, wolna noga odchodzi w tył.",
# 50
"Palce drugiej stopy dotykają podłogi.","Tylna noga na krześle, tułów lekko w przód, kolano przedniej nogi nad stopą.","Zwykły wykrok w tył z podparciem.","Mały przysiad — niski skok — miękkie lądowanie od razu w przysiad.","Przysiad i wspięcie na palce.","Łopatki na siedzisku krzesła, hantla na biodrach; wydech i unieś dno miednicy — biodra w górę do prostej linii, pauza 1 s.","Mostek na podłodze z hantlą.","Szeroki krok w bok, biodra w tył, druga noga prosta; odepchnij się z powrotem.","Mniejszy krok, bez hantli.","Szeroki rozkrok; przenieś ciężar na jedną nogę, uginając jej kolano; druga noga prosta.",
# 60
"Powolne krążenia barkami w przód i w tył, szyja rozluźniona.","Dłonie na udach; na wydechu zaokrąglij plecy, na wdechu otwórz klatkę.","Plecy i łokcie przy ścianie; powoli przesuwaj ręce w górę i w dół, nie odrywając ich od ściany.","Unoś ręce niżej.","Dłonie na ścianie na wysokości barków, ciało proste; do ściany na wdechu, od ściany na wydechu.","Stań bliżej ściany.","Ręka i kolano na krześle, plecy proste; ciągnij hantlę łokciem wzdłuż ciała do pasa.","Siedząc na krześle, ciągnij obie hantle do pasa.","Plecy proste, brzuch lekko napięty; wypchnij hantle znad barków w górę na wydechu.","Wypychanie w przód do wysokości twarzy.",
# 70
"Hantle w opuszczonych rękach, barki w tył i w dół, równe kroki po pokoju.","Lżejszy ciężar albo stój w miejscu z hantlami.","Leżąc na brzuchu, czoło na macie; na wydechu unieś przeciwną rękę i nogę na kilka centymetrów, szyja długa.","Unoś tylko ręce naprzemiennie.","Przedramię na framudze drzwi, łagodny krok w przód do rozciągnięcia klatki.","Przyciśnij prostą rękę do klatki drugą ręką, bark w dół.","Krążenia barkami, potem prostymi rękami — powoli, w obie strony.","W klęku podpartym: na wydechu zaokrąglij plecy, na wdechu łagodnie się wygnij; głowa podąża za plecami.","Dłonie na siedzisku lub oparciu stabilnego krzesła, ciało proste; powoli zejdź i wypchnij.","Pompki przy ścianie.",
# 80
"Dłonie nieco szerzej niż barki, ciało od kolan do głowy proste.","Przy krześle lub ścianie.","Skłon z prostymi plecami, kolana miękkie; hantle do pasa, ściągnij łopatki.","Jedną ręką z oparciem o krzesło.","Brzuch i pośladki lekko napięte, bez wyginania lędźwi; wypchnij hantle znad barków na wydechu.","Siedząc, do wysokości twarzy.","Skłon z prostymi plecami, ręce lekko ugięte; unieś lekkie hantle bokiem do wysokości barków.","Bez obciążenia.","Leżąc, kolana ugięte; wypchnij hantle znad klatki na wydechu, łokcie dotykają podłogi.","Lżejszy ciężar albo po jednej ręce.",
# 90
"Ręka za głową; drugą ręką łagodnie pociągnij łokieć.","Ciało proste, schodź powoli na 3, w górę na wydechu.","Na kolanach.","Ręka i kolano na krześle, plecy proste; hantla do pasa, cięższy ciężar.","Lżejszy ciężar.","Wypchnij hantlę znad barku jedną ręką; tułów się nie pochyla.","Obiema rękami na siedząco, do wysokości twarzy.","Łokcie lekko ugięte; unoś hantle bokiem do wysokości barków, nie wyżej.","Lekki ciężar albo bez obciążenia.","Wyciskanie znad klatki, potem prostymi rękami przenieś hantlę za głowę i z powrotem.",
# 100
"Tylko wyciskanie.","Deska na prostych rękach, stopy szerzej; dotykaj na zmianę barków, biodra stabilnie.","Na kolanach albo deska na przedramionach bez dotykania.","Krążenia barkami, potem biodrami, powoli, w obie strony.","Hantla przy klatce; stopy nieco szerzej niż barki, biodra w tył, dotknij krzesła i wstań na wydechu.","Bez hantli, pomagając sobie rękami.","Dłoń na ścianie za tobą; powoli obróć tułów od ściany do rozciągnięcia klatki.","Krążenia barkami, biodrami, potem kolanami — powoli, w obie strony.","Miękkie, niskie podskoki w miejscu, potem na boki; kolana miękkie.","Miękkie podskoki na palcach, kolana rozluźnione.",
# 110
"Wspięcia na palce.","Z przysiadu z hantlami przy barkach wstań i wypchnij je w górę jednym ruchem.","Przysiad z hantlami przy barkach, bez wyciskania.","Dłonie nieco szerzej niż barki, ciało proste; w dół na wdechu, w górę na wydechu.","Hantla w jednej ręce; tułów nie przechyla się w bok; równe kroki.","Dwie lekkie hantle.","Kolana nad biodrami, lędźwie łagodnie przy podłodze; na wydechu opuść jedną piętę do podłogi.","Stopy na podłodze, wysuwaj jedną piętę w przód.","Wyciągnij przeciwną rękę i nogę, plecy proste, pauza 2 s.","Tylko noga, palce suną po podłodze.",
# 120
"Leżąc na boku, podpór na przedramieniu i kolanach; unieś biodra, ciało proste.","Stojąc, przedramię oparte o ścianę.","Zanim wstaniesz, łagodnie unieś dno miednicy i wstań na wydechu.","Wdech — brzuch i żebra łagodnie się rozszerzają; długi wydech — żebra się schodzą, dno miednicy łagodnie się unosi.","Leżąc, kolana ugięte; łagodnie opuszczaj kolana w jedną i drugą stronę.","Na wdechu w myślach rozluźnij dno miednicy, brzuch miękki.","Opuszczaj przeciwną rękę i nogę, lędźwie łagodnie przy podłodze; wydech przy opuszczaniu.","Tylko nogi.","Bez pauzy.","Podpór na przedramionach i palcach, ciało proste; nie wstrzymuj oddechu.",
# 130
"Podpór na przedramieniu i stopach, biodra uniesione, ciało proste.","Hantla w jednej ręce; nie przechylaj się do niej; unieś dno miednicy przed podniesieniem hantli z podłogi.","Kolano na macie, druga noga z przodu; łagodnie przesuń biodra w przód do rozciągnięcia przodu uda.","Bez hantli.","Deska na prostych rękach; powoli przyciągnij kolano do klatki i wróć, biodra stabilnie.","Deska na przedramionach, 30 s.","Deska boczna: opuść biodra i unieś z powrotem.","W klęku podpartym unieś kolana 3 cm nad podłogę, plecy proste, nie wstrzymuj oddechu.","Kolana na podłodze, „pies-ptak”.","Ręka prosta nad barkiem, żebra nie wypychają się; równe kroki.",
# 140
"Hantla przy barku.","Stojąc przy podporze, krążenia stopą i kolanem w obie strony.","Trzymając się krzesła, przetocz się z pięty na palce i z powrotem.","Ręka na oparciu, stój na jednej nodze; jeśli łatwo — bez podpory.","Przy ścianie: stawiaj piętę tuż przed palcami drugiej stopy, wzrok przed siebie.","Krótsze kroki, ręka na ścianie.","Stojąc na jednej nodze przy podporze, dotykaj palcami drugiej podłogi z przodu, z boku i z tyłu.","Trzymaj się obiema rękami.","Krok w bok z wysoko uniesionym kolanem, jak przez przeszkodę.","Stojąc na jednej nodze, skłon z prostymi plecami, druga noga odchodzi w tył.",
# 150
"Palce drugiej stopy dotykają podłogi.","Przy podporze: na komendę krok w przód, w bok lub w tył i powrót.","Tylko kroki w bok.","Dłonie na ścianie, jedna noga w tył, pięta na podłodze; przesuń biodra w przód do rozciągnięcia łydki.","Siedząc, tocz stopę po piłce lub zwiniętych skarpetkach.","Głowa powoli półkolem od barku do barku, potem krążenia barkami i rękami.","Nie odchylaj głowy do tyłu.","W klęku podpartym powolne krążenia biodrami.","Leżąc na boku, kolana ugięte; górna ręka otwiera się do tyłu, wzrok podąża za dłonią.","Na wydechu unoś biodra, odklejając plecy kręg po kręgu; opuszczaj tak samo.",
# 160
"Pięta na krześle, noga prosta; łagodnie bujaj się w przód i w tył z prostymi plecami.","Siedząc: krążenia stopami, przetaczanie z pięty na palce, palce po kolei „grają na pianinie”.","Leżąc na plecach, łydki na siedzisku krzesła; spokojny oddech, lędźwie rozluźnione.","Marsz w miejscu, co pół minuty trochę szybciej.","Wchodź i schodź ze stopnia w równym tempie, cała stopa na stopniu.","Ręka na ścianie.","15 s szybciej, ale na pół siły; potem spokojny marsz.","Skok w rozkrok z rękami w górę, skok z powrotem; miękkie lądowanie.","Kroki w bok z unoszeniem rąk.","Bieg w miejscu, kolana wyżej, miękkie lądowanie.",
# 170
"Szybki marsz z wysokim kolanem.","Spokojny marsz w miejscu, oddech się wyrównuje.","Rozciąganie przodu i tyłu uda, łydek i klatki — po 20–30 s.","Ręka na ścianie, niższy stopień.","Pięta na stopniu, noga prosta; pochyl się z prostymi plecami.","Skok z płytkiego przysiadu, potem skoki na boki; miękkie lądowanie.","Niższy stopień, bez hantli.","Pięta w przód, skłon z prostymi plecami; potem na siedząco kostka na kolanie.","Dłonie na krawędzi stołu lub siedzisku krzesła, ciało proste; klatka do krawędzi, odepchnij się na wydechu.","Przy ścianie.",
# 180
"Stopy na krześle, dłonie na podłodze, ciało proste; schodź na 3. Przy wysokim ciśnieniu — z podłogi.","Zwykłe pompki.","Wyciskanie leżąc z pauzą 1 s na dole, w górę na wydechu.","Rozciąganie przodu i tyłu uda oraz pośladków — po 20–30 s.","Wydech — unieś dno miednicy — biodra w górę; przy opuszczaniu rozluźnij.","Marsz w miejscu coraz szybciej, krążenia barkami i biodrami, łagodne przysiady.","Szybki marsz w miejscu, ręce aktywnie pracują.","Krok w bok i z powrotem, ręce unoszą się bokiem w górę.","Krok w tył, potem kolano w przód i w górę; zmiana nóg.","Stojąc, ciosy w powietrze w przód z lekkimi krokami; łokcie miękkie.",
# 190
"Marsz w miejscu coraz wolniej, oddech się wyrównuje.","Rozciąganie łydek przy ścianie i ud — po 20–30 s.","Marsz z przyspieszaniem, wejścia na stopień, potem dwa próbne przyspieszenia na pół siły.","Przysiad i przy wstawaniu ręce w górę; szybkie tempo, kolana miękkie.","Wolniej.","Szeroki krok w bok i z powrotem, szybko.","Powtórz ćwiczenia 1–5 jeszcze raz.","Spokojny marsz, głęboki oddech, potem rozciąganie łydek i ud.","Stojąc przy ścianie, dociskaj dłoń do ściany na zewnątrz, potem do środka — po 10 s, nie wstrzymuj oddechu.","Siedząc na podłodze, nogi zgięte pod kątem 90°; łagodnie przenoś kolana na drugą stronę.",
# 200
"Plecy przy ścianie, zejdź do wygodnego kąta i trzymaj; nie wstrzymuj oddechu.","Zostań wyżej.","Palce przy ścianie, kolano sięga do ściany; potem krążenia stopą.","Leżąc, kolana ugięte: wdech — brzuch i żebra łagodnie się rozszerzają, dno miednicy się rozluźnia; wydech — żebra się schodzą, dno miednicy łagodnie się unosi.","Unieś dno miednicy jak przez słomkę, trzymaj 2 s, rozluźnij 2 s. Pośladki i brzuch luźne.","Szybko unieś dno miednicy i od razu puść.","Leżąc, kolana ugięte; lędźwie łagodnie dociskają się do podłogi i puszczają.","Unieś dno miednicy, trzymaj 5 s, rozluźnij 5 s. Pośladki i brzuch luźne.","Trzymaj 3 s.","Łagodnie unieś dno miednicy sekundę przed kaszlem lub podniesieniem hantli.",
# 210
"Siedząc prosto: wdech — brzuch i żebra się rozszerzają; długi wydech — żebra się schodzą.","Wdech nosem na 4, wydech na 6.","Leżąc: wdech — brzuch i żebra się rozszerzają, wydech — łagodnie się schodzą.","Jakbyś wstrzymywał strumień: unieś, trzymaj 3 s, puść 3 s. Pośladki i brzuch luźne.","Unieś dno miednicy, potem zakaszl.","Unieś dno miednicy, zanim podniesiesz hantlę z podłogi.","Ręka na ścianie: idź bokiem, potem tyłem, na palcach i na piętach.","Krótsze kroki, obie ręce przy ścianie.","Leżąc na boku, noga prosta, palce do siebie; unoś nisko, biodra nie odchylają się w tył.","Leżąc na boku, kolana ugięte, stopy razem; otwieraj górne kolano, biodra nieruchome.",
# 220
"Leżąc, kolano nad biodrem; małe krążenia w obie strony, lędźwie spokojne.","Głowa na macie, kolana ugięte; proste ręce sprężynują przy podłodze: 5 liczb wdech, 5 wydech.","Głowa na macie; jedno kolano do klatki, druga noga wyciąga się po skosie; zmiana na wydechu.","Leżąc na brzuchu, podpór na przedramionach; klatka unosi się nisko, wzrok w podłogę.","Siedząc, ręka nad głową, skłon w bok bez skrętu.","Kolana szeroko, biodra do pięt, ręce w przód, oddychaj w plecy.","Poduszka pod biodra.","Stojąc, stopy pod biodrami, czubek głowy w górę; spokojny wdech nosem.","Kolana miękkie, ciężar powoli przepływa z nogi na nogę, ręce płyną za nim.","Krok w bok; jedna dłoń unosi się do wysokości barku, druga opada do biodra; zmiana.",
# 230
"Dłonie na zmianę zataczają koło przed twarzą i brzuchem, z dostawnym krokiem w bok.","Stopa na łydce, nie na kolanie; ręka na podporze.","Palce na podłodze, pięta przy kostce.","Szeroki rozkrok, przednie kolano nad stopą, ręce w bok.","Węższy rozkrok, kolano mniej ugięte.","Biodra w tył jak przy siadaniu na krześle, ręce w górę przy uszach.","Ręce na udach.","Leżąc na brzuchu, przedramiona pod barkami, barki w dół.","Leżąc na plecach, ręce lekko w bok, uwaga na wydechu.",
]
HIT = [
# 0
"Marcia sul posto a un ritmo comodo, le braccia oscillano libere avanti e indietro.","Piedi alla larghezza delle spalle, ginocchia morbide; cerchi lenti con il bacino in un senso e nell’altro.","Ginocchia leggermente piegate, bacino indietro, schiena dritta, le mani scivolano sulle cosce fino alle ginocchia; risalendo, stringi i glutei.","Sdraiati sulla schiena, piedi alla larghezza del bacino; solleva il bacino espirando, abbassalo inspirando.","Solleva il bacino solo un po’.","Sedia dietro di te; bacino indietro, scendi a metà e risali espirando.","Appoggia le mani sulle cosce.","Piedi alla larghezza delle spalle, bacino indietro, ginocchia nella direzione delle punte; tocca la sedia e risali espirando.","Siediti del tutto e alzati aiutandoti con le mani; se il ginocchio fa male, solo fino a una profondità comoda.","Ginocchia leggermente piegate, schiena dritta, i manubri scivolano lungo le cosce fino a metà tibia; risalendo stringi i glutei, espira.",
# 10
"Senza peso, mani fino alle ginocchia; se la schiena fa male, movimento più piccolo.","Mano sullo schienale, passo indietro e scendi; ginocchio davanti sopra il piede; spingi con la gamba davanti.","Passo corto indietro, poco profondo.","Tenendoti alla sedia, sali sulle punte e lascia ricadere dolcemente i talloni: il piccolo impatto fa bene all’osso.","Scendi piano, senza impatto.","Sdraiati, piedi alla larghezza del bacino; espira e solleva il pavimento pelvico: bacino su, pausa 1 s, scendi inspirando.","Seduti dritti, inspira dal naso, espira più a lungo: le spalle si abbassano.","Mano sulla sedia, afferra il piede e porta il tallone verso il gluteo; ginocchia vicine, senza inarcare la zona lombare.","Tira il piede con una cinghia o un asciugamano.","Tallone sulla sedia o a terra davanti, gamba dritta; piegati in avanti a schiena dritta fino a un lieve allungamento.",
# 20
"Mani sulle ginocchia, cerchi morbidi con ginocchia e bacino nei due sensi.","Mano sulla sedia, piccolo passo indietro, scendi poco e torna.","Sdraiati, espira e solleva il pavimento pelvico: bacino su, scendi inspirando.","Piedi alla larghezza delle spalle, bacino indietro, ginocchia in linea con le punte, schiena dritta; risali espirando.","Squat verso la sedia.","Manubrio al petto, bacino indietro, ginocchia in linea con le punte, schiena dritta; risali espirando.","Squat verso la sedia; se il ginocchio fa male, profondità comoda.","Schiena dritta, manubri lungo le cosce fino a metà tibia; risalendo stringi i glutei. Con il peso non arrotondare mai la schiena.","Solo fino alle ginocchia, peso più leggero.","Passo indietro e scendi; ginocchio davanti sopra il piede; spingi con la gamba davanti.",
# 30
"Con una mano sullo schienale, poco profondo.","Salti bassi, atterraggio morbido sull’avampiede, ginocchia leggermente piegate.","Sollevamenti sulle punte con discesa morbida sui talloni.","L’altra gamba piegata in aria; espira e solleva il pavimento pelvico: bacino su.","Ponte su due piedi.","Tutto il piede sul gradino, spingi con il tallone, scendi piano.","Senza manubri, con la mano al muro.","Inspira dal naso, espira più a lungo: il corpo si rilassa.","Seduti sulla sedia, caviglia sul ginocchio opposto; piegati in avanti a schiena dritta.","Marcia sul posto, ginocchia più alte del solito, braccia attive.",
# 40
"Cerchi morbidi con il bacino, poi le ginocchia, poi le caviglie, nei due sensi.","Passo indietro in affondo alzando le braccia; torna e abbassale.","Senza braccia, con appoggio sulla sedia.","Bacino su, pausa 2–3 s in alto, glutei stretti, costole giù.","Pausa più breve.","Squat e, alla fine, qualche piccolo rimbalzo sul posto.","Senza rimbalzi.","Manubri alle spalle o lungo il corpo; scendi piano in 3 tempi, risali deciso espirando.","Un manubrio al petto, ritmo normale.","Mano sulla sedia, manubrio nell’altra mano; schiena e bacino in linea, la gamba libera va indietro.",
# 50
"Le dita dell’altro piede toccano il pavimento.","Piede dietro sulla sedia, busto un po’ in avanti, ginocchio davanti sopra il piede.","Affondo indietro normale con appoggio.","Piccolo squat, salto basso, atterraggio morbido direttamente in squat.","Squat e sollevamento sulle punte.","Scapole sulla seduta della sedia, manubrio sul bacino; espira e solleva il pavimento pelvico: bacino su fino alla linea dritta, pausa 1 s.","Ponte a terra con il manubrio.","Passo ampio di lato, bacino indietro, l’altra gamba dritta; spingi per tornare.","Passo più corto, senza manubrio.","Gambe larghe; sposta il peso su una gamba piegando quel ginocchio; l’altra gamba resta dritta.",
# 60
"Cerchi lenti con le spalle avanti e indietro, collo rilassato.","Mani sulle cosce; espirando arrotonda la schiena, inspirando apri il petto.","Schiena e gomiti al muro; fai scorrere lentamente le braccia su e giù senza staccarle.","Alza meno le braccia.","Mani al muro all’altezza delle spalle, corpo dritto; verso il muro inspirando, spingi via espirando.","Mettiti più vicino al muro.","Mano e ginocchio sulla sedia, schiena dritta; tira il manubrio con il gomito lungo il fianco fino alla vita.","Seduti sulla sedia, tira entrambi i manubri verso la vita.","Schiena dritta, addome leggermente attivo; spingi i manubri dalle spalle verso l’alto espirando.","Spinta in avanti fino all’altezza del viso.",
# 70
"Manubri nelle mani a braccia distese, spalle indietro e in basso, passi regolari per la stanza.","Peso più leggero, oppure fermo sul posto con i manubri.","A pancia in giù, fronte sul tappetino; espirando solleva braccio e gamba opposti di pochi centimetri, collo lungo.","Solleva solo le braccia, alternando.","Avambraccio sullo stipite della porta, piccolo passo avanti fino ad allungare il petto.","Porta il braccio dritto contro il petto con l’altra mano, spalla giù.","Cerchi con le spalle, poi con le braccia dritte, lentamente, nei due sensi.","A quattro zampe: espirando arrotonda la schiena, inspirando inarcala dolcemente; la testa segue la schiena.","Mani sulla seduta o sullo schienale di una sedia stabile, corpo dritto; scendi piano e spingi.","Piegamenti al muro.",
# 80
"Mani un po’ più larghe delle spalle, corpo dritto dalle ginocchia alla testa.","Sulla sedia o al muro.","Busto inclinato a schiena dritta, ginocchia morbide; manubri verso la vita, avvicina le scapole.","Con un braccio, appoggiati alla sedia.","Addome e glutei leggermente attivi, senza inarcare la zona lombare; spingi i manubri dalle spalle in su espirando.","Seduti, fino all’altezza del viso.","Busto inclinato a schiena dritta, braccia leggermente piegate; apri manubri leggeri fino all’altezza delle spalle.","Senza peso.","Sdraiati, ginocchia piegate; spingi i manubri dal petto in su espirando, i gomiti toccano il pavimento.","Peso più leggero o un braccio alla volta.",
# 90
"Mano dietro la testa; con l’altra mano tira dolcemente il gomito.","Corpo dritto, scendi piano in 3 tempi, risali espirando.","Sulle ginocchia.","Mano e ginocchio sulla sedia, schiena dritta; manubrio verso la vita, peso più alto.","Peso più leggero.","Spingi il manubrio dalla spalla in su con un braccio; il busto non si inclina.","A due braccia seduti, fino all’altezza del viso.","Gomiti leggermente piegati; solleva i manubri di lato fino all’altezza delle spalle, non oltre.","Peso leggero o senza peso.","Spinta dal petto, poi a braccia dritte porta il manubrio dietro la testa e torna.",
# 100
"Solo la spinta.","Plank a braccia tese, piedi più larghi; tocca una spalla e poi l’altra, bacino fermo.","Sulle ginocchia o plank sugli avambracci senza tocchi.","Cerchi con le spalle, poi con il bacino, lentamente, nei due sensi.","Manubrio al petto; piedi un po’ più larghi delle spalle, bacino indietro, tocca la sedia e risali espirando.","Senza manubrio, aiutandoti con le mani.","Palmo al muro dietro di te; ruota lentamente il busto allontanandoti dal muro fino ad allungare il petto.","Cerchi con le spalle, il bacino, poi le ginocchia, lentamente, nei due sensi.","Saltelli morbidi e bassi sul posto, poi da un lato all’altro; ginocchia morbide.","Piccoli rimbalzi morbidi sulle punte, ginocchia rilassate.",
# 110
"Sollevamenti sulle punte.","Dallo squat con i manubri alle spalle, alzati e spingi in su con un solo movimento.","Squat con i manubri alle spalle, senza spinta.","Mani un po’ più larghe delle spalle, corpo dritto; giù inspirando, su espirando.","Manubrio in una mano; il busto non si inclina di lato; passi regolari.","Due manubri leggeri.","Ginocchia sopra il bacino, zona lombare morbida a terra; espirando abbassa un tallone verso il pavimento.","Piedi a terra, fai scivolare un tallone in avanti.","Allunga braccio e gamba opposti, schiena dritta, pausa 2 s.","Solo la gamba, la punta scivola sul pavimento.",
# 120
"Sdraiati sul fianco, appoggio su avambraccio e ginocchia; solleva il bacino, corpo dritto.","In piedi, avambraccio appoggiato al muro.","Prima di alzarti, solleva dolcemente il pavimento pelvico e alzati espirando.","Inspira: pancia e costole si allargano dolcemente; espirazione lunga: le costole si chiudono, il pavimento pelvico sale dolcemente.","Sdraiati, ginocchia piegate; lascia scendere dolcemente le ginocchia da un lato e dall’altro.","Inspirando, lascia andare mentalmente il pavimento pelvico, pancia morbida.","Abbassa braccio e gamba opposti, zona lombare morbida a terra; espira mentre scendi.","Solo le gambe.","Senza pausa.","Appoggio su avambracci e punte, corpo dritto; non trattenere il respiro.",
# 130
"Appoggio su avambraccio e piedi, bacino sollevato, corpo dritto.","Manubrio in una mano; non inclinarti verso di esso; solleva il pavimento pelvico prima di prendere il manubrio da terra.","Ginocchio sul tappetino, l’altro piede avanti; porta dolcemente il bacino avanti fino ad allungare la parte anteriore della coscia.","Senza manubrio.","Plank a braccia tese; porta lentamente un ginocchio al petto e torna, bacino fermo.","Plank sugli avambracci, 30 s.","Plank laterale: abbassa il bacino e risollevalo.","A quattro zampe, solleva le ginocchia di 3 cm da terra, schiena dritta, senza trattenere il respiro.","Ginocchia a terra, bird dog.","Braccio dritto sopra la spalla, costole giù; passi regolari.",
# 140
"Manubrio alla spalla.","In piedi vicino a un appoggio, cerchi con caviglia e ginocchio nei due sensi.","Tenendoti alla sedia, rulla dal tallone alla punta e ritorno.","Mano sullo schienale, stai su una gamba; se è facile, senza appoggio.","Vicino al muro: metti il tallone attaccato alla punta dell’altro piede, sguardo avanti.","Passi più corti, mano al muro.","Su una gamba vicino a un appoggio, tocca il pavimento con la punta dell’altro piede davanti, di lato e dietro.","Tieniti con entrambe le mani.","Passo di lato alzando bene il ginocchio, come sopra un ostacolo.","Su una gamba, piegati a schiena dritta; l’altra gamba va indietro.",
# 150
"La punta dell’altro piede tocca il pavimento.","Vicino a un appoggio: al comando, passo avanti, di lato o indietro, e ritorna.","Solo passi laterali.","Mani al muro, una gamba indietro, tallone a terra; porta il bacino avanti fino ad allungare il polpaccio.","Seduti, fai rotolare il piede su una pallina o su calzini arrotolati.","Testa lentamente a semicerchio da spalla a spalla, poi cerchi con spalle e braccia.","Non piegare la testa all’indietro.","A quattro zampe, cerchi lenti con il bacino.","Sdraiati sul fianco, ginocchia piegate; il braccio sopra si apre indietro, lo sguardo segue la mano.","Espirando solleva il bacino staccando la schiena una vertebra alla volta; scendi allo stesso modo.",
# 160
"Tallone sulla sedia, gamba dritta; dondola dolcemente avanti e indietro a schiena dritta.","Seduti: cerchi con i piedi, rullate tallone-punta, le dita «suonano il pianoforte» una alla volta.","Sdraiati sulla schiena, polpacci sulla seduta della sedia; respiro calmo, zona lombare rilassata.","Marcia sul posto, un po’ più veloce ogni mezzo minuto.","Sali e scendi dal gradino a ritmo regolare, tutto il piede sul gradino.","Mano al muro.","15 s più veloce, ma a metà intensità; poi marcia tranquilla.","Salta a gambe aperte e braccia in alto, salta per tornare; atterraggio morbido.","Passi laterali alzando le braccia.","Corsa sul posto, ginocchia più alte, atterraggio morbido.",
# 170
"Marcia veloce a ginocchia alte.","Marcia tranquilla sul posto, il respiro si calma.","Allunga la parte anteriore e posteriore della coscia, i polpacci e il petto: 20–30 s ciascuno.","Mano al muro, gradino più basso.","Tallone sul gradino, gamba dritta; piegati in avanti a schiena dritta.","Salto da squat poco profondo, poi salti da un lato all’altro; atterraggio morbido.","Gradino più basso, senza manubri.","Tallone avanti, piegati a schiena dritta; poi, seduti, caviglia sul ginocchio.","Mani sul bordo di un tavolo o sulla seduta di una sedia, corpo dritto; petto al bordo, spingi via espirando.","Al muro.",
# 180
"Piedi sulla sedia, mani a terra, corpo dritto; scendi in 3 tempi. Con la pressione alta, da terra.","Piegamenti normali.","Distensione da sdraiati con pausa di 1 s in basso; risali espirando.","Allunga la parte anteriore e posteriore della coscia e i glutei: 20–30 s ciascuno.","Espira, solleva il pavimento pelvico e il bacino; scendendo, rilascia.","Marcia sul posto sempre più veloce, cerchi con spalle e bacino, squat morbidi.","Marcia veloce sul posto, braccia molto attive.","Passo di lato e ritorno, le braccia salgono di lato verso l’alto.","Passo indietro, poi ginocchio avanti e in alto; cambia gamba.","In piedi, pugni nell’aria in avanti con passi leggeri; gomiti morbidi.",
# 190
"Marcia sul posto sempre più lenta, il respiro si calma.","Allungamento dei polpacci al muro e delle cosce: 20–30 s ciascuno.","Marcia accelerando, step-up, poi due accelerazioni di prova a metà intensità.","Squat e, risalendo, braccia in alto; ritmo veloce, ginocchia morbide.","Più lento.","Passo ampio di lato e ritorno, veloce.","Ripeti gli esercizi 1–5 ancora una volta.","Marcia tranquilla, respiro profondo, poi allungamento di polpacci e cosce.","In piedi vicino al muro, spingi il palmo contro il muro verso l’esterno e poi verso l’interno: 10 s ciascuno, senza trattenere il respiro.","Seduti a terra, gambe piegate a 90°; porta dolcemente le ginocchia dall’altra parte.",
# 200
"Schiena al muro, scendi fino a un angolo comodo e mantieni; senza trattenere il respiro.","Resta più in alto.","Punta del piede al muro, il ginocchio va verso il muro; poi cerchi con il piede.","Sdraiati, ginocchia piegate: inspira, pancia e costole si allargano e il pavimento pelvico si rilassa; espira, le costole si chiudono e il pavimento pelvico sale dolcemente.","Solleva il pavimento pelvico come attraverso una cannuccia, tieni 2 s, rilascia 2 s. Glutei e addome rilassati.","Solleva rapidamente il pavimento pelvico e lascia subito.","Sdraiati, ginocchia piegate; la zona lombare preme dolcemente sul pavimento e si rilascia.","Solleva il pavimento pelvico, tieni 5 s, rilascia 5 s. Glutei e addome rilassati.","Tieni 3 s.","Solleva dolcemente il pavimento pelvico un secondo prima di tossire o sollevare il manubrio.",
# 210
"Seduti dritti: inspira, pancia e costole si allargano; espirazione lunga, le costole si chiudono.","Inspira dal naso in 4 tempi, espira in 6.","Sdraiati: inspira, pancia e costole si allargano; espira, si chiudono dolcemente.","Come per trattenere il flusso: solleva, tieni 3 s, rilascia 3 s. Glutei e addome rilassati.","Solleva il pavimento pelvico, poi tossisci.","Solleva il pavimento pelvico prima di prendere il manubrio da terra.","Mano al muro: cammina di lato, poi all’indietro, sulle punte e sui talloni.","Passi più corti, entrambe le mani vicino al muro.","Sdraiati sul fianco, gamba dritta, punta verso di te; solleva poco, il bacino non ruota indietro.","Sdraiati sul fianco, ginocchia piegate, piedi uniti; apri il ginocchio sopra, bacino fermo.",
# 220
"Sdraiati, ginocchio sopra il bacino; piccoli cerchi nei due sensi, zona lombare tranquilla.","Testa sul tappetino, ginocchia piegate; braccia dritte che pulsano vicino al pavimento: 5 tempi inspirando, 5 espirando.","Testa sul tappetino; un ginocchio al petto, l’altra gamba si allunga in diagonale; cambia espirando.","A pancia in giù, sugli avambracci; il petto si solleva poco, sguardo a terra.","Seduti, braccio sopra la testa, inclinati di lato senza ruotare.","Ginocchia divaricate, bacino verso i talloni, braccia avanti, respira nella schiena.","Cuscino sotto il bacino.","In piedi, piedi sotto il bacino, la sommità della testa sale; respiro calmo dal naso.","Ginocchia morbide, il peso scorre lentamente da una gamba all’altra, le braccia fluttuano dietro.","Passo di lato; un palmo sale all’altezza della spalla, l’altro scende al fianco; cambia.",
# 230
"I palmi disegnano a turno un cerchio davanti al viso e alla pancia, con passo laterale.","Piede sul polpaccio, non sul ginocchio; mano su un appoggio.","Punta a terra, tallone vicino alla caviglia.","Gambe larghe, ginocchio davanti sopra il piede, braccia ai lati.","Gambe meno larghe, ginocchio meno piegato.","Bacino indietro come per sedersi, braccia in alto vicino alle orecchie.","Mani sulle cosce.","A pancia in giù, avambracci sotto le spalle, spalle giù.","Sdraiati sulla schiena, braccia leggermente aperte, attenzione sull’espirazione.",
]
