HPT = [
# 0
"Marche no lugar em ritmo confortável, braços balançando livremente para frente e para trás.","Pés na largura dos ombros, joelhos soltos; círculos lentos com o quadril para um lado e para o outro.","Joelhos levemente dobrados, quadril para trás, costas retas, mãos deslizam pelas coxas até os joelhos; ao subir, contraia os glúteos.","Deitado de costas, pés na largura do quadril; suba o quadril ao expirar e desça ao inspirar.","Suba o quadril só um pouco.","Cadeira atrás; quadril para trás, agache até a metade e levante ao expirar.","Apoie as mãos nas coxas.","Pés na largura dos ombros, quadril para trás, joelhos na direção dos pés; toque a cadeira e levante ao expirar.","Sente-se por completo e levante com ajuda das mãos; se o joelho doer, só até a profundidade confortável.","Joelhos levemente dobrados, costas retas, halteres deslizam pelas coxas até o meio da canela; ao subir, contraia os glúteos e expire.",
# 10
"Sem peso, mãos até os joelhos; se as costas doerem, amplitude menor.","Mão no encosto, passo para trás e desça; joelho da frente sobre o pé; empurre com a perna da frente.","Passo curto para trás e pouco profundo.","Segurando a cadeira, suba na ponta dos pés e desça suavemente nos calcanhares — o leve impacto faz bem ao osso.","Desça devagar, sem impacto.","Deitado, pés na largura do quadril; expire e eleve o assoalho pélvico — quadril para cima, pausa de 1 s, desça ao inspirar.","Sentado ereto, inspire pelo nariz e expire mais longo — os ombros descem.","Mão na cadeira, segure o pé e leve o calcanhar ao glúteo; joelhos juntos, sem arquear a lombar.","Puxe o pé com uma faixa ou toalha.","Calcanhar na cadeira ou no chão à frente, perna reta; incline-se com as costas retas até sentir um leve alongamento.",
# 20
"Mãos nos joelhos, círculos suaves com joelhos e quadril para os dois lados.","Mão na cadeira, passo curto para trás, desça um pouco e volte.","Deitado, expire e eleve o assoalho pélvico — quadril para cima, desça ao inspirar.","Pés na largura dos ombros, quadril para trás, joelhos alinhados com os pés, costas retas; suba ao expirar.","Agachamento até a cadeira.","Halter junto ao peito, quadril para trás, joelhos alinhados com os pés, costas retas; suba ao expirar.","Agachamento até a cadeira; se o joelho doer, profundidade confortável.","Costas retas, halteres junto às coxas até o meio da canela; ao subir, contraia os glúteos. Nunca arredonde as costas com peso.","Só até os joelhos, peso menor.","Passo para trás e desça; joelho da frente sobre o pé; empurre com a perna da frente.",
# 30
"Com uma mão no encosto, pouco profundo.","Saltos baixos, aterrissagem suave na parte da frente do pé, joelhos levemente dobrados.","Elevação dos calcanhares com descida suave.","A outra perna dobrada no ar; expire e eleve o assoalho pélvico — quadril para cima.","Ponte com os dois pés.","Pé inteiro no degrau, empurre pelo calcanhar, desça devagar.","Sem halteres, com a mão na parede.","Inspire pelo nariz e expire mais longo — o corpo relaxa.","Sentado na cadeira, tornozelo sobre o joelho oposto; incline-se com as costas retas.","Marcha no lugar, joelhos mais altos que o normal, braços trabalhando.",
# 40
"Círculos suaves com o quadril, depois joelhos, depois tornozelos — para os dois lados.","Passo para trás em afundo levantando os braços; volte e abaixe-os.","Sem os braços, apoiado na cadeira.","Quadril para cima, pausa de 2–3 s no alto, glúteos contraídos, costelas para baixo.","Pausa mais curta.","Agachamento e, no fim, alguns saltitos suaves no lugar.","Sem saltitos.","Halteres nos ombros ou ao lado do corpo; desça devagar em 3 tempos, suba com firmeza ao expirar.","Um halter junto ao peito, ritmo normal.","Mão na cadeira, halter na outra mão; costas e quadril nivelados, a perna livre vai para trás.",
# 50
"Os dedos do outro pé tocam o chão.","Pé de trás na cadeira, tronco um pouco à frente, joelho da frente sobre o pé.","Afundo para trás comum com apoio.","Agachamento pequeno — salto baixo — aterrissagem suave direto no agachamento.","Agachamento e elevação dos calcanhares.","Escápulas no assento da cadeira, halter no quadril; expire e eleve o assoalho pélvico — quadril para cima até a linha reta, pausa de 1 s.","Ponte no chão com halter.","Passo largo para o lado, quadril para trás, a outra perna reta; empurre para voltar.","Passo menor, sem halter.","Base larga; leve o peso para uma perna dobrando esse joelho; a outra perna fica reta.",
# 60
"Círculos lentos com os ombros para frente e para trás, pescoço relaxado.","Mãos nas coxas; ao expirar arredonde as costas, ao inspirar abra o peito.","Costas e cotovelos na parede; deslize os braços para cima e para baixo devagar, sem tirá-los da parede.","Suba menos os braços.","Mãos na parede na altura dos ombros, corpo reto; em direção à parede ao inspirar, empurre ao expirar.","Fique mais perto da parede.","Mão e joelho na cadeira, costas retas; puxe o halter com o cotovelo junto ao corpo até a cintura.","Sentado na cadeira, puxe os dois halteres até a cintura.","Costas retas, abdômen levemente ativado; empurre os halteres dos ombros para cima ao expirar.","Empurre para frente até a altura do rosto.",
# 70
"Halteres nas mãos estendidas, ombros para trás e para baixo, passos regulares pela sala.","Peso menor ou parado no lugar com os halteres.","De bruços, testa no tapete; ao expirar eleve o braço e a perna opostos alguns centímetros, pescoço longo.","Eleve só os braços, alternando.","Antebraço no batente da porta, passo suave à frente até sentir o peito alongar.","Puxe o braço reto contra o peito com a outra mão, ombro para baixo.","Círculos com os ombros e depois com os braços retos — devagar, para os dois lados.","De quatro apoios: ao expirar arredonde as costas, ao inspirar arqueie suavemente; a cabeça acompanha a coluna.","Mãos no assento ou no encosto de uma cadeira firme, corpo reto; desça devagar e empurre.","Flexões na parede.",
# 80
"Mãos um pouco mais abertas que os ombros, corpo reto dos joelhos à cabeça.","Na cadeira ou na parede.","Inclinado com as costas retas, joelhos soltos; halteres até a cintura, aproxime as escápulas.","Com uma mão, apoiado na cadeira.","Abdômen e glúteos levemente ativados, sem arquear a lombar; empurre os halteres dos ombros para cima ao expirar.","Sentado, até a altura do rosto.","Inclinado com as costas retas, braços levemente dobrados; abra halteres leves até a altura dos ombros.","Sem peso.","Deitado, joelhos dobrados; empurre os halteres do peito para cima ao expirar, cotovelos tocam o chão.","Peso menor ou um braço de cada vez.",
# 90
"Mão atrás da cabeça; com a outra mão puxe suavemente o cotovelo.","Corpo reto, desça devagar em 3 tempos, suba ao expirar.","Com os joelhos apoiados.","Mão e joelho na cadeira, costas retas; halter até a cintura, peso maior.","Peso menor.","Empurre o halter do ombro para cima com um braço; o tronco não inclina.","Com os dois braços sentado, até a altura do rosto.","Cotovelos levemente dobrados; eleve os halteres para os lados até a altura dos ombros, não mais.","Peso leve ou sem peso.","Empurre do peito e depois, com os braços retos, leve o halter para trás da cabeça e volte.",
# 100
"Só o supino.","Prancha alta, pés mais afastados; toque um ombro de cada vez, quadril estável.","Com os joelhos ou prancha nos antebraços sem toques.","Círculos com os ombros e depois com o quadril, devagar, para os dois lados.","Halter junto ao peito; pés um pouco mais afastados que os ombros, quadril para trás, toque a cadeira e levante ao expirar.","Sem halter, ajudando com as mãos.","Palma na parede atrás de você; gire o tronco devagar para longe da parede até sentir o peito alongar.","Círculos com os ombros, quadril e depois joelhos — devagar, para os dois lados.","Saltos suaves e baixos no lugar, depois de um lado para o outro; joelhos soltos.","Saltitos suaves na ponta dos pés, joelhos relaxados.",
# 110
"Elevações dos calcanhares.","Do agachamento com halteres nos ombros, levante e empurre para cima num só movimento.","Agachamento com halteres nos ombros, sem empurrar.","Mãos um pouco mais abertas que os ombros, corpo reto; desça ao inspirar, suba ao expirar.","Halter em uma mão; o tronco não inclina para o lado; passos regulares.","Dois halteres leves.","Joelhos sobre o quadril, lombar suavemente no chão; ao expirar desça um calcanhar ao chão.","Pés no chão, deslize um calcanhar para frente.","Estenda o braço e a perna opostos, costas retas, pausa de 2 s.","Só a perna, a ponta desliza no chão.",
# 120
"Deitado de lado, apoio no antebraço e nos joelhos; eleve o quadril, corpo reto.","Em pé, antebraço apoiado na parede.","Antes de levantar, eleve suavemente o assoalho pélvico e levante ao expirar.","Inspire — barriga e costelas se expandem suavemente; expiração longa — costelas se fecham, o assoalho pélvico sobe suavemente.","Deitado, joelhos dobrados; deixe os joelhos caírem suavemente para um lado e para o outro.","Ao inspirar, solte mentalmente o assoalho pélvico, barriga macia.","Desça o braço e a perna opostos, lombar suavemente no chão; expire ao descer.","Só as pernas.","Sem pausa.","Apoio nos antebraços e nas pontas dos pés, corpo reto; não prenda a respiração.",
# 130
"Apoio no antebraço e nos pés, quadril elevado, corpo reto.","Halter em uma mão; não incline para o halter; eleve o assoalho pélvico antes de pegar o halter do chão.","Joelho no tapete, a outra perna à frente; leve o quadril suavemente à frente até sentir a frente da coxa alongar.","Sem halter.","Prancha alta; traga um joelho devagar ao peito e volte, quadril estável.","Prancha nos antebraços, 30 s.","Prancha lateral: desça o quadril e suba de novo.","De quatro apoios, tire os joelhos 3 cm do chão, costas retas, sem prender a respiração.","Joelhos no chão, perdigueiro.","Braço reto acima do ombro, costelas para baixo; passos regulares.",
# 140
"Halter no ombro.","Em pé junto a um apoio, círculos com o tornozelo e o joelho para os dois lados.","Segurando a cadeira, role do calcanhar para a ponta do pé e volte.","Mão no encosto, fique numa perna; se estiver fácil, sem apoio.","Junto à parede: coloque o calcanhar colado à ponta do outro pé, olhar à frente.","Passos mais curtos, mão na parede.","Numa perna junto a um apoio, toque o chão com a ponta do outro pé à frente, ao lado e atrás.","Segure com as duas mãos.","Passo para o lado elevando bem o joelho, como sobre um obstáculo.","Numa perna, incline-se com as costas retas; a outra perna vai para trás.",
# 150
"A ponta do outro pé toca o chão.","Junto a um apoio: ao comando, passo à frente, ao lado ou atrás, e volte.","Só passos laterais.","Mãos na parede, uma perna atrás, calcanhar no chão; leve o quadril à frente até sentir a panturrilha.","Sentado, role o pé sobre uma bola ou meias enroladas.","Cabeça devagar em meio círculo de ombro a ombro, depois círculos com ombros e braços.","Não jogue a cabeça para trás.","De quatro apoios, círculos lentos com o quadril.","Deitado de lado, joelhos dobrados; o braço de cima abre para trás, o olhar acompanha a mão.","Ao expirar eleve o quadril, descolando as costas vértebra por vértebra; desça do mesmo jeito.",
# 160
"Calcanhar na cadeira, perna reta; balance suavemente para frente e para trás com as costas retas.","Sentado: círculos com os pés, rolamentos do calcanhar à ponta, os dedos «tocam piano» um por um.","Deitado de costas, panturrilhas no assento da cadeira; respiração calma, lombar relaxada.","Marcha no lugar, um pouco mais rápido a cada meio minuto.","Suba e desça do degrau em ritmo regular, pé inteiro no degrau.","Mão na parede.","15 s mais rápido, mas a meia intensidade; depois marcha tranquila.","Salte abrindo as pernas e levantando os braços, salte de volta; aterrissagem suave.","Passos laterais levantando os braços.","Corrida no lugar, joelhos mais altos, aterrissagem suave.",
# 170
"Marcha rápida com joelhos altos.","Marcha tranquila no lugar, a respiração se acalma.","Alongue a frente e a parte de trás da coxa, panturrilhas e peito — 20–30 s cada.","Mão na parede, degrau mais baixo.","Calcanhar no degrau, perna reta; incline-se com as costas retas.","Salto a partir de agachamento raso, depois saltos de um lado para o outro; aterrissagem suave.","Degrau mais baixo, sem halteres.","Calcanhar à frente, incline-se com as costas retas; depois, sentado, tornozelo sobre o joelho.","Mãos na borda da mesa ou no assento da cadeira, corpo reto; peito até a borda, empurre ao expirar.","Na parede.",
# 180
"Pés na cadeira, mãos no chão, corpo reto; desça em 3 tempos. Com pressão alta, do chão.","Flexões normais.","Supino deitado com pausa de 1 s embaixo, suba ao expirar.","Alongue a frente e a parte de trás da coxa e os glúteos — 20–30 s cada.","Expire — eleve o assoalho pélvico — quadril para cima; ao descer, solte.","Marcha no lugar cada vez mais rápida, círculos com ombros e quadril, agachamentos suaves.","Marcha rápida no lugar, braços bem ativos.","Passo para o lado e de volta, os braços sobem pelas laterais.","Passo para trás e depois joelho à frente e para cima; troque de perna.","Em pé, socos no ar para frente com passos leves; cotovelos soltos.",
# 190
"Marcha no lugar cada vez mais lenta, a respiração se acalma.","Alongamento das panturrilhas na parede e das coxas — 20–30 s cada.","Marcha acelerando, subidas no degrau e depois duas acelerações de teste a meia intensidade.","Agachamento e, ao subir, braços para cima; ritmo rápido, joelhos soltos.","Mais devagar.","Passo largo para o lado e de volta, rápido.","Repita os exercícios 1–5 mais uma vez.","Marcha tranquila, respiração profunda e depois alongamento de panturrilhas e coxas.","Em pé junto à parede, pressione a palma na parede para fora e depois para dentro — 10 s cada, sem prender a respiração.","Sentado no chão, pernas dobradas a 90°; leve os joelhos suavemente para o outro lado.",
# 200
"Costas na parede, desça até um ângulo confortável e segure; sem prender a respiração.","Fique mais alto.","Ponta do pé na parede, o joelho vai em direção à parede; depois círculos com o pé.","Deitado, joelhos dobrados: inspire — barriga e costelas se expandem, o assoalho pélvico relaxa; expire — as costelas se fecham, o assoalho pélvico sobe suavemente.","Eleve o assoalho pélvico como se puxasse por um canudo, segure 2 s, relaxe 2 s. Glúteos e abdômen relaxados.","Eleve o assoalho pélvico rapidamente e solte logo.","Deitado, joelhos dobrados; a lombar pressiona suavemente o chão e solta.","Eleve o assoalho pélvico, segure 5 s, relaxe 5 s. Glúteos e abdômen relaxados.","Segure 3 s.","Eleve suavemente o assoalho pélvico um segundo antes de tossir ou levantar o halter.",
# 210
"Sentado ereto: inspire — barriga e costelas se expandem; expiração longa — as costelas se fecham.","Inspire pelo nariz em 4 tempos e expire em 6.","Deitado: inspire — barriga e costelas se expandem, expire — se fecham suavemente.","Como se segurasse o xixi: eleve, segure 3 s, solte 3 s. Glúteos e abdômen relaxados.","Eleve o assoalho pélvico e depois tussa.","Eleve o assoalho pélvico antes de pegar o halter do chão.","Mão na parede: ande de lado, depois de costas, na ponta dos pés e nos calcanhares.","Passos mais curtos, as duas mãos perto da parede.","Deitado de lado, perna reta, ponta do pé para você; suba pouco, o quadril não rola para trás.","Deitado de lado, joelhos dobrados, pés juntos; abra o joelho de cima, quadril parado.",
# 220
"Deitado, joelho sobre o quadril; círculos pequenos para os dois lados, lombar tranquila.","Cabeça no tapete, joelhos dobrados; braços retos pulsam perto do chão: 5 tempos inspirando, 5 expirando.","Cabeça no tapete; um joelho ao peito, a outra perna estende na diagonal; troque ao expirar.","De bruços, apoio nos antebraços; o peito sobe pouco, olhar para o chão.","Sentado, braço acima da cabeça, incline para o lado sem girar.","Joelhos afastados, quadril em direção aos calcanhares, braços à frente, respire nas costas.","Travesseiro sob o quadril.","Em pé, pés sob o quadril, o topo da cabeça cresce para cima; inspiração calma pelo nariz.","Joelhos soltos, o peso passa devagar de uma perna à outra, os braços flutuam junto.","Passo para o lado; uma palma sobe à altura do ombro, a outra desce ao quadril; troque.",
# 230
"As palmas desenham, uma de cada vez, um círculo diante do rosto e da barriga, com passo lateral.","Pé na canela, não no joelho; mão num apoio.","Ponta do pé no chão, calcanhar junto ao tornozelo.","Base larga, joelho da frente sobre o pé, braços para os lados.","Base mais estreita, joelho menos dobrado.","Quadril para trás como ao sentar numa cadeira, braços para cima junto às orelhas.","Mãos nas coxas.","De bruços, antebraços sob os ombros, ombros para baixo.","Deitado de costas, braços levemente afastados, atenção na expiração.",
]
HFR = [
# 0
"Marchez sur place à un rythme confortable, les bras se balancent librement d’avant en arrière.","Pieds à largeur d’épaules, genoux souples ; cercles lents du bassin dans un sens puis dans l’autre.","Genoux légèrement fléchis, bassin vers l’arrière, dos plat, les mains glissent sur les cuisses jusqu’aux genoux ; en remontant, serrez les fessiers.","Sur le dos, pieds à largeur de hanches ; montez le bassin en expirant, redescendez en inspirant.","Montez le bassin seulement un peu.","Chaise derrière vous ; bassin en arrière, descendez à mi-hauteur et remontez en expirant.","Appuyez les mains sur les cuisses.","Pieds à largeur d’épaules, bassin en arrière, genoux dans l’axe des pieds ; touchez la chaise et remontez en expirant.","Asseyez-vous complètement et relevez-vous avec l’aide des mains ; si le genou fait mal, seulement jusqu’à une profondeur confortable.","Genoux légèrement fléchis, dos plat, les haltères glissent le long des cuisses jusqu’à mi-tibia ; en remontant, serrez les fessiers, expirez.",
# 10
"Sans poids, mains jusqu’aux genoux ; si le dos fait mal, amplitude réduite.","Main sur le dossier, pas en arrière et descendez ; genou avant au-dessus du pied ; poussez avec la jambe avant.","Petit pas en arrière, peu profond.","En tenant la chaise, montez sur la pointe des pieds et retombez doucement sur les talons — le petit impact est bon pour l’os.","Redescendez lentement, sans impact.","Sur le dos, pieds à largeur de hanches ; expirez et remontez le périnée — bassin en haut, pause 1 s, redescendez en inspirant.","Assis bien droit, inspirez par le nez, expirez plus longtemps — les épaules descendent.","Main sur la chaise, attrapez le pied et ramenez le talon vers la fesse ; genoux côte à côte, sans cambrer.","Ramenez le pied avec une sangle ou une serviette.","Talon sur la chaise ou au sol devant, jambe tendue ; penchez-vous dos plat jusqu’à un léger étirement.",
# 20
"Mains sur les genoux, cercles doux des genoux et du bassin dans les deux sens.","Main sur la chaise, petit pas en arrière, descendez un peu et revenez.","Sur le dos, expirez et remontez le périnée — bassin en haut, redescendez en inspirant.","Pieds à largeur d’épaules, bassin en arrière, genoux dans l’axe des orteils, dos plat ; remontez en expirant.","Squat vers la chaise.","Haltère contre la poitrine, bassin en arrière, genoux dans l’axe des orteils, dos plat ; remontez en expirant.","Squat vers la chaise ; si le genou fait mal, profondeur confortable.","Dos plat, haltères le long des cuisses jusqu’à mi-tibia ; en remontant, serrez les fessiers. Ne jamais arrondir le dos avec une charge.","Seulement jusqu’aux genoux, charge plus légère.","Pas en arrière, descendez ; genou avant au-dessus du pied ; poussez avec la jambe avant.",
# 30
"Une main sur le dossier, peu profond.","Petits sauts, réception douce sur l’avant du pied, genoux légèrement fléchis.","Montées sur pointes avec descente douce sur les talons.","L’autre jambe fléchie en l’air ; expirez et remontez le périnée — bassin en haut.","Pont sur les deux pieds.","Tout le pied sur la marche, poussez par le talon, redescendez lentement.","Sans haltères, main au mur.","Inspirez par le nez, expirez plus longtemps — le corps se détend.","Assis sur la chaise, cheville sur le genou opposé ; penchez-vous dos plat.","Marche sur place, genoux plus hauts que d’habitude, les bras travaillent.",
# 40
"Cercles doux du bassin, puis des genoux, puis des chevilles — dans les deux sens.","Pas en arrière en fente en levant les bras ; revenez, bras en bas.","Sans les bras, avec appui sur la chaise.","Bassin en haut, pause 2–3 s, fessiers serrés, côtes basses.","Pause plus courte.","Squat puis, à la fin, quelques petits rebonds sur place.","Sans rebonds.","Haltères aux épaules ou le long du corps ; descendez lentement en 3 temps, remontez franchement en expirant.","Un haltère contre la poitrine, rythme normal.","Main sur la chaise, haltère dans l’autre main ; dos et bassin à niveau, la jambe libre part en arrière.",
# 50
"Les orteils de l’autre pied touchent le sol.","Pied arrière sur la chaise, buste légèrement en avant, genou avant au-dessus du pied.","Fente arrière classique avec appui.","Petit squat — petit saut — réception douce directement en squat.","Squat et montée sur pointes.","Omoplates sur l’assise de la chaise, haltère sur les hanches ; expirez et remontez le périnée — bassin en haut jusqu’à la ligne droite, pause 1 s.","Pont au sol avec un haltère.","Grand pas sur le côté, bassin en arrière, l’autre jambe tendue ; poussez pour revenir.","Pas plus petit, sans haltère.","Appui large ; transférez le poids sur une jambe en fléchissant ce genou ; l’autre jambe reste tendue.",
# 60
"Cercles lents des épaules vers l’avant et l’arrière, nuque détendue.","Mains sur les cuisses ; en expirant arrondissez le dos, en inspirant ouvrez la poitrine.","Dos et coudes contre le mur ; faites glisser lentement les bras de haut en bas sans quitter le mur.","Montez moins les bras.","Paumes au mur à hauteur d’épaules, corps droit ; vers le mur en inspirant, poussez en expirant.","Rapprochez-vous du mur.","Main et genou sur la chaise, dos plat ; tirez l’haltère, coude le long du corps, jusqu’à la taille.","Assis sur la chaise, tirez les deux haltères vers la taille.","Dos droit, ventre légèrement engagé ; poussez les haltères des épaules vers le haut en expirant.","Poussez vers l’avant jusqu’à hauteur du visage.",
# 70
"Haltères dans les mains bras tendus, épaules en arrière et en bas, pas réguliers dans la pièce.","Charge plus légère, ou rester sur place avec les haltères.","À plat ventre, front sur le tapis ; en expirant, soulevez le bras et la jambe opposés de quelques centimètres, nuque longue.","Soulevez seulement les bras, en alternance.","Avant-bras sur l’encadrement de la porte, petit pas en avant jusqu’à l’étirement de la poitrine.","Ramenez le bras tendu contre la poitrine avec l’autre main, épaule basse.","Cercles des épaules, puis des bras tendus — lentement, dans les deux sens.","À quatre pattes : en expirant arrondissez le dos, en inspirant creusez doucement ; la tête suit le dos.","Mains sur l’assise ou le dossier d’une chaise stable, corps droit ; descendez lentement et poussez.","Pompes contre le mur.",
# 80
"Mains un peu plus larges que les épaules, corps droit des genoux à la tête.","Sur une chaise ou contre le mur.","Penché dos plat, genoux souples ; haltères vers la taille, serrez les omoplates.","À un bras avec appui sur la chaise.","Ventre et fessiers légèrement engagés, sans cambrer ; poussez les haltères des épaules vers le haut en expirant.","Assis, jusqu’à hauteur du visage.","Penché dos plat, bras légèrement fléchis ; écartez des haltères légers jusqu’à hauteur d’épaules.","Sans poids.","Sur le dos, genoux fléchis ; poussez les haltères depuis la poitrine en expirant, les coudes touchent le sol.","Charge plus légère ou un bras à la fois.",
# 90
"Main derrière la tête ; avec l’autre main, tirez doucement le coude.","Corps droit, descendez lentement en 3 temps, remontez en expirant.","Sur les genoux.","Main et genou sur la chaise, dos plat ; haltère vers la taille, charge plus lourde.","Charge plus légère.","Poussez l’haltère de l’épaule vers le haut d’un bras ; le buste ne penche pas.","À deux bras assis, jusqu’à hauteur du visage.","Coudes légèrement fléchis ; montez les haltères sur les côtés jusqu’à hauteur d’épaules, pas plus haut.","Charge légère ou sans poids.","Développé depuis la poitrine, puis bras tendus, amenez l’haltère derrière la tête et revenez.",
# 100
"Seulement le développé.","Planche bras tendus, pieds plus écartés ; touchez une épaule puis l’autre, bassin stable.","Sur les genoux, ou planche sur les avant-bras sans touches.","Cercles des épaules, puis du bassin, lentement, dans les deux sens.","Haltère contre la poitrine ; pieds un peu plus larges que les épaules, bassin en arrière, touchez la chaise et remontez en expirant.","Sans haltère, en vous aidant des mains.","Paume au mur derrière vous ; tournez lentement le buste en vous éloignant du mur jusqu’à l’étirement de la poitrine.","Cercles des épaules, du bassin puis des genoux — lentement, dans les deux sens.","Petits sauts doux sur place, puis d’un côté à l’autre ; genoux souples.","Petits rebonds doux sur l’avant des pieds, genoux détendus.",
# 110
"Montées sur pointes.","Depuis le squat, haltères aux épaules, remontez et poussez vers le haut en un seul mouvement.","Squat avec haltères aux épaules, sans développé.","Mains un peu plus larges que les épaules, corps droit ; descendez en inspirant, remontez en expirant.","Haltère dans une main ; le buste ne penche pas sur le côté ; pas réguliers.","Deux haltères légers.","Genoux au-dessus des hanches, bas du dos doucement plaqué ; en expirant, descendez un talon vers le sol.","Pieds au sol, faites glisser un talon vers l’avant.","Allongez le bras et la jambe opposés, dos plat, pause 2 s.","Seulement la jambe, les orteils glissent au sol.",
# 120
"Allongé sur le côté, appui sur l’avant-bras et les genoux ; montez le bassin, corps droit.","Debout, avant-bras appuyé contre le mur.","Avant de vous lever, remontez doucement le périnée et levez-vous en expirant.","Inspiration — ventre et côtes s’ouvrent doucement ; longue expiration — les côtes se referment, le périnée remonte doucement.","Sur le dos, genoux fléchis ; laissez doucement tomber les genoux d’un côté puis de l’autre.","En inspirant, relâchez mentalement le périnée, ventre souple.","Descendez le bras et la jambe opposés, bas du dos doucement plaqué ; expirez en descendant.","Seulement les jambes.","Sans pause.","Appui sur les avant-bras et les orteils, corps droit ; ne bloquez pas la respiration.",
# 130
"Appui sur l’avant-bras et les pieds, bassin levé, corps droit.","Haltère dans une main ; ne penchez pas vers lui ; remontez le périnée avant de ramasser l’haltère au sol.","Genou au tapis, l’autre pied devant ; avancez doucement le bassin jusqu’à l’étirement de l’avant de la cuisse.","Sans haltère.","Planche bras tendus ; amenez lentement un genou vers la poitrine et revenez, bassin stable.","Planche sur les avant-bras, 30 s.","Planche latérale : descendez le bassin et remontez-le.","À quatre pattes, décollez les genoux de 3 cm, dos plat, sans bloquer la respiration.","Genoux au sol, bird dog.","Bras tendu au-dessus de l’épaule, côtes basses ; pas réguliers.",
# 140
"Haltère à l’épaule.","Debout près d’un appui, cercles de la cheville et du genou dans les deux sens.","En tenant la chaise, roulez du talon à la pointe et revenez.","Main sur le dossier, tenez sur une jambe ; si c’est facile, sans appui.","Près du mur : posez le talon collé aux orteils de l’autre pied, regard devant.","Pas plus courts, main au mur.","Sur une jambe près d’un appui, touchez le sol avec les orteils de l’autre pied devant, sur le côté et derrière.","Tenez-vous des deux mains.","Pas de côté en levant haut le genou, comme pour enjamber un obstacle.","Sur une jambe, penchez-vous dos plat, l’autre jambe part en arrière.",
# 150
"Les orteils de l’autre pied touchent le sol.","Près d’un appui : au signal, faites un pas devant, sur le côté ou derrière, puis revenez.","Seulement des pas de côté.","Mains au mur, une jambe en arrière, talon au sol ; avancez le bassin jusqu’à l’étirement du mollet.","Assis, faites rouler le pied sur une balle ou des chaussettes roulées.","La tête décrit lentement un demi-cercle d’une épaule à l’autre, puis cercles des épaules et des bras.","Ne basculez pas la tête en arrière.","À quatre pattes, cercles lents du bassin.","Allongé sur le côté, genoux fléchis ; le bras du dessus s’ouvre vers l’arrière, le regard suit la main.","En expirant, montez le bassin en décollant le dos vertèbre par vertèbre ; redescendez de même.",
# 160
"Talon sur la chaise, jambe tendue ; balancez-vous doucement d’avant en arrière, dos plat.","Assis : cercles des pieds, roulés du talon à la pointe, les orteils « jouent du piano » un par un.","Sur le dos, mollets sur l’assise de la chaise ; respiration calme, bas du dos détendu.","Marche sur place, un peu plus vite toutes les trente secondes.","Montez et descendez la marche à rythme régulier, tout le pied sur la marche.","Main au mur.","15 s plus vite, mais à mi-effort ; puis marche tranquille.","Sautez jambes écartées bras en l’air, sautez pour revenir ; réception douce.","Pas de côté en levant les bras.","Course sur place, genoux plus hauts, réception douce.",
# 170
"Marche rapide genoux hauts.","Marche tranquille sur place, la respiration se calme.","Étirez l’avant et l’arrière de la cuisse, les mollets et la poitrine — 20–30 s chacun.","Main au mur, marche plus basse.","Talon sur la marche, jambe tendue ; penchez-vous dos plat.","Saut depuis un squat peu profond, puis sauts d’un côté à l’autre ; réception douce.","Marche plus basse, sans haltères.","Talon devant, penchez-vous dos plat ; puis, assis, cheville sur le genou.","Mains au bord d’une table ou sur l’assise d’une chaise, corps droit ; poitrine vers le bord, poussez en expirant.","Contre le mur.",
# 180
"Pieds sur la chaise, mains au sol, corps droit ; descendez en 3 temps. En cas de tension élevée — depuis le sol.","Pompes classiques.","Développé couché avec pause de 1 s en bas, remontez en expirant.","Étirez l’avant et l’arrière de la cuisse et les fessiers — 20–30 s chacun.","Expirez — remontez le périnée — bassin en haut ; en redescendant, relâchez.","Marche sur place de plus en plus vite, cercles des épaules et du bassin, squats doux.","Marche rapide sur place, bras très actifs.","Pas de côté et retour, les bras montent par les côtés.","Pas en arrière, puis genou vers l’avant et le haut ; changez de jambe.","Debout, coups de poing dans le vide vers l’avant avec des pas légers ; coudes souples.",
# 190
"Marche sur place de plus en plus lente, la respiration se calme.","Étirement des mollets au mur et des cuisses — 20–30 s chacun.","Marche en accélérant, montées sur marche, puis deux accélérations d’essai à mi-effort.","Squat et, en remontant, bras en l’air ; rythme rapide, genoux souples.","Plus lentement.","Grand pas sur le côté et retour, vite.","Répétez les exercices 1–5 une fois de plus.","Marche tranquille, respiration profonde, puis étirement des mollets et des cuisses.","Debout près du mur, poussez la paume contre le mur vers l’extérieur puis vers l’intérieur — 10 s chacun, sans bloquer la respiration.","Assis au sol, jambes pliées à 90° ; basculez doucement les genoux de l’autre côté.",
# 200
"Dos au mur, descendez jusqu’à un angle confortable et tenez ; sans bloquer la respiration.","Restez plus haut.","Orteils contre le mur, le genou va vers le mur ; puis cercles du pied.","Sur le dos, genoux fléchis : inspiration — ventre et côtes s’ouvrent, le périnée se relâche ; expiration — les côtes se referment, le périnée remonte doucement.","Remontez le périnée comme avec une paille, tenez 2 s, relâchez 2 s. Fessiers et abdos détendus.","Contractez le périnée rapidement et relâchez aussitôt.","Sur le dos, genoux fléchis ; le bas du dos se plaque doucement au sol puis se relâche.","Remontez le périnée, tenez 5 s, relâchez 5 s. Fessiers et abdos détendus.","Tenez 3 s.","Remontez doucement le périnée une seconde avant de tousser ou de soulever l’haltère.",
# 210
"Assis bien droit : inspiration — ventre et côtes s’ouvrent ; longue expiration — les côtes se referment.","Inspirez par le nez sur 4 temps, expirez sur 6.","Sur le dos : inspiration — ventre et côtes s’ouvrent, expiration — ils se referment doucement.","Comme pour retenir le jet : remontez, tenez 3 s, relâchez 3 s. Fessiers et abdos détendus.","Remontez le périnée, puis toussez.","Remontez le périnée avant de ramasser l’haltère au sol.","Main au mur : marchez de côté, puis à reculons, sur la pointe des pieds et sur les talons.","Pas plus courts, les deux mains près du mur.","Sur le côté, jambe tendue, pointe vers vous ; montez peu, le bassin ne bascule pas en arrière.","Sur le côté, genoux fléchis, pieds joints ; ouvrez le genou du dessus, bassin immobile.",
# 220
"Sur le dos, genou au-dessus de la hanche ; petits cercles dans les deux sens, bas du dos calme.","Tête sur le tapis, genoux fléchis ; bras tendus qui pulsent près du sol : 5 temps d’inspiration, 5 d’expiration.","Tête sur le tapis ; un genou vers la poitrine, l’autre jambe s’allonge en diagonale ; changez en expirant.","À plat ventre, sur les avant-bras ; la poitrine se soulève un peu, regard vers le sol.","Assis, bras au-dessus de la tête, inclinez-vous sur le côté sans tourner.","Genoux écartés, fesses vers les talons, bras devant, respirez dans le dos.","Coussin sous le bassin.","Debout, pieds sous les hanches, le sommet du crâne s’étire vers le haut ; inspiration calme par le nez.","Genoux souples, le poids passe lentement d’une jambe à l’autre, les bras suivent en flottant.","Pas de côté ; une paume monte à hauteur d’épaule, l’autre descend vers la hanche ; changez.",
# 230
"Les paumes dessinent tour à tour un cercle devant le visage et le ventre, avec un pas chassé.","Pied sur le mollet, pas sur le genou ; main sur un appui.","Orteils au sol, talon contre la cheville.","Appui large, genou avant au-dessus du pied, bras sur les côtés.","Appui plus étroit, genou moins fléchi.","Bassin en arrière comme pour s’asseoir, bras levés près des oreilles.","Mains sur les cuisses.","À plat ventre, avant-bras sous les épaules, épaules basses.","Sur le dos, bras légèrement écartés, attention sur l’expiration.",
]
