HES = [
# 0
"Marcha en el sitio a un ritmo cómodo, con los brazos balanceándose libremente.","Pies al ancho de los hombros, rodillas suaves; círculos lentos de cadera hacia un lado y hacia el otro.","Rodillas algo flexionadas, cadera atrás, espalda recta, las manos se deslizan por los muslos hasta las rodillas; al subir, aprieta los glúteos.","Boca arriba, pies al ancho de la cadera; sube la cadera al exhalar y bájala al inhalar.","Sube la cadera solo un poco.","Silla detrás; cadera atrás, baja a media sentadilla y sube al exhalar.","Apoya las manos en los muslos.","Pies al ancho de los hombros, cadera atrás, rodillas en la misma dirección que las puntas; toca la silla y sube al exhalar.","Siéntate del todo y levántate ayudándote con las manos; si duele la rodilla, baja solo hasta donde sea cómodo.","Rodillas algo flexionadas, espalda recta, las mancuernas bajan junto a los muslos hasta media tibia; al subir, aprieta glúteos y exhala.",
# 10
"Sin peso, manos hasta las rodillas; si duele la espalda, menos recorrido.","Mano en el respaldo, paso atrás y baja; rodilla delantera sobre el pie; empuja con la pierna delantera.","Paso corto atrás y poco profundo.","Sujetándote a la silla, sube de puntillas y deja caer suavemente los talones: el pequeño impacto es bueno para el hueso.","Baja despacio, sin impacto.","Boca arriba, pies al ancho de la cadera; exhala y eleva el suelo pélvico: cadera arriba, pausa de 1 s, baja al inhalar.","Sentado recto, inhala por la nariz y exhala más largo; los hombros bajan.","Mano en la silla, sujeta el pie y lleva el talón hacia el glúteo; rodillas juntas, sin arquear la zona lumbar.","Tira del pie con una cinta o una toalla.","Talón en la silla o en el suelo delante, pierna recta; inclínate con la espalda recta hasta notar un estiramiento suave.",
# 20
"Manos en las rodillas, círculos suaves de rodillas y cadera hacia ambos lados.","Mano en la silla, paso corto atrás, baja un poco y vuelve.","Boca arriba, exhala y eleva el suelo pélvico: cadera arriba; baja al inhalar.","Pies al ancho de los hombros, cadera atrás, rodillas en línea con las puntas, espalda recta; sube al exhalar.","Sentadilla a la silla.","Mancuerna al pecho, cadera atrás, rodillas en línea con las puntas, espalda recta; sube al exhalar.","Sentadilla a la silla; si duele la rodilla, profundidad cómoda.","Espalda recta, mancuernas junto a los muslos hasta media tibia; al subir, aprieta glúteos. Nunca redondees la espalda con peso.","Solo hasta las rodillas, menos peso.","Paso atrás y baja; rodilla delantera sobre el pie; empuja con la pierna delantera.",
# 30
"Con una mano en el respaldo, poco profundo.","Saltos bajos, aterrizaje suave sobre la parte delantera del pie, rodillas algo flexionadas.","Elevación de talones con bajada suave.","La otra pierna flexionada en el aire; exhala y eleva el suelo pélvico: cadera arriba.","Puente con los dos pies.","Todo el pie en el escalón, empuja con el talón, baja despacio.","Sin mancuernas, con la mano en la pared.","Inhala por la nariz y exhala más largo: el cuerpo se relaja.","Sentado en la silla, tobillo sobre la rodilla contraria; inclínate con la espalda recta.","Marcha en el sitio, rodillas más altas de lo habitual, brazos activos.",
# 40
"Círculos suaves de cadera, luego rodillas y luego tobillos, hacia ambos lados.","Paso atrás a zancada mientras subes los brazos; vuelve y bájalos.","Sin brazos, con apoyo en la silla.","Cadera arriba, pausa de 2–3 s, glúteos apretados, costillas abajo.","Pausa más corta.","Sentadilla y, al final, unos rebotes suaves en el sitio.","Sin rebotes.","Mancuernas a los hombros o junto al cuerpo; baja despacio en 3 tiempos y sube con firmeza al exhalar.","Una mancuerna al pecho, ritmo normal.","Mano en la silla, mancuerna en la otra mano; espalda y cadera niveladas, la pierna libre va hacia atrás.",
# 50
"Los dedos del otro pie tocan el suelo.","Pie trasero en la silla, tronco algo adelantado, rodilla delantera sobre el pie.","Zancada atrás normal con apoyo.","Sentadilla pequeña, salto bajo, aterrizaje suave directo a la sentadilla.","Sentadilla y elevación de talones.","Escápulas en el asiento de la silla, mancuerna en la cadera; exhala y eleva el suelo pélvico: cadera arriba hasta una línea recta, pausa de 1 s.","Puente en el suelo con mancuerna.","Paso amplio al lado, cadera atrás, la otra pierna recta; empuja para volver.","Paso más corto, sin mancuerna.","Postura amplia; lleva el peso a una pierna flexionando esa rodilla; la otra pierna recta.",
# 60
"Círculos lentos de hombros hacia delante y hacia atrás, cuello relajado.","Manos en los muslos; redondea la espalda al exhalar y abre el pecho al inhalar.","Espalda y codos contra la pared; desliza los brazos arriba y abajo sin despegarlos.","Sube menos los brazos.","Palmas en la pared a la altura de los hombros, cuerpo recto; hacia la pared al inhalar, empuja al exhalar.","Ponte más cerca de la pared.","Mano y rodilla en la silla, espalda recta; tira de la mancuerna con el codo pegado al cuerpo hasta la cintura.","Sentado en la silla, tira de las dos mancuernas hacia la cintura.","Espalda recta, abdomen suave activo; empuja las mancuernas desde los hombros hacia arriba al exhalar.","Empuja hacia delante a la altura de la cara.",
# 70
"Mancuernas en las manos bajadas, hombros atrás y abajo, pasos regulares por la habitación.","Menos peso o quieto en el sitio con las mancuernas.","Boca abajo, frente en la esterilla; al exhalar eleva el brazo y la pierna contrarios unos centímetros, cuello largo.","Eleva solo los brazos, alternando.","Antebrazo en el marco de la puerta, paso suave adelante hasta notar el estiramiento en el pecho.","Lleva el brazo recto contra el pecho con la otra mano, hombro abajo.","Círculos de hombros y luego de brazos rectos, despacio, hacia ambos lados.","A cuatro patas: redondea la espalda al exhalar y arquéala suave al inhalar; la cabeza sigue a la espalda.","Manos en el asiento o el respaldo de una silla estable, cuerpo recto; baja despacio y empuja.","Flexiones en la pared.",
# 80
"Manos algo más abiertas que los hombros, cuerpo recto de rodillas a cabeza.","En una silla o en la pared.","Inclinado con la espalda recta, rodillas suaves; mancuernas a la cintura, junta las escápulas.","A una mano con apoyo en la silla.","Abdomen y glúteos suaves activos, sin arquear la zona lumbar; empuja las mancuernas desde los hombros al exhalar.","Sentado, a la altura de la cara.","Inclinado con la espalda recta, brazos algo flexionados; abre mancuernas ligeras hasta la altura de los hombros.","Sin peso.","Boca arriba, rodillas flexionadas; empuja las mancuernas desde el pecho al exhalar, los codos tocan el suelo.","Menos peso o a una mano.",
# 90
"Mano detrás de la cabeza; con la otra mano tira suave del codo.","Cuerpo recto, baja despacio en 3 tiempos, sube al exhalar.","Con las rodillas apoyadas.","Mano y rodilla en la silla, espalda recta; mancuerna a la cintura, más peso.","Menos peso.","Empuja la mancuerna desde el hombro con un brazo; el tronco no se inclina.","A dos manos sentado, a la altura de la cara.","Codos algo flexionados; sube las mancuernas a los lados hasta los hombros, no más.","Poco peso o sin peso.","Press desde el pecho y luego, con brazos rectos, lleva la mancuerna detrás de la cabeza y vuelve.",
# 100
"Solo el press.","Plancha alta, pies más abiertos; toca un hombro y luego el otro, cadera estable.","Con rodillas o plancha de antebrazos sin toques.","Círculos de hombros y luego de cadera, despacio, hacia ambos lados.","Mancuerna al pecho; pies algo más abiertos que los hombros, cadera atrás, toca la silla y sube al exhalar.","Sin mancuerna, ayudándote con las manos.","Palma en la pared por detrás; gira el tronco despacio alejándote de la pared hasta notar el estiramiento en el pecho.","Círculos de hombros, cadera y luego rodillas, despacio, hacia ambos lados.","Saltos suaves y bajos en el sitio, luego de lado a lado; rodillas suaves.","Rebotes suaves sobre la punta de los pies, rodillas relajadas.",
# 110
"Elevaciones de talones.","Desde la sentadilla con mancuernas a los hombros, sube y empuja hacia arriba en un solo movimiento.","Sentadilla con mancuernas a los hombros, sin press.","Manos algo más abiertas que los hombros, cuerpo recto; baja al inhalar, sube al exhalar.","Mancuerna en una mano; el tronco no se inclina hacia el lado; pasos regulares.","Dos mancuernas ligeras.","Rodillas sobre la cadera, zona lumbar suave contra el suelo; al exhalar baja un talón al suelo.","Pies en el suelo, desliza un talón hacia delante.","Estira el brazo y la pierna contrarios, espalda recta, pausa de 2 s.","Solo la pierna, la punta se desliza por el suelo.",
# 120
"De lado, sobre el antebrazo y las rodillas; sube la cadera, cuerpo recto.","De pie, con el antebrazo apoyado en la pared.","Antes de levantarte, eleva suave el suelo pélvico y levántate al exhalar.","Inhala: abdomen y costillas se expanden suave; exhalación larga: las costillas se cierran y el suelo pélvico sube suave.","Boca arriba, rodillas flexionadas; deja caer las rodillas suave a un lado y al otro.","Al inhalar, suelta mentalmente el suelo pélvico, abdomen blando.","Baja el brazo y la pierna contrarios, zona lumbar suave contra el suelo; exhala al bajar.","Solo las piernas.","Sin pausa.","Sobre antebrazos y puntas de los pies, cuerpo recto; no contengas la respiración.",
# 130
"Sobre el antebrazo y los pies, cadera arriba, cuerpo recto.","Mancuerna en una mano; no te inclines hacia ella; eleva el suelo pélvico antes de levantar la mancuerna del suelo.","Rodilla en la esterilla, la otra pierna delante; lleva la cadera suave adelante hasta notar estiramiento en la parte delantera del muslo.","Sin mancuerna.","Plancha alta; lleva despacio una rodilla al pecho y vuelve, cadera estable.","Plancha de antebrazos, 30 s.","Plancha lateral: baja la cadera y vuelve a subirla.","A cuatro patas, despega las rodillas 3 cm del suelo, espalda recta, sin contener la respiración.","Rodillas en el suelo, pájaro-perro.","Brazo recto sobre el hombro, costillas abajo; pasos regulares.",
# 140
"Mancuerna al hombro.","De pie junto a un apoyo, círculos de tobillo y rodilla hacia ambos lados.","Sujetándote a la silla, rueda del talón a la punta y vuelve.","Mano en el respaldo, sobre una pierna; si es fácil, suelta el apoyo.","Junto a la pared: pon el talón pegado a la punta del otro pie, mirada al frente.","Pasos más cortos, mano en la pared.","Sobre una pierna junto a un apoyo, toca el suelo con la otra punta delante, al lado y detrás.","Sujétate con las dos manos.","Paso lateral subiendo mucho la rodilla, como por encima de un obstáculo.","Sobre una pierna, inclínate con la espalda recta; la otra pierna va hacia atrás.",
# 150
"La punta del otro pie toca el suelo.","Junto a un apoyo: a la orden, paso adelante, al lado o atrás, y vuelve.","Solo pasos laterales.","Manos en la pared, una pierna atrás, talón en el suelo; lleva la cadera adelante hasta notar el gemelo.","Sentado, rueda el pie sobre una pelota o unos calcetines enrollados.","Cabeza despacio en semicírculo de hombro a hombro, luego círculos de hombros y brazos.","No eches la cabeza hacia atrás.","A cuatro patas, círculos lentos de cadera.","De lado, rodillas flexionadas; el brazo de arriba se abre hacia atrás, la mirada lo sigue.","Al exhalar sube la cadera despegando la espalda vértebra a vértebra; baja igual.",
# 160
"Talón en la silla, pierna recta; balancéate suave adelante y atrás con la espalda recta.","Sentado: círculos de tobillos, balanceo talón-punta, los dedos «tocan el piano» uno a uno.","Boca arriba, gemelos en el asiento de la silla; respiración tranquila, zona lumbar relajada.","Marcha en el sitio, un poco más rápido cada medio minuto.","Sube y baja del escalón a ritmo regular, todo el pie en el escalón.","Mano en la pared.","15 s más rápido, pero a media intensidad; luego marcha tranquila.","Salta abriendo piernas y subiendo brazos, salta de vuelta; aterrizaje suave.","Pasos laterales subiendo los brazos.","Carrera en el sitio, rodillas más altas, aterrizaje suave.",
# 170
"Marcha rápida con rodillas altas.","Marcha tranquila en el sitio, la respiración se calma.","Estira la parte delantera y trasera del muslo, gemelos y pecho: 20–30 s cada uno.","Mano en la pared, escalón más bajo.","Talón en el escalón, pierna recta; inclínate con la espalda recta.","Salto desde sentadilla poco profunda y luego saltos de lado a lado; aterrizaje suave.","Escalón más bajo, sin mancuernas.","Talón adelante, inclínate con la espalda recta; luego, sentado, tobillo sobre la rodilla.","Manos en el borde de una mesa o asiento de silla, cuerpo recto; pecho al borde y empuja al exhalar.","En la pared.",
# 180
"Pies en la silla, manos en el suelo, cuerpo recto; baja en 3 tiempos. Con la presión alta, desde el suelo.","Flexiones normales.","Press tumbado con pausa de 1 s abajo; sube al exhalar.","Estira la parte delantera y trasera del muslo y los glúteos: 20–30 s cada uno.","Exhala, eleva el suelo pélvico y sube la cadera; al bajar, suéltalo.","Marcha en el sitio cada vez más rápido, círculos de hombros y cadera, sentadillas suaves.","Marcha rápida en el sitio, brazos muy activos.","Paso lateral y vuelta, los brazos suben por los lados.","Paso atrás y luego rodilla adelante y arriba; cambia de pierna.","De pie, golpes al aire hacia delante con pasos ligeros; codos suaves.",
# 190
"Marcha en el sitio cada vez más lenta, la respiración se calma.","Estiramiento de gemelos en la pared y de muslos: 20–30 s cada uno.","Marcha acelerando, subidas al escalón y luego dos aceleraciones de prueba a media intensidad.","Sentadilla y, al subir, brazos arriba; ritmo rápido, rodillas suaves.","Más despacio.","Paso amplio al lado y vuelta, rápido.","Repite los ejercicios 1–5 una vez más.","Marcha tranquila, respiración profunda y luego estiramiento de gemelos y muslos.","De pie junto a la pared, empuja la pared con la palma hacia fuera y luego hacia dentro: 10 s cada vez, sin contener la respiración.","Sentado en el suelo, piernas flexionadas a 90°; lleva las rodillas suavemente al otro lado.",
# 200
"Espalda contra la pared, baja hasta un ángulo cómodo y mantén; sin contener la respiración.","Quédate más arriba.","Punta del pie en la pared, la rodilla va hacia la pared; luego círculos de tobillo.","Boca arriba, rodillas flexionadas: inhala, abdomen y costillas se expanden y el suelo pélvico se relaja; exhala, las costillas se cierran y el suelo pélvico sube suave.","Eleva el suelo pélvico como si sorbieras con una pajita, mantén 2 s y relaja 2 s. Glúteos y abdomen relajados.","Eleva el suelo pélvico rápido y suéltalo enseguida.","Boca arriba, rodillas flexionadas; la zona lumbar se apoya suave en el suelo y se suelta.","Eleva el suelo pélvico, mantén 5 s, relaja 5 s. Glúteos y abdomen relajados.","Mantén 3 s.","Eleva suave el suelo pélvico un segundo antes de toser o levantar la mancuerna.",
# 210
"Sentado recto: inhala, abdomen y costillas se expanden; exhalación larga, las costillas se cierran.","Inhala por la nariz en 4 tiempos y exhala en 6.","Boca arriba: inhala, abdomen y costillas se expanden; exhala, se cierran suave.","Como si cortaras el chorro: eleva, mantén 3 s, suelta 3 s. Glúteos y abdomen relajados.","Eleva el suelo pélvico y luego tose.","Eleva el suelo pélvico antes de levantar la mancuerna del suelo.","Mano en la pared: camina de lado, luego hacia atrás, de puntillas y sobre los talones.","Pasos más cortos, las dos manos cerca de la pared.","De lado, pierna recta, punta hacia ti; sube poco, la cadera no rueda hacia atrás.","De lado, rodillas flexionadas, pies juntos; abre la rodilla de arriba, la cadera quieta.",
# 220
"Boca arriba, rodilla sobre la cadera; círculos pequeños hacia ambos lados, zona lumbar tranquila.","Cabeza en la esterilla, rodillas flexionadas; los brazos rectos rebotan cerca del suelo: 5 tiempos inhalando, 5 exhalando.","Cabeza en la esterilla; una rodilla al pecho y la otra pierna se estira en diagonal; cambia de pierna al exhalar.","Boca abajo, sobre los antebrazos; sube un poco el pecho, mirada al suelo.","Sentado, brazo por encima de la cabeza, inclínate al lado sin girar.","Rodillas separadas, cadera hacia los talones, brazos adelante, respira hacia la espalda.","Almohada bajo la cadera.","De pie, pies bajo la cadera, la coronilla crece hacia arriba; respiración tranquila por la nariz.","Rodillas suaves, el peso pasa despacio de una pierna a otra, los brazos flotan detrás.","Paso lateral; una palma sube a la altura del hombro y la otra baja a la cadera; cambia.",
# 230
"Las palmas dibujan por turnos un círculo delante de la cara y del abdomen, con paso lateral.","Pie en la pantorrilla, no en la rodilla; mano en un apoyo.","Punta en el suelo, talón junto al tobillo.","Postura amplia, rodilla delantera sobre el pie, brazos a los lados.","Postura más estrecha, rodilla menos flexionada.","Cadera atrás como al sentarte en una silla, brazos arriba junto a las orejas.","Manos en los muslos.","Boca abajo, antebrazos bajo los hombros, hombros abajo.","Boca arriba, brazos algo separados, atención en la exhalación.",
]
HDE = [
# 0
"Marschieren Sie in angenehmem Tempo auf der Stelle, die Arme schwingen locker vor und zurück.","Füße schulterbreit, Knie locker; langsame Hüftkreise in die eine und die andere Richtung.","Knie leicht gebeugt, Hüfte nach hinten, Rücken gerade, Hände gleiten über die Oberschenkel bis zu den Knien; beim Aufrichten das Gesäß anspannen.","In Rückenlage, Füße hüftbreit; beim Ausatmen die Hüfte heben, beim Einatmen senken.","Hüfte nur wenig anheben.","Stuhl hinter Ihnen; Hüfte nach hinten, halb in die Hocke und beim Ausatmen aufstehen.","Hände auf den Oberschenkeln abstützen.","Füße schulterbreit, Hüfte nach hinten, Knie zeigen in Richtung der Zehen; Stuhl berühren und beim Ausatmen aufstehen.","Ganz hinsetzen und mit Hilfe der Hände aufstehen; bei Knieschmerzen nur so tief wie angenehm.","Knie leicht gebeugt, Rücken gerade, die Hanteln gleiten an den Oberschenkeln bis zur Schienbeinmitte; beim Aufrichten Gesäß anspannen, ausatmen.",
# 10
"Ohne Gewicht, Hände bis zu den Knien; bei Rückenschmerzen kleinere Bewegung.","Hand auf der Stuhllehne, Schritt zurück, absenken; vorderes Knie über dem Fuß; mit dem vorderen Bein abdrücken.","Kleiner Schritt zurück, nicht tief.","Am Stuhl festhalten, auf die Zehen gehen und weich auf die Fersen fallen lassen — der leichte Stoß ist gut für die Knochen.","Langsam absenken, ohne Stoß.","In Rückenlage, Füße hüftbreit; ausatmen und Beckenboden anheben — Hüfte hoch, 1 s halten, beim Einatmen senken.","Aufrecht sitzen, durch die Nase einatmen, länger ausatmen — die Schultern sinken.","Hand am Stuhl, Fuß greifen und Ferse zum Gesäß ziehen; Knie nebeneinander, kein Hohlkreuz.","Fuß mit Gurt oder Handtuch heranziehen.","Ferse auf dem Stuhl oder vorne am Boden, Bein gestreckt; mit geradem Rücken vorbeugen bis zu leichter Dehnung.",
# 20
"Hände auf den Knien, sanfte Kreise mit Knien und Hüfte in beide Richtungen.","Hand am Stuhl, kleiner Schritt zurück, etwas absenken und zurück.","In Rückenlage ausatmen und Beckenboden anheben — Hüfte hoch, beim Einatmen senken.","Füße schulterbreit, Hüfte nach hinten, Knie in Linie mit den Zehen, Rücken gerade; beim Ausatmen hoch.","Kniebeuge zum Stuhl.","Hantel an der Brust, Hüfte nach hinten, Knie in Linie mit den Zehen, Rücken gerade; beim Ausatmen hoch.","Kniebeuge zum Stuhl; bei Knieschmerzen nur so tief wie angenehm.","Rücken gerade, Hanteln entlang der Oberschenkel bis zur Schienbeinmitte; beim Aufrichten Gesäß anspannen. Mit Gewicht nie den Rücken runden.","Nur bis zu den Knien, leichteres Gewicht.","Schritt zurück, absenken; vorderes Knie über dem Fuß; mit dem vorderen Bein abdrücken.",
# 30
"Mit einer Hand an der Stuhllehne, nicht tief.","Niedrige Sprünge, weiche Landung auf dem Vorfuß, Knie leicht gebeugt.","Wadenheben mit weichem Absenken auf die Fersen.","Das andere Bein gebeugt in der Luft; ausatmen und Beckenboden anheben — Hüfte hoch.","Brücke auf beiden Füßen.","Ganzer Fuß auf der Stufe, über die Ferse hochdrücken, langsam absenken.","Ohne Hanteln, Hand an der Wand.","Durch die Nase einatmen, länger ausatmen — der Körper entspannt sich.","Auf dem Stuhl sitzend, Knöchel auf das andere Knie; mit geradem Rücken vorbeugen.","Auf der Stelle marschieren, Knie höher als sonst, Arme arbeiten mit.",
# 40
"Sanfte Kreise mit Hüfte, dann Knien, dann Füßen — in beide Richtungen.","Schritt zurück in den Ausfallschritt, gleichzeitig Arme hoch; zurück, Arme runter.","Ohne Arme, mit Stütze am Stuhl.","Hüfte hoch, oben 2–3 s halten, Gesäß angespannt, Rippen bleiben unten.","Kürzere Pause.","Kniebeuge und am Ende ein paar weiche Federungen auf der Stelle.","Ohne Federn.","Hanteln an den Schultern oder neben dem Körper; in 3 Zählzeiten langsam absenken, beim Ausatmen kräftig hoch.","Eine Hantel an der Brust, normales Tempo.","Hand am Stuhl, Hantel in der anderen Hand; Rücken und Hüfte gerade, das freie Bein geht nach hinten.",
# 50
"Die Zehen des anderen Fußes berühren den Boden.","Hinterer Fuß auf dem Stuhl, Oberkörper leicht nach vorn, vorderes Knie über dem Fuß.","Normaler Ausfallschritt rückwärts mit Stütze.","Kleine Hocke — niedriger Sprung — weich direkt wieder in die Hocke landen.","Kniebeuge und Wadenheben.","Schulterblätter auf der Sitzfläche, Hantel auf der Hüfte; ausatmen und Beckenboden anheben — Hüfte hoch bis zur geraden Linie, 1 s halten.","Brücke am Boden mit Hantel.","Weiter Schritt zur Seite, Hüfte nach hinten, das andere Bein gestreckt; zurückdrücken.","Kleinerer Schritt, ohne Hantel.","Breiter Stand; Gewicht auf ein Bein verlagern und dieses Knie beugen; das andere Bein bleibt gestreckt.",
# 60
"Langsame Schulterkreise vor und zurück, Nacken locker.","Hände auf den Oberschenkeln; beim Ausatmen den Rücken runden, beim Einatmen die Brust öffnen.","Rücken und Ellbogen an der Wand; Arme langsam auf und ab gleiten lassen, ohne die Wand zu verlassen.","Arme weniger hoch heben.","Hände in Schulterhöhe an der Wand, Körper gerade; beim Einatmen zur Wand, beim Ausatmen wegdrücken.","Näher an die Wand stellen.","Hand und Knie auf dem Stuhl, Rücken gerade; die Hantel mit dem Ellbogen am Körper entlang zur Taille ziehen.","Auf dem Stuhl sitzend beide Hanteln zur Taille ziehen.","Rücken gerade, Bauch leicht angespannt; beim Ausatmen die Hanteln von den Schultern nach oben drücken.","Nach vorn bis Gesichtshöhe drücken.",
# 70
"Hanteln in den hängenden Händen, Schultern zurück und unten, gleichmäßige Schritte durch den Raum.","Leichteres Gewicht oder mit den Hanteln auf der Stelle stehen.","In Bauchlage, Stirn auf der Matte; beim Ausatmen gegenüberliegenden Arm und Bein einige Zentimeter heben, Nacken lang.","Nur die Arme abwechselnd heben.","Unterarm am Türrahmen, sanft nach vorn treten, bis die Brust dehnt.","Den gestreckten Arm mit der anderen Hand an die Brust ziehen, Schulter unten.","Schulterkreise, dann Kreise mit gestreckten Armen — langsam, in beide Richtungen.","Im Vierfüßlerstand: beim Ausatmen den Rücken runden, beim Einatmen sanft durchhängen; der Kopf folgt dem Rücken.","Hände auf Sitz oder Lehne eines stabilen Stuhls, Körper gerade; langsam absenken und hochdrücken.","Liegestütze an der Wand.",
# 80
"Hände etwas breiter als die Schultern, Körper von Knien bis Kopf gerade.","Am Stuhl oder an der Wand.","Vorbeugen mit geradem Rücken, Knie locker; Hanteln zur Taille ziehen, Schulterblätter zusammen.","Einarmig mit Stütze am Stuhl.","Bauch und Gesäß leicht angespannt, kein Hohlkreuz; beim Ausatmen die Hanteln von den Schultern nach oben drücken.","Im Sitzen, bis Gesichtshöhe.","Vorbeugen mit geradem Rücken, Arme leicht gebeugt; leichte Hanteln seitlich bis Schulterhöhe heben.","Ohne Gewicht.","In Rückenlage, Knie gebeugt; beim Ausatmen die Hanteln von der Brust hochdrücken, Ellbogen berühren den Boden.","Leichteres Gewicht oder einarmig.",
# 90
"Hand hinter dem Kopf; mit der anderen Hand sanft am Ellbogen ziehen.","Körper gerade, in 3 Zählzeiten langsam absenken, beim Ausatmen hoch.","Auf den Knien.","Hand und Knie auf dem Stuhl, Rücken gerade; Hantel zur Taille, schwereres Gewicht.","Leichteres Gewicht.","Hantel einarmig von der Schulter nach oben drücken; der Oberkörper neigt sich nicht.","Beidarmig im Sitzen, bis Gesichtshöhe.","Ellbogen leicht gebeugt; Hanteln seitlich bis Schulterhöhe heben, nicht höher.","Leichtes oder kein Gewicht.","Von der Brust drücken, dann mit gestreckten Armen die Hantel hinter den Kopf führen und zurück.",
# 100
"Nur drücken.","Hoher Stütz, Füße weiter auseinander; abwechselnd eine Schulter antippen, Hüfte ruhig.","Auf den Knien oder Unterarmstütz ohne Antippen.","Schulterkreise, dann Hüftkreise, langsam, in beide Richtungen.","Hantel an der Brust; Füße etwas breiter als schulterbreit, Hüfte nach hinten, Stuhl berühren, beim Ausatmen aufstehen.","Ohne Hantel, mit Hilfe der Hände.","Handfläche hinter Ihnen an der Wand; den Oberkörper langsam von der Wand wegdrehen, bis die Brust dehnt.","Schulter-, Hüft-, dann Kniekreise — langsam, in beide Richtungen.","Weiche, niedrige Sprünge auf der Stelle, dann seitlich; Knie locker.","Weiches Federn auf den Zehenballen, Knie locker.",
# 110
"Wadenheben.","Aus der Hocke mit Hanteln an den Schultern aufstehen und in einer Bewegung nach oben drücken.","Kniebeuge mit Hanteln an den Schultern, ohne Drücken.","Hände etwas breiter als die Schultern, Körper gerade; beim Einatmen runter, beim Ausatmen hoch.","Hantel in einer Hand; der Oberkörper neigt sich nicht zur Seite; gleichmäßige Schritte.","Zwei leichte Hanteln.","Knie über der Hüfte, unterer Rücken sanft am Boden; beim Ausatmen eine Ferse zum Boden senken.","Füße am Boden, eine Ferse nach vorn gleiten lassen.","Gegenüberliegenden Arm und Bein strecken, Rücken gerade, 2 s halten.","Nur das Bein, die Zehen gleiten über den Boden.",
# 120
"In Seitlage auf Unterarm und Knien; Hüfte heben, Körper gerade.","Im Stand, Unterarm an der Wand.","Vor dem Aufstehen den Beckenboden sanft anheben und beim Ausatmen aufstehen.","Einatmen — Bauch und Rippen weiten sich sanft; langes Ausatmen — Rippen schließen sich, der Beckenboden hebt sich sanft.","In Rückenlage, Knie gebeugt; die Knie sanft zur einen und zur anderen Seite sinken lassen.","Beim Einatmen den Beckenboden gedanklich loslassen, Bauch weich.","Gegenüberliegenden Arm und Bein senken, unterer Rücken sanft am Boden; beim Senken ausatmen.","Nur die Beine.","Ohne Pause.","Auf Unterarmen und Zehen, Körper gerade; den Atem nicht anhalten.",
# 130
"Auf Unterarm und Füßen, Hüfte oben, Körper gerade.","Hantel in einer Hand; nicht zur Hantel neigen; vor dem Anheben der Hantel vom Boden den Beckenboden anspannen.","Knie auf der Matte, das andere Bein vorn; Hüfte sanft nach vorn schieben, bis die Vorderseite des Oberschenkels dehnt.","Ohne Hantel.","Hoher Stütz; ein Knie langsam zur Brust ziehen und zurück, Hüfte ruhig.","Unterarmstütz, 30 s.","Seitstütz: Hüfte senken und wieder heben.","Im Vierfüßlerstand die Knie 3 cm vom Boden heben, Rücken gerade, Atem nicht anhalten.","Knie am Boden, Bird Dog.","Arm gestreckt über der Schulter, Rippen bleiben unten; gleichmäßige Schritte.",
# 140
"Hantel an der Schulter.","An einer Stütze stehend Fuß und Knie in beide Richtungen kreisen.","Am Stuhl festhalten, von der Ferse auf die Zehen abrollen und zurück.","Hand auf der Stuhllehne, auf einem Bein stehen; wenn es leicht ist, ohne Halt.","Neben der Wand: Ferse direkt vor die Zehen des anderen Fußes setzen, Blick nach vorn.","Kürzere Schritte, Hand an der Wand.","Auf einem Bein an einer Stütze, mit den Zehen des anderen Beins vorn, seitlich und hinten den Boden antippen.","Mit beiden Händen festhalten.","Seitschritt mit hochgezogenem Knie, wie über ein Hindernis.","Auf einem Bein mit geradem Rücken vorbeugen, das andere Bein geht nach hinten.",
# 150
"Die Zehen des anderen Fußes berühren den Boden.","Neben einer Stütze: auf Kommando nach vorn, zur Seite oder zurück treten und zurückkehren.","Nur Seitschritte.","Hände an der Wand, ein Bein hinten, Ferse am Boden; Hüfte nach vorn, bis die Wade dehnt.","Im Sitzen den Fuß über einen Ball oder zusammengerollte Socken rollen.","Kopf langsam im Halbkreis von Schulter zu Schulter, dann Schulter- und Armkreise.","Den Kopf nicht in den Nacken legen.","Im Vierfüßlerstand langsame Hüftkreise.","In Seitlage, Knie gebeugt; den oberen Arm nach hinten öffnen, der Blick folgt der Hand.","Beim Ausatmen die Hüfte heben und den Rücken Wirbel für Wirbel ablösen; genauso wieder absenken.",
# 160
"Ferse auf dem Stuhl, Bein gestreckt; mit geradem Rücken sanft vor und zurück wippen.","Im Sitzen: Fußkreise, Abrollen von Ferse zu Zehen, die Zehen „spielen Klavier“.","In Rückenlage, Waden auf der Sitzfläche; ruhige Atmung, unterer Rücken entspannt.","Auf der Stelle marschieren, jede halbe Minute etwas schneller.","Gleichmäßig auf die Stufe und hinunter, ganzer Fuß auf der Stufe.","Hand an der Wand.","15 s schneller, aber mit halber Kraft; dann ruhig marschieren.","Mit einem Sprung Beine auseinander und Arme hoch, zurückspringen; weiche Landung.","Seitschritte mit Armheben.","Laufen auf der Stelle, Knie höher, weiche Landung.",
# 170
"Schnelles Marschieren mit hohen Knien.","Ruhiges Marschieren, der Atem beruhigt sich.","Vorder- und Rückseite des Oberschenkels, Waden und Brust dehnen — je 20–30 s.","Hand an der Wand, niedrigere Stufe.","Ferse auf der Stufe, Bein gestreckt; mit geradem Rücken vorbeugen.","Sprung aus flacher Hocke, dann Sprünge von Seite zu Seite; weiche Landung.","Niedrigere Stufe, ohne Hanteln.","Ferse nach vorn, mit geradem Rücken vorbeugen; dann im Sitzen Knöchel aufs Knie.","Hände an der Tischkante oder auf der Sitzfläche, Körper gerade; Brust zur Kante, beim Ausatmen wegdrücken.","An der Wand.",
# 180
"Füße auf dem Stuhl, Hände am Boden, Körper gerade; in 3 Zählzeiten absenken. Bei hohem Blutdruck vom Boden aus.","Normale Liegestütze.","Bodendrücken mit 1 s Pause unten, beim Ausatmen hoch.","Vorder- und Rückseite des Oberschenkels und Gesäß dehnen — je 20–30 s.","Ausatmen — Beckenboden anheben — Hüfte hoch; beim Senken loslassen.","Auf der Stelle marschieren, allmählich schneller, Schulter- und Hüftkreise, sanfte Kniebeugen.","Zügiges Marschieren, die Arme arbeiten aktiv.","Schritt zur Seite und zurück, die Arme heben sich seitlich nach oben.","Schritt zurück, dann Knie nach vorn und oben; Beinwechsel.","Im Stand mit leichten Schritten in die Luft boxen; Ellbogen locker.",
# 190
"Auf der Stelle marschieren, allmählich langsamer, der Atem beruhigt sich.","Wadendehnung an der Wand und Oberschenkeldehnung — je 20–30 s.","Marschieren mit Steigerung, Step-ups, dann zwei Probe-Steigerungen mit halber Kraft.","Kniebeuge und beim Aufstehen Arme hoch; schnelles Tempo, Knie locker.","Langsamer.","Weiter Schritt zur Seite und zurück, schnell.","Übungen 1–5 noch einmal wiederholen.","Ruhiges Marschieren, tiefe Atmung, dann Waden und Oberschenkel dehnen.","An der Wand stehend die Handfläche nach außen, dann nach innen gegen die Wand drücken — je 10 s, Atem nicht anhalten.","Auf dem Boden sitzend, Beine im 90°-Winkel; die Knie sanft zur anderen Seite bringen.",
# 200
"Rücken an der Wand, in einen angenehmen Winkel absinken und halten; Atem nicht anhalten.","Höher bleiben.","Zehen an der Wand, das Knie geht zur Wand; dann Fußkreise.","In Rückenlage, Knie gebeugt: einatmen — Bauch und Rippen weiten sich, der Beckenboden entspannt; ausatmen — Rippen schließen sich, der Beckenboden hebt sich sanft.","Den Beckenboden wie durch einen Strohhalm nach oben ziehen, 2 s halten, 2 s lösen. Gesäß und Bauch locker lassen.","Den Beckenboden schnell anspannen und sofort lösen.","In Rückenlage, Knie gebeugt; der untere Rücken drückt sanft in den Boden und löst sich.","Beckenboden anheben, 5 s halten, 5 s lösen. Gesäß und Bauch locker lassen.","3 s halten.","Den Beckenboden eine Sekunde vor dem Husten oder Heben der Hantel sanft anspannen.",
# 210
"Aufrecht sitzend: einatmen — Bauch und Rippen weiten sich; lange ausatmen — die Rippen schließen sich.","Durch die Nase 4 Zählzeiten einatmen, 6 ausatmen.","In Rückenlage: einatmen — Bauch und Rippen weiten sich, ausatmen — sie schließen sich sanft.","Als würden Sie den Harnstrahl stoppen: anheben, 3 s halten, 3 s lösen. Gesäß und Bauch locker lassen.","Beckenboden anspannen, dann husten.","Vor dem Anheben der Hantel vom Boden den Beckenboden anspannen.","Hand an der Wand: seitwärts gehen, dann rückwärts, auf den Zehen und auf den Fersen.","Kürzere Schritte, beide Hände nahe der Wand.","In Seitlage, Bein gestreckt, Zehen angezogen; nur wenig heben, die Hüfte kippt nicht nach hinten.","In Seitlage, Knie gebeugt, Füße zusammen; oberes Knie öffnen, Hüfte bleibt ruhig.",
# 220
"In Rückenlage, Knie über der Hüfte; kleine Kreise in beide Richtungen, unterer Rücken ruhig.","Kopf auf der Matte, Knie gebeugt; gestreckte Arme federn nahe am Boden: 5 Zählzeiten ein-, 5 ausatmen.","Kopf auf der Matte; ein Knie zur Brust, das andere Bein diagonal strecken; beim Ausatmen wechseln.","In Bauchlage auf den Unterarmen; die Brust nur wenig heben, Blick zum Boden.","Im Sitzen, Arm über den Kopf, zur Seite neigen ohne zu drehen.","Knie auseinander, Gesäß zu den Fersen, Arme nach vorn, in den Rücken atmen.","Kissen unter das Gesäß.","Im Stand, Füße unter der Hüfte, der Scheitel strebt nach oben; ruhig durch die Nase atmen.","Knie locker, das Gewicht fließt langsam von Bein zu Bein, die Arme schweben mit.","Schritt zur Seite; eine Handfläche steigt auf Schulterhöhe, die andere sinkt zur Hüfte; Wechsel.",
# 230
"Die Handflächen beschreiben abwechselnd einen Kreis vor Gesicht und Bauch, mit Seitschritt.","Fuß am Unterschenkel, nicht am Knie; Hand an einer Stütze.","Zehen am Boden, Ferse am Knöchel.","Breiter Stand, vorderes Knie über dem Fuß, Arme zur Seite.","Schmalerer Stand, Knie weniger gebeugt.","Hüfte nach hinten wie beim Hinsetzen, Arme hoch neben den Ohren.","Hände auf den Oberschenkeln.","In Bauchlage, Unterarme unter den Schultern, Schultern nach unten.","In Rückenlage, Arme leicht seitlich, Aufmerksamkeit auf dem Ausatmen.",
]
