HUK = [
# 0
"Крокуйте на місці у зручному темпі, руки вільно гойдаються вперед-назад.","Ноги на ширині плечей, коліна м’які; повільні кола тазом в один і другий бік.","Коліна трохи зігнуті, таз іде назад, спина рівна, руки ковзають по стегнах до колін; вгору — стиснути сідниці.","Лежачи на спині, стопи на ширині таза; на видиху підняти таз, на вдиху опустити.","Піднімати таз невисоко.","Стілець позаду; таз назад, присісти наполовину й встати на видиху.","Триматися руками за стегна.","Стопи на ширині плечей, таз назад, коліна дивляться туди ж, куди носки; торкнутися стільця — встати на видиху.","Сісти на стілець повністю й встати, допомагаючи руками; при болю в коліні — лише до комфортної глибини.","Коліна трохи зігнуті, спина рівна, гантелі ковзають уздовж стегон до середини гомілки; вгору — стиснути сідниці, видих.",
# 10
"Без ваги, руки до колін; при болю в спині — менша амплітуда.","Рука на спинці стільця, крок назад, опуститися; коліно передньої ноги над стопою; відштовхнутися передньою ногою.","Маленький крок назад і неглибоко.","Тримаючись за стілець, піднятися на носки й м’яко опуститися на п’яти — легкий удар корисний для кістки.","Опускатися повільно, без удару.","Лежачи, стопи на ширині таза; видих і підтягнути тазове дно — таз угору, пауза 1 с, на вдиху вниз.","Сидячи рівно, вдих носом, видих довший за вдих — плечі опускаються.","Рука на стільці, візьміть стопу рукою й підтягніть п’яту до сідниці; коліна поруч, таз не прогинається.","Підтягніть стопу ременем або рушником.","П’ята на стільці або попереду на підлозі, нога пряма; нахил уперед із рівною спиною до легкого натягу.",
# 20
"Долоні на колінах, м’які кола колінами й тазом в обидва боки.","Рука на стільці, невеликий крок назад, опуститися невисоко й повернутися.","Лежачи, видих і підтягнути тазове дно — таз угору, на вдиху вниз.","Стопи на ширині плечей, таз назад, коліна по лінії носків, спина рівна; вгору на видиху.","Присідання до стільця.","Гантель біля грудей, таз назад, коліна по лінії носків, спина рівна; вгору на видиху.","Присідання до стільця; при болю в коліні — глибина за комфортом.","Спина рівна, гантелі вздовж стегон до середини гомілки; вгору — стиснути сідниці. Спину з вагою не округлюємо.","До колін, вага легша.","Крок назад, опуститися; коліно передньої ноги над стопою; відштовхнутися передньою ногою.",
# 30
"З рукою на спинці стільця, неглибоко.","Невисоко, м’яке приземлення на передню частину стопи, коліна злегка зігнуті.","Підйом на носки з м’яким опусканням на п’яти.","Друга нога зігнута в повітрі; видих і підтягнути тазове дно — таз угору.","Міст на двох ногах.","Уся стопа на сходинці, поштовх п’ятою, вниз повільно.","Без гантелей, тримаючись за стіну.","Вдих носом, видих довший за вдих — тіло розслабляється.","Сидячи на стільці, стопу на протилежне коліно; нахил уперед із рівною спиною.","Крок на місці, коліна вище звичайного, руки працюють.",
# 40
"М’які кола тазом, потім колінами, потім стопами — в обидва боки.","Крок назад у випад і водночас руки вгору; повернутися, руки вниз.","Без рук, з опорою на стілець.","Таз угору, пауза 2–3 с угорі, сідниці стиснуті, ребра не розкриваються.","Пауза коротша.","Присідання і наприкінці — кілька м’яких підстрибувань на місці.","Без підстрибувань.","Гантелі біля плечей або вздовж тіла; вниз повільно на 3 рахунки, вгору впевнено на видиху.","Одна гантель біля грудей, звичайний темп.","Рука на стільці, гантель в іншій руці; спина й таз рівно, вільна нога йде назад.",
# 50
"Пальці другої ноги торкаються підлоги.","Задня нога на стільці, корпус трохи вперед, коліно передньої ноги над стопою.","Звичайний випад назад з опорою.","Невелике присідання — стрибок невисоко — м’яке приземлення одразу в присід.","Присідання й підйом на носки.","Лопатки на сидінні стільця, гантель на тазі; видих і тазове дно — таз угору до прямої лінії, пауза 1 с.","Міст на підлозі з гантеллю.","Широкий крок убік, таз назад, друга нога пряма; відштовхнутися назад.","Менший крок, без гантелі.","Широка стійка, переносьте вагу на одну ногу, згинаючи її коліно; друга нога пряма.",
# 60
"Повільні кола плечима вперед і назад, шия розслаблена.","Руки на стегнах; на видиху округлити спину, на вдиху розкрити груди.","Спина й лікті біля стіни; повільно ковзати руками вгору й униз, не відриваючи від стіни.","Піднімати руки нижче.","Долоні на стіні на рівні плечей, тіло пряме; до стіни на вдиху, від стіни на видиху.","Стати ближче до стіни.","Рука й коліно на стільці, спина рівна; тягнути гантель ліктем уздовж тіла до пояса.","Сидячи на стільці, тягнути обидві гантелі до пояса.","Спина пряма, прес м’яко підтягнутий; гантелі від плечей угору на видиху.","Жим уперед до рівня обличчя.",
# 70
"Гантелі в опущених руках, плечі назад і вниз, рівні кроки кімнатою.","Легша вага або стояти на місці з гантелями.","Лежачи на животі, лоб на килимку; на видиху підняти протилежні руку й ногу на кілька сантиметрів, шия довга.","Піднімати лише руки по черзі.","Передпліччя на дверній рамі, м’який крок уперед до натягу в грудях.","Пряму руку притиснути до грудей іншою рукою, плече вниз.","Кола плечима, потім прямими руками — повільно, в обидва боки.","На чотирьох: на видиху округлити спину, на вдиху м’яко прогнутися, голова йде за спиною.","Долоні на сидінні або спинці стійкого стільця, тіло пряме; повільно опуститися й відштовхнутися.","Віджимання від стіни.",
# 80
"Руки трохи ширше плечей, тіло від колін до голови пряме.","Від стільця або стіни.","Нахил із прямою спиною, коліна м’які; гантелі до пояса, звести лопатки.","Однією рукою з опорою на стілець.","Прес і сідниці м’яко підтягнуті, без прогину в попереку; гантелі від плечей угору на видиху.","Сидячи, до рівня обличчя.","Нахил із прямою спиною, руки трохи зігнуті, легкі гантелі розвести в сторони до рівня плечей.","Без ваги.","Лежачи, коліна зігнуті; гантелі від грудей угору на видиху, лікті торкаються підлоги.","Вага легша або по одній руці.",
# 90
"Рука за головою, іншою рукою м’яко потягнути лікоть.","Тіло пряме, опускатися повільно на 3 рахунки, вгору на видиху.","З колін.","Рука й коліно на стільці, спина рівна; гантель до пояса, вага важча.","Вага легша.","Гантель від плеча вгору однією рукою, корпус не нахиляється.","Двома руками сидячи, до рівня обличчя.","Лікті трохи зігнуті, піднімати гантелі в сторони до рівня плечей, не вище.","Легка вага або без ваги.","Жим від грудей, потім прямими руками відвести гантель за голову й повернути.",
# 100
"Лише жим.","Планка на прямих руках, ноги ширше; по черзі торкнутися плеча, таз рівно.","З колін або планка на передпліччях без торкань.","Кола плечима, потім тазом, повільно, в обидва боки.","Гантель біля грудей; стопи трохи ширше плечей, таз назад, торкнутися стільця — встати на видиху.","Без гантелі, допомагаючи руками.","Долоня на стіні позаду, повільно повернути корпус від стіни до натягу в грудях.","Кола плечима, тазом, потім колінами — повільно, в обидва боки.","М’які невисокі стрибки на місці, потім з боку в бік; коліна м’які.","М’які підстрибування на носках, коліна розслаблені.",
# 110
"Підйоми на носки.","З присіду з гантелями біля плечей встати й вижати вгору одним рухом.","Присід із гантелями біля плечей без жиму.","Руки трохи ширше плечей, тіло пряме; вниз на вдиху, вгору на видиху.","Гантель в одній руці, корпус не нахиляється вбік; рівні кроки.","Дві легкі гантелі.","Коліна над тазом, поперек м’яко притиснутий; на видиху опустити одну п’яту до підлоги.","Стопи на підлозі, ковзати п’ятою вперед.","Витягнути протилежні руку й ногу, спина рівна, пауза 2 с.","Лише ногу, носок ковзає підлогою.",
# 120
"Лежачи на боці, опора на передпліччя й коліна; підняти таз, тіло пряме.","Стоячи, упор передпліччям у стіну.","Перед тим як встати — м’яко підтягнути тазове дно й встати на видиху.","Вдих — живіт і ребра м’яко розширюються; довгий видих — ребра сходяться, тазове дно м’яко піднімається.","Лежачи, коліна зігнуті; м’яко опускати коліна в один і другий бік.","На вдиху подумки відпустити тазове дно, живіт м’який.","Протилежні рука й нога опускаються, поперек м’яко притиснутий; видих на опусканні.","Лише ноги.","Без паузи.","Опора на передпліччя й носки, тіло пряме; дихання не затримувати.",
# 130
"Опора на передпліччя й стопи, таз піднятий, тіло пряме.","Гантель в одній руці, корпус не нахиляється до гантелі; тазове дно підтягнути перед підйомом гантелі з підлоги.","Коліно на килимку, друга нога попереду; м’яко подати таз уперед до натягу спереду стегна.","Без гантелі.","Планка на прямих руках, повільно підтягнути коліно до грудей і повернути, таз рівно.","Планка на передпліччях 30 с.","Бічна планка: опустити таз і підняти назад.","На чотирьох підняти коліна над підлогою на 3 см, спина рівна, дихання не затримувати.","Коліна на підлозі, «пташка-собака».","Рука пряма над плечем, ребра не розкриваються; рівні кроки.",
# 140
"Гантель біля плеча.","Стоячи біля опори, кола стопою й коліном в обидва боки.","Тримаючись за стілець, перекотитися з п’яти на носок і назад.","Рука на спинці стільця, стояти на одній нозі; якщо легко — без опори.","Біля стіни: ставити п’яту впритул до носка іншої ноги, погляд уперед.","Крок коротший, рука на стіні.","Стоячи на одній нозі біля опори, носком іншої торкатися підлоги попереду, збоку й позаду.","Триматися обома руками.","Крок убік, високо піднімаючи коліно, ніби через перешкоду.","Стоячи на одній нозі, нахил із прямою спиною, друга нога йде назад.",
# 150
"Носок другої ноги торкається підлоги.","Біля опори: за командою ступити вперед, убік або назад і повернутися.","Лише кроки вбік.","Руки на стіні, одна нога назад, п’ята на підлозі; подати таз уперед до натягу в литці.","Сидячи, катати стопу по м’ячу або згорнутих шкарпетках.","Голова повільно півколом від плеча до плеча, потім кола плечима й руками.","Голову назад не закидати.","На чотирьох повільні кола тазом.","Лежачи на боці, коліна зігнуті; верхня рука розкривається назад, погляд за рукою.","На видиху піднімати таз, відриваючи спину хребець за хребцем; опускати так само.",
# 160
"П’ята на стільці, нога пряма; м’яко погойдуватися вперед-назад із рівною спиною.","Сидячи: кола стопами, перекати з п’яти на носок, пальці по черзі «грають на піаніно».","Лежачи на спині, литки на сидінні стільця; спокійне дихання, поперек розслаблений.","Крок на місці, кожні пів хвилини трохи швидше.","Підніматися на сходинку й спускатися в рівному темпі, уся стопа на сходинці.","Триматися за стіну.","15 с швидше, але в пів сили; потім спокійний крок.","Стрибком ноги нарізно й руки вгору, стрибком назад; м’яке приземлення.","Кроки вбік із підйомом рук.","Біг на місці, коліна вище, приземлення м’яке.",
# 170
"Швидкий крок із високим коліном.","Спокійний крок на місці, дихання вирівнюється.","Розтяжка передньої й задньої поверхні стегна, литки й грудей — по 20–30 с.","Триматися за стіну, сходинка нижча.","П’ята на сходинці, нога пряма; нахил уперед із рівною спиною.","Стрибок із неглибокого присіду, потім стрибки з боку в бік; м’яке приземлення.","Сходинка нижча, без гантелей.","П’ята вперед, нахил із рівною спиною; потім стопа на коліно сидячи.","Долоні на краю столу або сидінні стільця, тіло пряме; груди до краю, від опори на видиху.","Від стіни.",
# 180
"Стопи на стільці, руки на підлозі, тіло пряме; опускатися на 3 рахунки. При високому тиску — з підлоги.","Звичайні віджимання.","Жим лежачи, внизу пауза 1 с, вгору на видиху.","Розтяжка передньої й задньої поверхні стегна та сідниць — по 20–30 с.","Видих — підтягнути тазове дно — таз угору; вниз — відпустити.","Крок на місці, поступово швидше, кола плечима й тазом, м’які присідання.","Швидкий крок на місці, руки активно працюють.","Крок убік і назад, руки піднімаються через сторони вгору.","Крок назад, потім коліно вперед і вгору; зміна ніг.","Стоячи, удари руками в повітря вперед, з легкими кроками; лікті м’які.",
# 190
"Крок на місці, поступово повільніше, дихання вирівнюється.","Розтяжка литок біля стіни й стегон — по 20–30 с.","Крок на місці з прискоренням, підйоми на сходинку, потім два пробні прискорення в пів сили.","Присід і, встаючи, руки вгору; швидкий темп, м’які коліна.","Повільніше.","Широкий крок убік і назад, швидко.","Повторити вправи 1–5 ще раз.","Спокійний крок, глибоке дихання, потім розтяжка литок і стегон.","Стоячи біля стіни, долоня тисне в стіну назовні, потім усередину — по 10 с, дихання не затримувати.","Сидячи на підлозі, ноги зігнуті під 90°; м’яко переводити коліна в інший бік.",
# 200
"Спина біля стіни, присісти до комфортного кута й тримати; дихання не затримувати.","Присід вищий.","Носок біля стіни, коліно тягнеться до стіни; потім кола стопою.","Лежачи, коліна зігнуті: вдих — живіт і ребра м’яко розширюються, тазове дно розслабляється; видих — ребра сходяться, тазове дно м’яко піднімається.","Підтягнути тазове дно вгору, ніби через трубочку, тримати 2 с, розслабити 2 с. Сідниці й прес не напружувати.","Швидко підтягнути тазове дно й одразу відпустити.","Лежачи, коліна зігнуті; поперек м’яко притискається до підлоги й відпускається.","Підтягнути тазове дно, тримати 5 с, розслабити 5 с. Сідниці й прес не напружувати.","Тримати 3 с.","М’яко підтягнути тазове дно за секунду до кашлю або підйому гантелі.",
# 210
"Сидячи рівно: вдих — живіт і ребра розширюються; довгий видих — ребра сходяться.","Вдих носом на 4 рахунки, видих на 6.","Лежачи: вдих — живіт і ребра розширюються, видих — м’яко сходяться.","Ніби стримуєте струмінь: підтягнути, тримати 3 с, відпустити 3 с. Сідниці й прес не напружувати.","Підтягнути тазове дно, потім кашлянути.","Підтягнути тазове дно перед тим, як підняти гантель із підлоги.","Рука на стіні: йти боком, потім спиною вперед, на носках і на п’ятах.","Коротші кроки, обидві руки біля стіни.","Лежачи на боці, нога пряма, носок на себе; піднімати невисоко, таз не завалюється назад.","Лежачи на боці, коліна зігнуті, стопи разом; відкривати верхнє коліно, таз нерухомий.",
# 220
"Лежачи, коліно над тазом; маленькі кола в обидва боки, поперек спокійний.","Голова на килимку, коліна зігнуті; прямі руки пружинять біля підлоги: 5 рахунків вдих, 5 видих.","Голова на килимку; одне коліно до грудей, інша нога витягується по діагоналі; зміна ніг на видиху.","Лежачи на животі, опора на передпліччя; груди піднімаються невисоко, погляд у підлогу.","Сидячи, рука над головою, нахил убік без повороту.","Коліна нарізно, таз до п’ят, руки вперед, дихання в спину.","Подушка під таз.","Стоячи, стопи під тазом, маківка тягнеться вгору; спокійний вдих носом.","Коліна м’які, вага повільно перетікає з ноги на ногу, руки пливуть слідом.","Крок убік, одна долоня піднімається до рівня плеча, інша опускається до стегна; зміна.",
# 230
"Долоні по черзі описують коло перед обличчям і животом, приставний крок убік.","Стопа на гомілці, не на коліні; рука на опорі.","Носок на підлозі, п’ята біля щиколотки.","Широка стійка, переднє коліно над стопою, руки в сторони.","Стійка вужча, коліно зігнуте менше.","Таз назад, як при посадці на стілець, руки вгору біля вух.","Руки на стегнах.","Лежачи на животі, передпліччя під плечима, плечі вниз.","Лежачи на спині, руки трохи в сторони, увага на видиху.",
]
HEN = [
# 0
"March in place at a comfortable pace, arms swinging freely back and forth.","Feet shoulder-width, knees soft; slow hip circles one way, then the other.","Knees slightly bent, hips go back, back flat, hands slide down the thighs to the knees; on the way up, squeeze your glutes.","Lying on your back, feet hip-width; lift the hips as you exhale, lower as you inhale.","Lift the hips only a little.","Chair behind you; hips back, squat halfway and stand up as you exhale.","Rest your hands on your thighs.","Feet shoulder-width, hips back, knees point the same way as your toes; touch the chair, then stand up as you exhale.","Sit all the way down and stand up using your hands; if a knee hurts, go only as deep as is comfortable.","Knees slightly bent, back flat, dumbbells slide along the thighs to mid-shin; on the way up, squeeze your glutes and exhale.",
# 10
"No weight, hands to the knees; if your back hurts, use a smaller range.","Hand on the chair back, step back and lower down; front knee over the foot; push back up with the front leg.","A small step back, not too deep.","Holding the chair, rise onto your toes and drop softly onto your heels — the light impact is good for bone.","Lower slowly, without impact.","Lying down, feet hip-width; exhale and lift the pelvic floor — hips up, pause 1 s, lower as you inhale.","Sit tall, breathe in through the nose, breathe out longer than in — let the shoulders drop.","Hand on the chair, hold your foot and draw the heel toward your buttock; knees together, no arch in the lower back.","Pull the foot with a strap or towel.","Heel on a chair or on the floor in front, leg straight; lean forward with a flat back until you feel a light stretch.",
# 20
"Hands on knees, gentle circles with the knees and hips both ways.","Hand on the chair, small step back, lower a little and come back.","Lying down, exhale and lift the pelvic floor — hips up, lower as you inhale.","Feet shoulder-width, hips back, knees in line with toes, back flat; stand up as you exhale.","Squat to a chair.","Dumbbell at the chest, hips back, knees in line with toes, back flat; stand up as you exhale.","Squat to a chair; if a knee hurts, go only as deep as is comfortable.","Back flat, dumbbells along the thighs to mid-shin; on the way up, squeeze your glutes. Never round your back with weight.","Only to the knees, lighter weight.","Step back and lower down; front knee over the foot; push back up with the front leg.",
# 30
"With a hand on the chair back, not too deep.","Low hops, soft landing on the balls of the feet, knees slightly bent.","Calf raises with a soft drop onto the heels.","Other leg bent in the air; exhale and lift the pelvic floor — hips up.","Bridge on both feet.","Whole foot on the step, push through the heel, lower slowly.","No dumbbells, hand on the wall.","Breathe in through the nose, breathe out longer than in — the body relaxes.","Sitting on a chair, ankle on the opposite knee; lean forward with a flat back.","March in place, knees higher than usual, arms working.",
# 40
"Gentle circles with the hips, then knees, then ankles — both ways.","Step back into a lunge while raising your arms; come back, arms down.","No arm raise, hand on the chair.","Hips up, pause 2–3 s at the top, glutes squeezed, ribs stay down.","Shorter pause.","Squat, then finish with a few soft bounces in place.","No bounces.","Dumbbells at the shoulders or by your sides; lower slowly for a count of 3, stand up firmly as you exhale.","One dumbbell at the chest, normal pace.","Hand on the chair, dumbbell in the other hand; back and hips level, the free leg reaches back.",
# 50
"Toes of the other foot touch the floor.","Back foot on the chair, torso slightly forward, front knee over the foot.","Regular supported reverse lunge.","Small squat — low jump — soft landing straight back into the squat.","Squat and calf raise.","Shoulder blades on the chair seat, dumbbell on the hips; exhale and lift the pelvic floor — hips up into a straight line, pause 1 s.","Floor bridge with a dumbbell.","Wide step to the side, hips back, other leg straight; push back to the start.","Shorter step, no dumbbell.","Wide stance; shift your weight onto one leg, bending that knee; the other leg stays straight.",
# 60
"Slow shoulder circles forward and back, neck relaxed.","Hands on thighs; round your back as you exhale, open your chest as you inhale.","Back and elbows against the wall; slowly slide your arms up and down without leaving the wall.","Don’t raise the arms as high.","Palms on the wall at shoulder height, body straight; toward the wall as you inhale, push away as you exhale.","Stand closer to the wall.","Hand and knee on the chair, back flat; pull the dumbbell with your elbow along your side to the waist.","Sitting on a chair, pull both dumbbells to the waist.","Back straight, abs gently drawn in; press the dumbbells up from the shoulders as you exhale.","Press forward to face height.",
# 70
"Dumbbells in lowered hands, shoulders back and down, even steps around the room.","Lighter weight, or stand in place holding the dumbbells.","Lying face down, forehead on the mat; as you exhale, lift the opposite arm and leg a few centimetres, neck long.","Lift only the arms, one at a time.","Forearm on the door frame, step gently forward until you feel a stretch in the chest.","Hold a straight arm across your chest with the other hand, shoulder down.","Circle the shoulders, then straight arms — slowly, both ways.","On all fours: round your back as you exhale, gently arch as you inhale; the head follows the spine.","Hands on the seat or back of a sturdy chair, body straight; lower slowly and press up.","Wall push-ups.",
# 80
"Hands slightly wider than shoulders, body straight from knees to head.","Against a chair or wall.","Hinge with a flat back, knees soft; pull the dumbbells to your waist, squeeze the shoulder blades.","One arm at a time, supported on a chair.","Abs and glutes gently engaged, no arch in the lower back; press the dumbbells up from the shoulders as you exhale.","Seated, to face height.","Hinge with a flat back, arms slightly bent; raise light dumbbells out to the sides to shoulder height.","No weight.","Lying down, knees bent; press the dumbbells up from the chest as you exhale, elbows touch the floor.","Lighter weight or one arm at a time.",
# 90
"Hand behind your head; gently pull the elbow with the other hand.","Body straight, lower slowly for a count of 3, push up as you exhale.","From the knees.","Hand and knee on the chair, back flat; dumbbell to the waist, heavier weight.","Lighter weight.","Press the dumbbell up from the shoulder with one arm; the torso doesn’t lean.","Both arms, seated, to face height.","Elbows slightly bent; raise the dumbbells out to the sides to shoulder height, no higher.","Light weight or no weight.","Press from the chest, then with straight arms take the dumbbell behind your head and back.",
# 100
"Press only.","High plank, feet wider; tap each shoulder in turn, hips level.","From the knees, or a forearm plank without taps.","Circle the shoulders, then the hips, slowly, both ways.","Dumbbell at the chest; feet slightly wider than shoulders, hips back, touch the chair, stand up as you exhale.","No dumbbell, help with your hands.","Palm on the wall behind you; slowly turn your body away from the wall until you feel a stretch in the chest.","Circle the shoulders, hips, then knees — slowly, both ways.","Soft low hops in place, then side to side; knees soft.","Soft bounces on the balls of the feet, knees relaxed.",
# 110
"Calf raises.","From a squat with dumbbells at the shoulders, stand and press overhead in one movement.","Squat with dumbbells at the shoulders, no press.","Hands slightly wider than shoulders, body straight; down as you inhale, up as you exhale.","Dumbbell in one hand; the torso doesn’t lean to the side; even steps.","Two light dumbbells.","Knees over hips, lower back gently pressed down; as you exhale, lower one heel to the floor.","Feet on the floor, slide one heel forward.","Reach out the opposite arm and leg, back flat, pause 2 s.","Leg only, toes slide along the floor.",
# 120
"Lying on your side, on forearm and knees; lift the hips, body straight.","Standing, forearm against the wall.","Before you stand up, gently lift the pelvic floor and stand as you exhale.","Inhale — belly and ribs gently expand; long exhale — ribs draw in, the pelvic floor gently lifts.","Lying, knees bent; gently lower the knees to one side, then the other.","As you inhale, let the pelvic floor go, belly soft.","Lower the opposite arm and leg, lower back gently pressed down; exhale as you lower.","Legs only.","No pause.","On forearms and toes, body straight; don’t hold your breath.",
# 130
"On forearm and feet, hips lifted, body straight.","Dumbbell in one hand; don’t lean toward it; lift the pelvic floor before picking the dumbbell up from the floor.","Knee on the mat, other foot in front; gently move the hips forward until you feel a stretch at the front of the thigh.","No dumbbell.","High plank; slowly draw one knee to the chest and back, hips level.","Forearm plank, 30 s.","Side plank: lower the hips and lift them back up.","On all fours, lift the knees 3 cm off the floor, back flat, don’t hold your breath.","Knees on the floor, bird dog.","Arm straight above the shoulder, ribs stay down; even steps.",
# 140
"Dumbbell at the shoulder.","Standing by a support, circle the ankle and knee both ways.","Holding the chair, roll from heel to toe and back.","Hand on the chair back, stand on one leg; if it’s easy, let go.","Next to a wall: place the heel right against the toes of the other foot, eyes forward.","Shorter steps, hand on the wall.","Standing on one leg by a support, tap the floor with the other toes in front, to the side and behind.","Hold on with both hands.","Step to the side, lifting the knee high as if over an obstacle.","Standing on one leg, hinge with a flat back, the other leg reaches back.",
# 150
"Toes of the other foot touch the floor.","Next to a support: on cue, step forward, to the side or back, and return.","Side steps only.","Hands on the wall, one leg back, heel down; move the hips forward until you feel a calf stretch.","Seated, roll your foot over a ball or rolled-up socks.","Move the head slowly in a half circle from shoulder to shoulder, then circle the shoulders and arms.","Don’t tip the head back.","On all fours, slow hip circles.","Lying on your side, knees bent; open the top arm behind you, eyes follow the hand.","As you exhale, lift the hips, peeling the back up one vertebra at a time; lower the same way.",
# 160
"Heel on a chair, leg straight; gently rock forward and back with a flat back.","Seated: ankle circles, heel-to-toe rolls, toes “play the piano” one by one.","Lying on your back, calves on the chair seat; calm breathing, lower back relaxed.","March in place, a little faster every half minute.","Step up and down at an even pace, whole foot on the step.","Hand on the wall.","15 s faster, but at half effort; then easy marching.","Jump feet apart with arms up, jump back; soft landing.","Side steps with arm raises.","Run in place, knees higher, soft landing.",
# 170
"Fast march with high knees.","Easy march in place, breathing settles.","Stretch the front and back of the thigh, calves and chest — 20–30 s each.","Hand on the wall, lower step.","Heel on the step, leg straight; lean forward with a flat back.","Jump from a shallow squat, then side-to-side hops; soft landing.","Lower step, no dumbbells.","Heel forward, hinge with a flat back; then, seated, ankle on the knee.","Hands on the edge of a table or chair seat, body straight; chest to the edge, push away as you exhale.","Against the wall.",
# 180
"Feet on a chair, hands on the floor, body straight; lower for a count of 3. With high blood pressure — from the floor.","Regular push-ups.","Floor press with a 1 s pause at the bottom, up as you exhale.","Stretch the front and back of the thigh and the glutes — 20–30 s each.","Exhale — lift the pelvic floor — hips up; on the way down, let it go.","March in place, gradually faster, shoulder and hip circles, gentle squats.","Brisk march in place, arms working actively.","Step to the side and back, arms rise out to the sides and up.","Step back, then drive the knee forward and up; switch legs.","Standing, punch forward into the air with light steps; elbows soft.",
# 190
"March in place, gradually slower, breathing settles.","Calf stretch at the wall and thigh stretch — 20–30 s each.","Accelerating march, step-ups, then two practice bursts at half effort.","Squat, and as you stand, arms up; fast pace, soft knees.","Slower.","Wide step to the side and back, fast.","Repeat exercises 1–5 once more.","Easy march, deep breathing, then calf and thigh stretch.","Standing by a wall, press your palm into the wall outward, then inward — 10 s each, don’t hold your breath.","Sitting on the floor, legs bent at 90°; gently move the knees to the other side.",
# 200
"Back against the wall, slide down to a comfortable angle and hold; don’t hold your breath.","Stay higher.","Toes at the wall, knee reaches toward the wall; then ankle circles.","Lying, knees bent: inhale — belly and ribs gently expand, the pelvic floor relaxes; exhale — ribs draw in, the pelvic floor gently lifts.","Lift the pelvic floor as if through a straw, hold 2 s, relax 2 s. Keep the glutes and abs relaxed.","Lift the pelvic floor quickly and let go at once.","Lying, knees bent; the lower back gently presses into the floor and releases.","Lift the pelvic floor, hold 5 s, relax 5 s. Keep the glutes and abs relaxed.","Hold 3 s.","Gently lift the pelvic floor a second before you cough or lift the dumbbell.",
# 210
"Sitting tall: inhale — belly and ribs expand; long exhale — ribs draw in.","Breathe in through the nose for 4 counts, out for 6.","Lying: inhale — belly and ribs expand, exhale — they gently draw in.","As if stopping the flow: lift, hold 3 s, release 3 s. Keep the glutes and abs relaxed.","Lift the pelvic floor, then cough.","Lift the pelvic floor before you pick the dumbbell up from the floor.","Hand on the wall: walk sideways, then backwards, on your toes and on your heels.","Shorter steps, both hands near the wall.","Lying on your side, leg straight, toes pulled up; lift only a little, the hips don’t roll back.","Lying on your side, knees bent, feet together; open the top knee, hips stay still.",
# 220
"Lying down, knee over the hip; small circles both ways, lower back calm.","Head on the mat, knees bent; straight arms pulse near the floor: breathe in for 5 counts, out for 5.","Head on the mat; one knee to the chest, the other leg extends on a diagonal; switch legs as you exhale.","Lying face down, on your forearms; lift the chest a little, eyes on the floor.","Seated, arm over the head, bend to the side without twisting.","Knees apart, hips toward the heels, arms forward, breathe into your back.","Pillow under the hips.","Standing, feet under the hips, crown reaching up; calm breath through the nose.","Knees soft, weight flows slowly from leg to leg, arms float along.","Step to the side; one palm rises to shoulder height, the other lowers to the hip; switch.",
# 230
"The palms take turns drawing a circle in front of the face and belly, with a side step.","Foot on the shin, not on the knee; hand on a support.","Toes on the floor, heel at the ankle.","Wide stance, front knee over the foot, arms out to the sides.","Narrower stance, knee less bent.","Hips back as if sitting on a chair, arms up by your ears.","Hands on your thighs.","Lying face down, forearms under the shoulders, shoulders down.","Lying on your back, arms slightly out, attention on the exhale.",
]
