# 15 дополнительных названий — дыхательные разминки №10/11/12/14, М10/М11/М15 (пропущены при разборе)
X = {
'ru':["Дыхание «канистрой» лёжа, колени согнуты","Медленные сокращения тазового дна: держать 2 с, расслабить 2 с","Быстрые сокращения тазового дна","Наклоны таза лёжа","Дыхание «канистрой» лёжа","Медленные сокращения тазового дна: держать 5 с, расслабить 5 с","«Кошка-корова» на четвереньках с дыханием","Упреждающее сокращение: подтянуть тазовое дно перед кашлем и перед подъёмом гантели","Дыхание «канистрой» сидя на стуле","Вдох на 4 счёта, выдох на 6","Дыхание животом и рёбрами лёжа","Сокращения тазового дна, как будто сдерживаете струю: держать 3 с, отпустить 3 с","Упреждающее сокращение: подтянуть тазовое дно и кашлянуть","Упреждающее сокращение перед подъёмом гантели с пола","Дыхание животом и рёбрами сидя: вдох на 4 счёта, выдох на 6"],
'uk':["Дихання «каністрою» лежачи, коліна зігнуті","Повільні скорочення тазового дна: тримати 2 с, розслабити 2 с","Швидкі скорочення тазового дна","Нахили таза лежачи","Дихання «каністрою» лежачи","Повільні скорочення тазового дна: тримати 5 с, розслабити 5 с","«Кішка-корова» на чотирьох із диханням","Випереджальне скорочення: підтягнути тазове дно перед кашлем і перед підйомом гантелі","Дихання «каністрою» сидячи на стільці","Вдих на 4 рахунки, видих на 6","Дихання животом і ребрами лежачи","Скорочення тазового дна, ніби стримуєте струмінь: тримати 3 с, відпустити 3 с","Випереджальне скорочення: підтягнути тазове дно й кашлянути","Випереджальне скорочення перед підйомом гантелі з підлоги","Дихання животом і ребрами сидячи: вдих на 4 рахунки, видих на 6"],
'en':["“Canister” breathing lying down, knees bent","Slow pelvic-floor squeezes: hold 2 s, relax 2 s","Quick pelvic-floor squeezes","Lying pelvic tilts","“Canister” breathing lying down","Slow pelvic-floor squeezes: hold 5 s, relax 5 s","Cat-cow on all fours with breathing","The “knack”: lift the pelvic floor before a cough and before lifting a dumbbell","“Canister” breathing seated on a chair","Inhale for 4 counts, exhale for 6","Belly and rib breathing lying down","Pelvic-floor squeezes, as if stopping the flow: hold 3 s, release 3 s","The “knack”: lift the pelvic floor, then cough","The “knack” before lifting a dumbbell from the floor","Seated belly and rib breathing: inhale for 4 counts, exhale for 6"],
'es':["Respiración «en bote» tumbado, rodillas dobladas","Contracciones lentas del suelo pélvico: mantener 2 s, relajar 2 s","Contracciones rápidas del suelo pélvico","Basculaciones de pelvis tumbado","Respiración «en bote» tumbado","Contracciones lentas del suelo pélvico: mantener 5 s, relajar 5 s","Gato-vaca a cuatro patas con respiración","Contracción anticipada: elevar el suelo pélvico antes de toser y antes de levantar la mancuerna","Respiración «en bote» sentado en una silla","Inhala en 4 tiempos, exhala en 6","Respiración abdominal y costal tumbado","Contracciones del suelo pélvico, como si cortaras el chorro: mantener 3 s, soltar 3 s","Contracción anticipada: elevar el suelo pélvico y toser","Contracción anticipada antes de levantar la mancuerna del suelo","Respiración abdominal y costal sentado: inhala en 4 tiempos, exhala en 6"],
'de':["„Kanister“-Atmung in Rückenlage, Knie gebeugt","Langsames Beckenbodenanspannen: 2 s halten, 2 s lösen","Schnelles Beckenbodenanspannen","Beckenkippen in Rückenlage","„Kanister“-Atmung in Rückenlage","Langsames Beckenbodenanspannen: 5 s halten, 5 s lösen","Katze-Kuh im Vierfüßlerstand mit Atmung","Vorspannen: Beckenboden vor dem Husten und vor dem Anheben der Kurzhantel anspannen","„Kanister“-Atmung im Sitzen auf dem Stuhl","Einatmen auf 4 Zählzeiten, ausatmen auf 6","Bauch- und Rippenatmung in Rückenlage","Beckenboden anspannen, als ob Sie den Harnstrahl stoppen: 3 s halten, 3 s lösen","Vorspannen: Beckenboden anspannen, dann husten","Vorspannen vor dem Anheben der Kurzhantel vom Boden","Bauch- und Rippenatmung im Sitzen: einatmen auf 4, ausatmen auf 6"],
'pt':["Respiração «em vasilha» deitado, joelhos dobrados","Contrações lentas do assoalho pélvico: segurar 2 s, relaxar 2 s","Contrações rápidas do assoalho pélvico","Inclinações da pelve deitado","Respiração «em vasilha» deitado","Contrações lentas do assoalho pélvico: segurar 5 s, relaxar 5 s","Gato-vaca de quatro apoios com respiração","Contração antecipada: elevar o assoalho pélvico antes de tossir e antes de levantar o halter","Respiração «em vasilha» sentado na cadeira","Inspire em 4 tempos, expire em 6","Respiração abdominal e costal deitado","Contrações do assoalho pélvico, como se segurasse o xixi: segurar 3 s, soltar 3 s","Contração antecipada: elevar o assoalho pélvico e tossir","Contração antecipada antes de levantar o halter do chão","Respiração abdominal e costal sentado: inspire em 4 tempos, expire em 6"],
'fr':["Respiration « en bidon » allongé, genoux pliés","Contractions lentes du périnée : tenir 2 s, relâcher 2 s","Contractions rapides du périnée","Bascules du bassin allongé","Respiration « en bidon » allongé","Contractions lentes du périnée : tenir 5 s, relâcher 5 s","Chat-vache à quatre pattes avec respiration","Verrouillage : contracter le périnée avant de tousser et avant de soulever l’haltère","Respiration « en bidon » assis sur une chaise","Inspirez sur 4 temps, expirez sur 6","Respiration abdominale et costale allongé","Contractions du périnée, comme pour retenir le jet : tenir 3 s, relâcher 3 s","Verrouillage : contracter le périnée puis tousser","Verrouillage avant de soulever l’haltère du sol","Respiration abdominale et costale assis : inspirez sur 4 temps, expirez sur 6"],
'pl':["Oddech „kanister” na leżąco, kolana ugięte","Wolne napięcia dna miednicy: trzymaj 2 s, rozluźnij 2 s","Szybkie napięcia dna miednicy","Pochylenia miednicy na leżąco","Oddech „kanister” na leżąco","Wolne napięcia dna miednicy: trzymaj 5 s, rozluźnij 5 s","„Koci grzbiet” w klęku podpartym z oddechem","Napięcie wyprzedzające: unieś dno miednicy przed kaszlem i przed podniesieniem hantli","Oddech „kanister” siedząc na krześle","Wdech na 4, wydech na 6","Oddech brzuchem i żebrami na leżąco","Napięcia dna miednicy, jakbyś wstrzymywał strumień: trzymaj 3 s, puść 3 s","Napięcie wyprzedzające: unieś dno miednicy i zakaszl","Napięcie wyprzedzające przed podniesieniem hantli z podłogi","Oddech brzuchem i żebrami na siedząco: wdech na 4, wydech na 6"],
'it':["Respirazione «a barattolo» da sdraiati, ginocchia piegate","Contrazioni lente del pavimento pelvico: tenere 2 s, rilasciare 2 s","Contrazioni rapide del pavimento pelvico","Basculamenti del bacino da sdraiati","Respirazione «a barattolo» da sdraiati","Contrazioni lente del pavimento pelvico: tenere 5 s, rilasciare 5 s","Gatto-mucca a quattro zampe con il respiro","Contrazione anticipata: sollevare il pavimento pelvico prima di tossire e prima di sollevare il manubrio","Respirazione «a barattolo» seduti sulla sedia","Inspira in 4 tempi, espira in 6","Respirazione addominale e costale da sdraiati","Contrazioni del pavimento pelvico, come per trattenere il flusso: tenere 3 s, rilasciare 3 s","Contrazione anticipata: sollevare il pavimento pelvico e tossire","Contrazione anticipata prima di sollevare il manubrio da terra","Respirazione addominale e costale da seduti: inspira in 4 tempi, espira in 6"],
'he':["נשימת «קופסה» בשכיבה, ברכיים כפופות","כיווצים איטיים של רצפת האגן: להחזיק 2 שנ׳, להרפות 2 שנ׳","כיווצים מהירים של רצפת האגן","הטיות אגן בשכיבה","נשימת «קופסה» בשכיבה","כיווצים איטיים של רצפת האגן: להחזיק 5 שנ׳, להרפות 5 שנ׳","חתול-פרה בעמידת שש עם נשימה","כיווץ מקדים: להרים את רצפת האגן לפני שיעול ולפני הרמת משקולת","נשימת «קופסה» בישיבה על כיסא","שאיפה ב-4 ספירות, נשיפה ב-6","נשימת בטן וצלעות בשכיבה","כיווצי רצפת האגן, כאילו עוצרים את הזרם: להחזיק 3 שנ׳, לשחרר 3 שנ׳","כיווץ מקדים: להרים את רצפת האגן ולהשתעל","כיווץ מקדים לפני הרמת משקולת מהרצפה","נשימת בטן וצלעות בישיבה: שאיפה ב-4 ספירות, נשיפה ב-6"],
'ja':["仰向けでひざを立てて「缶」呼吸","ゆっくり骨盤底を締める：2秒保持、2秒ゆるめる","素早く骨盤底を締める","仰向けで骨盤を前後に傾ける","仰向けで「缶」呼吸","ゆっくり骨盤底を締める：5秒保持、5秒ゆるめる","呼吸に合わせて四つ這いでキャット＆カウ","先回りの締め：咳の前とダンベルを持ち上げる前に骨盤底を締める","椅子に座って「缶」呼吸","4カウントで吸って6カウントで吐く","仰向けでお腹と肋骨の呼吸","尿を止めるつもりで骨盤底を締める：3秒保持、3秒ゆるめる","先回りの締め：骨盤底を締めてから咳をする","床からダンベルを持ち上げる前に先回りの締め","座ってお腹と肋骨の呼吸：4カウントで吸って6カウントで吐く"],
'ko':["누워서 무릎 세우고 '통' 호흡","천천히 골반저 조이기: 2초 유지, 2초 이완","빠르게 골반저 조이기","누워서 골반 기울이기","누워서 '통' 호흡","천천히 골반저 조이기: 5초 유지, 5초 이완","호흡하며 네발 자세 고양이-소","미리 조이기: 기침 전과 덤벨 들기 전에 골반저 올리기","의자에 앉아 '통' 호흡","4박자 들숨, 6박자 날숨","누워서 배와 갈비뼈 호흡","소변을 참듯이 골반저 조이기: 3초 유지, 3초 풀기","미리 조이기: 골반저를 올리고 기침하기","바닥에서 덤벨 들기 전 미리 조이기","앉아서 배와 갈비뼈 호흡: 4박자 들숨, 6박자 날숨"],
}
# какой тренировке какая разминка: [(индекс доп. названия или 'b31' — «Мост с паузой вверху» из основного списка, доза)]
BR = {
'№10': ('brf',5,[(0,'90 с'),(1,'10 раз'),(2,'10 раз'),(3,'60 с')]),
'№11': ('brf',7,[(4,'90 с'),(5,'8 раз'),(2,'10 раз'),(6,'60 с'),('b31','60 с')]),
'№12': ('brf',7,[(4,'90 с'),(5,'8 раз'),(2,'10 раз'),(6,'60 с'),('b31','60 с'),(7,'8 раз')]),
'№14': ('br',3,[(8,'90 с'),(9,'90 с')]),
'М10': ('brf',6,[(10,'90 с'),(11,'10 раз'),(2,'10 раз'),(12,'5 раз'),(3,'60 с')]),
'М11': ('brf',5,[(10,'90 с'),(5,'10 раз'),(2,'10 раз'),(13,'5 раз'),(3,'60 с')]),
'М15': ('br',3,[(14,'3 мин')]),
}
