# Этап 2: подписи к технике и «Осторожно» по кодам каталога v2 (×12)
EASY = row('Легче','Легше','Easier','Más fácil','Leichter','Mais fácil','Plus facile','Łatwiej','Più facile','קל יותר','やさしく','쉽게')
CAUT = {
'O': row('при остеопорозе — без прыжков и рывков, амплитуда по комфорту','при остеопорозі — без стрибків і ривків, амплітуда за комфортом','with osteoporosis — no jumping or jerky moves, comfortable range','con osteoporosis — sin saltos ni tirones, recorrido cómodo','bei Osteoporose — ohne Springen und Rucken, angenehmer Bewegungsumfang','com osteoporose — sem saltos nem trancos, amplitude confortável','en cas d’ostéoporose — sans sauts ni à-coups, amplitude confortable','przy osteoporozie — bez skoków i szarpnięć, zakres wygodny','con osteoporosi — niente salti né strappi, movimento comodo','באוסטאופורוזיס — בלי קפיצות ותנועות חדות, טווח נוח','骨粗鬆症の場合はジャンプや急な動きをせず、楽な範囲で','골다공증이 있으면 점프와 급한 동작 없이, 편한 범위로'),
'D': row('при высоком давлении — не задерживать дыхание, без максимального усилия','при високому тиску — не затримувати дихання, без максимального зусилля','with high blood pressure — don’t hold your breath, no maximal effort','con la presión alta — no contengas la respiración, sin esfuerzo máximo','bei hohem Blutdruck — Atem nicht anhalten, keine Maximalkraft','com pressão alta — não prenda a respiração, sem esforço máximo','en cas de tension élevée — ne bloquez pas la respiration, pas d’effort maximal','przy wysokim ciśnieniu — nie wstrzymuj oddechu, bez maksymalnego wysiłku','con la pressione alta — non trattenere il respiro, niente sforzo massimo','בלחץ דם גבוה — לא לעצור נשימה, בלי מאמץ מרבי','血圧が高い場合は息を止めず、全力は出さない','혈압이 높으면 숨을 참지 말고 최대 힘은 쓰지 않기'),
'TD': row('при подтекании или тяжести внизу — вариант «легче»','при підтіканні або важкості внизу — варіант «легше»','with leaking or heaviness below — use the easier option','con escapes o pesadez abajo — la opción más fácil','bei Harnverlust oder Druckgefühl unten — die leichtere Variante','com escape de urina ou peso embaixo — a opção mais fácil','en cas de fuites ou de lourdeur en bas — la variante plus facile','przy popuszczaniu lub uczuciu ciężaru na dole — wariant łatwiejszy','con perdite o pesantezza in basso — la versione più facile','בדליפה או תחושת כובד למטה — הגרסה הקלה','尿もれや下腹部の重さがあるときは、やさしいバージョンで','요실금이나 아래 묵직함이 있으면 쉬운 버전으로'),
'K': row('колени — глубина по комфорту, без боли','коліна — глибина за комфортом, без болю','knees — comfortable depth, no pain','rodillas — profundidad cómoda, sin dolor','Knie — angenehme Tiefe, ohne Schmerz','joelhos — profundidade confortável, sem dor','genoux — profondeur confortable, sans douleur','kolana — głębokość wygodna, bez bólu','ginocchia — profondità comoda, senza dolore','ברכיים — עומק נוח, בלי כאב','ひざは痛みのない楽な深さで','무릎은 통증 없는 편한 깊이로'),
'S': row('спина — меньше амплитуда, без прогиба и округления','спина — менша амплітуда, без прогину й округлення','back — smaller range, no arching or rounding','espalda — menos recorrido, sin arquear ni redondear','Rücken — kleinerer Umfang, kein Hohlkreuz, nicht runden','costas — amplitude menor, sem arquear nem arredondar','dos — amplitude réduite, sans cambrer ni arrondir','plecy — mniejszy zakres, bez wyginania i zaokrąglania','schiena — movimento più piccolo, senza inarcare né arrotondare','גב — טווח קטן יותר, בלי קשת ובלי עיגול','背中は動きを小さく、反らしたり丸めたりしない','허리는 동작을 작게, 젖히거나 둥글게 말지 않기'),
'P': row('плечо — лёгкий вес, без боли','плече — легка вага, без болю','shoulder — light weight, no pain','hombro — poco peso, sin dolor','Schulter — leichtes Gewicht, ohne Schmerz','ombro — peso leve, sem dor','épaule — charge légère, sans douleur','bark — lekki ciężar, bez bólu','spalla — peso leggero, senza dolore','כתף — משקל קל, בלי כאב','肩は軽い重さで、痛みなく','어깨는 가벼운 무게로, 통증 없이'),
'R': row('если есть риск упасть — только у опоры','якщо є ризик упасти — лише біля опори','if you might fall — only next to a support','si hay riesgo de caída — solo junto a un apoyo','bei Sturzgefahr — nur an einer Stütze','se houver risco de queda — só junto a um apoio','en cas de risque de chute — uniquement près d’un appui','jeśli grozi upadek — tylko przy podporze','se c’è rischio di cadere — solo vicino a un appoggio','אם יש סיכון לנפילה — רק ליד תמיכה','転倒の心配があるときは必ず支えのそばで','넘어질 위험이 있으면 반드시 지지물 옆에서'),
}
