# 2026-10-10 — решения каталога v2 (docs/FITNESS-EXERCISE-CATALOG.md, 2026-10-08):
# замены в старых планах (REN — по индексу в names.json) и упражнения для №16 «Пилатес», №17 «Тело-разум»
# и ходьбы Otago в №13 (NEW — дописываются после tr_extra.X).
REN = {
48: dict(ru="«Пловец» лёжа на животе: рука и нога попеременно",uk="«Плавець» лежачи на животі: рука й нога по черзі",en="“Swimmer” lying on the stomach: alternate arm and leg",es="«Nadador» boca abajo: brazo y pierna alternos",de="„Schwimmer“ in Bauchlage: Arm und Bein im Wechsel",pt="«Nadador» de bruços: braço e perna alternados",fr="« Nageur » à plat ventre : bras et jambe en alternance",pl="„Pływak” na brzuchu: ręka i noga naprzemiennie",it="«Nuotatore» a pancia in giù: braccio e gamba alternati",he="«שחיין» על הבטן: יד ורגל לסירוגין",ja="うつ伏せで「スイマー」：腕と脚を交互に",ko="엎드려 '수영': 팔과 다리 번갈아"),
65: dict(ru="Подъём гантелей в стороны до уровня плеч",uk="Підйом гантелей у сторони до рівня плечей",en="Dumbbell lateral raise to shoulder height",es="Elevaciones laterales con mancuernas hasta la altura de los hombros",de="Seitheben mit Kurzhanteln bis Schulterhöhe",pt="Elevação lateral com halteres até a altura dos ombros",fr="Élévations latérales avec haltères jusqu’à hauteur d’épaules",pl="Unoszenie hantli bokiem do wysokości barków",it="Alzate laterali con manubri fino all’altezza delle spalle",he="הרמת משקולות לצדדים עד גובה הכתפיים",ja="ダンベルを肩の高さまで横に上げる",ko="덤벨 어깨 높이까지 옆으로 들기"),
112: dict(ru="Шаг-реакция по голосу: вперёд, вбок, назад по команде",uk="Крок-реакція на голос: вперед, убік, назад за командою",en="Step reaction to a voice cue: forward, side, back on command",es="Paso de reacción a la voz: adelante, al lado, atrás a la orden",de="Schritt-Reaktion auf Zuruf: vor, zur Seite, zurück auf Kommando",pt="Passo de reação à voz: frente, lado, trás ao comando",fr="Pas-réaction à la voix : avant, côté, arrière sur commande",pl="Krok-reakcja na głos: w przód, w bok, w tył na komendę",it="Passo-reazione alla voce: avanti, di lato, indietro al comando",he="צעד-תגובה לקול: קדימה, הצידה, אחורה לפי פקודה",ja="声に反応して一歩：合図で前・横・後ろへ",ko="목소리 반응 스텝: 신호에 앞·옆·뒤로"),
151: dict(ru="«Пловец» на животе, спокойно",uk="«Плавець» на животі, спокійно",en="“Swimmer” on the stomach, gently",es="«Nadador» boca abajo, con calma",de="„Schwimmer“ in Bauchlage, ruhig",pt="«Nadador» de bruços, com calma",fr="« Nageur » à plat ventre, calmement",pl="„Pływak” na brzuchu, spokojnie",it="«Nuotatore» a pancia in giù, con calma",he="«שחיין» על הבטן, ברוגע",ja="うつ伏せで「スイマー」、ゆっくり",ko="엎드려 '수영', 천천히"),
167: dict(ru="«Пловец» на животе (разгибание спины)",uk="«Плавець» на животі (розгинання спини)",en="“Swimmer” on the stomach (back extension)",es="«Nadador» boca abajo (extensión de espalda)",de="„Schwimmer“ in Bauchlage (Rückenstrecken)",pt="«Nadador» de bruços (extensão das costas)",fr="« Nageur » à plat ventre (extension du dos)",pl="„Pływak” na brzuchu (wyprost pleców)",it="«Nuotatore» a pancia in giù (estensione della schiena)",he="«שחיין» על הבטן (יישור הגב)",ja="うつ伏せで「スイマー」（背中を伸ばす）",ko="엎드려 '수영'(등 펴기)"),
168: dict(ru="«Пловец» с паузой 3 с вверху",uk="«Плавець» із паузою 3 с угорі",en="“Swimmer” with a 3 s pause at the top",es="«Nadador» con pausa de 3 s arriba",de="„Schwimmer“ mit 3 s Pause oben",pt="«Nadador» com pausa de 3 s no alto",fr="« Nageur » avec pause de 3 s en haut",pl="„Pływak” z pauzą 3 s na górze",it="«Nuotatore» con pausa di 3 s in alto",he="«שחיין» עם עצירה של 3 שנ׳ למעלה",ja="上で3秒止める「スイマー」",ko="위에서 3초 멈추는 '수영'"),
}
NEW = {
'ru':["Ходьба по программе Otago у стены: боком, спиной вперёд, на носках, на пятках","Подъёмы ноги лёжа на боку","«Раскладушка» лёжа на боку","Круги ногой лёжа, колено согнуто","«Сотня» без подъёма головы: дыхание и руки","Вытяжение одной ноги без подъёма головы","Мягкий «Лебедь»: подъём груди на предплечьях","«Русалка»: боковой наклон сидя","Поза ребёнка","Гора с дыханием","Перенос веса с ноги на ногу с руками (тайцзи)","«Разделение гривы» (тайцзи)","«Облачные руки» с шагом в сторону (тайцзи)","Дерево у стены или у стула","Воин II","«Стул»: полуприсед, руки вверх","Сфинкс (мягкая кобра)","Расслабление лёжа с дыханием"],
'uk':["Ходьба за програмою Otago біля стіни: боком, спиною вперед, на носках, на п’ятах","Підйоми ноги лежачи на боці","«Розкладачка» лежачи на боці","Кола ногою лежачи, коліно зігнуте","«Сотня» без підйому голови: дихання і руки","Витягнення однієї ноги без підйому голови","М’який «Лебідь»: підйом грудей на передпліччях","«Русалка»: бічний нахил сидячи","Поза дитини","Гора з диханням","Перенесення ваги з ноги на ногу з руками (тайцзі)","«Розділення гриви» (тайцзі)","«Хмарні руки» з кроком убік (тайцзі)","Дерево біля стіни або біля стільця","Воїн II","«Стілець»: напівприсід, руки вгору","Сфінкс (м’яка кобра)","Розслаблення лежачи з диханням"],
'en':["Otago walking by the wall: sideways, backwards, on toes, on heels","Side-lying leg lifts","Clamshell lying on your side","Leg circles lying down, knee bent","The “Hundred” without lifting the head: breathing and arms","Single-leg stretch without lifting the head","Gentle “Swan”: chest lift on the forearms","“Mermaid”: seated side bend","Child’s pose","Mountain pose with breathing","Weight shift from leg to leg with arms (tai chi)","“Parting the horse’s mane” (tai chi)","“Cloud hands” with a side step (tai chi)","Tree pose by a wall or chair","Warrior II","“Chair”: half squat, arms up","Sphinx (gentle cobra)","Lying relaxation with breathing"],
'es':["Marcha Otago junto a la pared: de lado, hacia atrás, de puntillas, de talones","Elevaciones de pierna tumbado de lado","«Almeja» tumbado de lado","Círculos de pierna tumbado, rodilla doblada","El «Cien» sin levantar la cabeza: respiración y brazos","Estiramiento de una pierna sin levantar la cabeza","«Cisne» suave: elevar el pecho sobre los antebrazos","«Sirena»: inclinación lateral sentado","Postura del niño","Postura de la montaña con respiración","Paso del peso de una pierna a otra con brazos (taichí)","«Separar la crin del caballo» (taichí)","«Manos de nube» con paso lateral (taichí)","Árbol junto a la pared o la silla","Guerrero II","«Silla»: media sentadilla, brazos arriba","Esfinge (cobra suave)","Relajación tumbado con respiración"],
'de':["Otago-Gehen an der Wand: seitwärts, rückwärts, auf Zehen, auf Fersen","Beinheben in Seitlage","„Muschel“ in Seitlage","Beinkreisen in Rückenlage, Knie gebeugt","„Hundred“ ohne Kopfheben: Atmung und Arme","Einbein-Strecken ohne Kopfheben","Sanfter „Schwan“: Brust auf den Unterarmen anheben","„Meerjungfrau“: Seitbeuge im Sitzen","Stellung des Kindes","Berghaltung mit Atmung","Gewicht von Bein zu Bein verlagern mit Armen (Tai-Chi)","„Mähne des Wildpferds teilen“ (Tai-Chi)","„Wolkenhände“ mit Seitschritt (Tai-Chi)","Baum an der Wand oder am Stuhl","Krieger II","„Stuhl“: halbe Kniebeuge, Arme hoch","Sphinx (sanfte Kobra)","Entspannung in Rückenlage mit Atmung"],
'pt':["Caminhada Otago junto à parede: de lado, de costas, na ponta dos pés, nos calcanhares","Elevações de perna deitado de lado","«Concha» deitado de lado","Círculos de perna deitado, joelho dobrado","O «Cem» sem levantar a cabeça: respiração e braços","Alongamento de uma perna sem levantar a cabeça","«Cisne» suave: elevar o peito apoiado nos antebraços","«Sereia»: inclinação lateral sentado","Postura da criança","Postura da montanha com respiração","Transferir o peso de uma perna para a outra com os braços (tai chi)","«Separar a crina do cavalo» (tai chi)","«Mãos de nuvem» com passo lateral (tai chi)","Árvore junto à parede ou à cadeira","Guerreiro II","«Cadeira»: meio agachamento, braços para cima","Esfinge (cobra suave)","Relaxamento deitado com respiração"],
'fr':["Marche Otago le long du mur : de côté, à reculons, sur la pointe des pieds, sur les talons","Élévations de jambe allongé sur le côté","« Coquillage » allongé sur le côté","Cercles de jambe allongé, genou plié","Le « Hundred » sans lever la tête : respiration et bras","Étirement d’une jambe sans lever la tête","« Cygne » doux : soulever la poitrine sur les avant-bras","« Sirène » : inclinaison latérale assis","Posture de l’enfant","Posture de la montagne avec respiration","Transfert du poids d’une jambe à l’autre avec les bras (tai-chi)","« Séparer la crinière du cheval » (tai-chi)","« Mains dans les nuages » avec pas de côté (tai-chi)","Arbre contre le mur ou près d’une chaise","Guerrier II","« Chaise » : demi-squat, bras levés","Sphinx (cobra doux)","Relaxation allongée avec respiration"],
'pl':["Chód Otago przy ścianie: bokiem, tyłem, na palcach, na piętach","Unoszenie nogi w leżeniu na boku","„Muszelka” w leżeniu na boku","Krążenia nogą w leżeniu, kolano ugięte","„Setka” bez unoszenia głowy: oddech i ręce","Wyciąganie jednej nogi bez unoszenia głowy","Łagodny „Łabędź”: uniesienie klatki na przedramionach","„Syrenka”: skłon w bok na siedząco","Pozycja dziecka","Pozycja góry z oddechem","Przenoszenie ciężaru z nogi na nogę z rękami (tai chi)","„Rozczesywanie grzywy” (tai chi)","„Ręce w chmurach” z krokiem w bok (tai chi)","Drzewo przy ścianie lub krześle","Wojownik II","„Krzesło”: półprzysiad, ręce w górę","Sfinks (łagodna kobra)","Relaks na leżąco z oddechem"],
'it':["Camminata Otago lungo il muro: di lato, all’indietro, sulle punte, sui talloni","Sollevamenti della gamba sdraiati sul fianco","«Conchiglia» sdraiati sul fianco","Cerchi con la gamba da sdraiati, ginocchio piegato","Il «Cento» senza sollevare la testa: respiro e braccia","Allungamento di una gamba senza sollevare la testa","«Cigno» dolce: sollevare il petto sugli avambracci","«Sirena»: inclinazione laterale da seduti","Posizione del bambino","Posizione della montagna con il respiro","Spostamento del peso da una gamba all’altra con le braccia (tai chi)","«Separare la criniera del cavallo» (tai chi)","«Mani tra le nuvole» con passo laterale (tai chi)","Albero vicino al muro o alla sedia","Guerriero II","«Sedia»: mezzo squat, braccia in alto","Sfinge (cobra dolce)","Rilassamento da sdraiati con il respiro"],
'he':["הליכת Otago ליד הקיר: הצידה, לאחור, על הבהונות, על העקבים","הרמות רגל בשכיבה על הצד","«צדפה» בשכיבה על הצד","מעגלי רגל בשכיבה, ברך כפופה","«המאה» בלי להרים את הראש: נשימה וידיים","מתיחת רגל אחת בלי להרים את הראש","«ברבור» עדין: הרמת החזה על האמות","«בת ים»: כפיפה הצידה בישיבה","תנוחת הילד","תנוחת ההר עם נשימה","העברת משקל מרגל לרגל עם ידיים (טאי צ׳י)","«הפרדת רעמת הסוס» (טאי צ׳י)","«ידי ענן» עם צעד הצידה (טאי צ׳י)","עץ ליד הקיר או הכיסא","לוחם II","«כיסא»: חצי סקוואט, ידיים למעלה","ספינקס (קוברה עדינה)","הרפיה בשכיבה עם נשימה"],
'ja':["壁沿いにオタゴ歩行：横歩き・後ろ歩き・つま先歩き・かかと歩き","横向きで脚を上げる","横向きでクラムシェル","仰向けで脚回し（ひざは曲げる）","頭を上げない「ハンドレッド」：呼吸と腕","頭を上げない片脚ストレッチ","やさしい「スワン」：前腕で胸を起こす","「マーメイド」：座って体側を伸ばす","チャイルドポーズ","呼吸に合わせて山のポーズ","腕を添えて左右に体重移動（太極拳）","「野馬分鬃」（太極拳）","横に歩く「雲手」（太極拳）","壁か椅子のそばで木のポーズ","戦士のポーズII","「椅子のポーズ」：半分しゃがんで腕を上へ","スフィンクス（やさしいコブラ）","仰向けで呼吸しながらリラックス"],
'ko':["벽 옆 오타고 걷기: 옆으로, 뒤로, 발끝으로, 발뒤꿈치로","옆으로 누워 다리 들기","옆으로 누워 클램셸","누워서 다리 돌리기(무릎 굽힘)","머리 들지 않는 '헌드레드': 호흡과 팔","머리 들지 않고 한 다리 뻗기","부드러운 '백조': 팔꿈치로 가슴 들기","'인어': 앉아서 옆구리 늘이기","아기 자세","호흡하며 산 자세","팔과 함께 다리에서 다리로 체중 이동(태극권)","'야마분종'(태극권)","옆으로 걸으며 '운수'(태극권)","벽이나 의자 옆에서 나무 자세","전사 자세 II","'의자 자세': 반쯤 앉아 팔 위로","스핑크스(부드러운 코브라)","누워서 호흡하며 이완"],
}
