// СГЕНЕРИРОВАНО tools/build-dayplan-base.js — РУКАМИ НЕ ПРАВИТЬ.
// Источник: interpreter/interpreter-via-l.html, функции _bpChapterData и _actFactor
// (базовая «Памятка дня», уже на 12 языках). Правка текстов — в клиенте, затем
// `node tools/build-dayplan-base.js`. Зачем так — docs/DAY-PLAN-DETERMINISTIC-PLAN.md §5.
// Дата генерации: 2026-09-22

// L() клиента отдаёт строку текущего языка; здесь язык приходит параметром.
let _L_LANG = 'en';
const L = o => (o && typeof o === 'object') ? (o[_L_LANG] || o.en || o.ru || '') : o;

function _actFactor(data){ var f=data.act_freq; return f==='high'?1.6 : (f==='moderate'||f==='mod')?1.5 : f==='low'?1.3 : 1.2; }   /* 'mod' — опечатка: анкета сохраняет 'moderate' (value у радиокнопки af3), и у человека с тренировками 3–4 раза в неделю коэффициент падал до 1.2, а белок на приём выходил 28 г вместо 35. Старое 'mod' оставлено на случай сохранённых профилей. Поймано 2026-09-22 на движке памятки. */

var _BP_CS='background:linear-gradient(150deg,#1b1712,#13100b);border:1px solid rgba(226,185,90,.28);border-radius:16px;padding:15px 16px;margin-bottom:12px;';
// ═══ ПАМЯТКА ДНЯ — 6 глав → BottomSheet (детерминированно, из велнес-базы; RU-пилот, i18n позже) ═══

function _bpChapterData(id, data){
  var w=parseFloat(data.weight)||70, per=Math.round(w*_actFactor(data)/3), isMale=data.gender==='male';
  var age=parseInt(data.age)||48, over40=age>=40, f=data.act_freq;
  if(id==='morning'){
    var bf=isMale?[
      L({ru:'Омлет из 3 яиц + тыквенные семечки (цинк) + зелень',en:'3-egg omelette + pumpkin seeds (zinc) + greens',uk:'Омлет із 3 яєць + гарбузове насіння (цинк) + зелень',es:'Tortilla de 3 huevos + semillas de calabaza (zinc) + verduras',de:'Omelett aus 3 Eiern + Kürbiskerne (Zink) + Grünzeug',pt:'Omelete de 3 ovos + sementes de abóbora (zinco) + verduras',fr:'Omelette de 3 œufs + graines de courge (zinc) + verdure',pl:'Omlet z 3 jaj + pestki dyni (cynk) + zielenina',it:'Omelette di 3 uova + semi di zucca (zinco) + verdure',he:'חביתה מ-3 ביצים + גרעיני דלעת (אבץ) + ירקות עלים',ja:'卵3個のオムレツ + かぼちゃの種（亜鉛）+ 青菜',ko:'달걀 3개 오믈렛 + 호박씨(아연) + 채소'}),
      L({ru:'Творог ~180 г + грецкий орех + ягоды',en:'Cottage cheese ~180 g + walnuts + berries',uk:'Сир ~180 г + волоський горіх + ягоди',es:'Requesón ~180 g + nueces + bayas',de:'Hüttenkäse ~180 g + Walnüsse + Beeren',pt:'Queijo cottage ~180 g + nozes + frutas vermelhas',fr:'Fromage blanc ~180 g + noix + baies',pl:'Twaróg ~180 g + orzechy włoskie + jagody',it:'Ricotta ~180 g + noci + frutti di bosco',he:'גבינת קוטג׳ ~180 גרם + אגוזי מלך + פירות יער',ja:'カッテージチーズ約180g + くるみ + ベリー',ko:'코티지치즈 ~180g + 호두 + 베리'}),
      L({ru:'Скумбрия/лосось + цельнозерновой тост + авокадо',en:'Mackerel/salmon + wholegrain toast + avocado',uk:'Скумбрія/лосось + цільнозерновий тост + авокадо',es:'Caballa/salmón + tostada integral + aguacate',de:'Makrele/Lachs + Vollkorntoast + Avocado',pt:'Cavala/salmão + torrada integral + abacate',fr:'Maquereau/saumon + toast complet + avocat',pl:'Makrela/łosoś + tost pełnoziarnisty + awokado',it:'Sgombro/salmone + toast integrale + avocado',he:'מקרל/סלמון + טוסט מחיטה מלאה + אבוקדו',ja:'サバ/サーモン + 全粒トースト + アボカド',ko:'고등어/연어 + 통곡물 토스트 + 아보카도'}),
      L({ru:'Греческий йогурт + миндаль + семена чиа',en:'Greek yogurt + almonds + chia seeds',uk:'Грецький йогурт + мигдаль + насіння чіа',es:'Yogur griego + almendras + semillas de chía',de:'Griechischer Joghurt + Mandeln + Chiasamen',pt:'Iogurte grego + amêndoas + sementes de chia',fr:'Yaourt grec + amandes + graines de chia',pl:'Jogurt grecki + migdały + nasiona chia',it:'Yogurt greco + mandorle + semi di chia',he:'יוגורט יווני + שקדים + זרעי צ׳יה',ja:'ギリシャヨーグルト + アーモンド + チアシード',ko:'그릭요거트 + 아몬드 + 치아씨드'}),
      L({ru:'Яичница из 3 яиц + цельнозерновой тост + помидоры',en:'3-egg scramble + wholegrain toast + tomatoes',uk:'Яєчня з 3 яєць + цільнозерновий тост + помідори',es:'Huevos revueltos (3) + tostada integral + tomates',de:'Rührei aus 3 Eiern + Vollkorntoast + Tomaten',pt:'Ovos mexidos (3) + torrada integral + tomate',fr:'Œufs brouillés (3) + toast complet + tomates',pl:'Jajecznica z 3 jaj + tost pełnoziarnisty + pomidory',it:'Uova strapazzate (3) + toast integrale + pomodori',he:'ביצים מקושקשות (3) + טוסט מחיטה מלאה + עגבניות',ja:'卵3個のスクランブル + 全粒トースト + トマト',ko:'달걀 3개 스크램블 + 통곡물 토스트 + 토마토'}),
      L({ru:'Овсянка + порция протеина + орехи + банан',en:'Oatmeal + a scoop of protein + nuts + banana',uk:'Вівсянка + порція протеїну + горіхи + банан',es:'Avena + una porción de proteína + nueces + plátano',de:'Haferbrei + eine Portion Protein + Nüsse + Banane',pt:'Aveia + uma porção de proteína + nozes + banana',fr:'Flocons d’avoine + une portion de protéine + noix + banane',pl:'Owsianka + porcja białka + orzechy + banan',it:'Fiocchi d’avena + una porzione di proteine + noci + banana',he:'דייסת שיבולת שועל + מנת חלבון + אגוזים + בננה',ja:'オートミール + プロテイン1杯 + ナッツ + バナナ',ko:'오트밀 + 프로틴 1스쿱 + 견과류 + 바나나'})
    ]:[
      L({ru:'Омлет из 2–3 яиц + авокадо + горсть зелени',en:'2–3-egg omelette + avocado + a handful of greens',uk:'Омлет із 2–3 яєць + авокадо + жменя зелені',es:'Tortilla de 2–3 huevos + aguacate + un puñado de verduras',de:'Omelett aus 2–3 Eiern + Avocado + eine Handvoll Grünzeug',pt:'Omelete de 2–3 ovos + abacate + um punhado de verduras',fr:'Omelette de 2–3 œufs + avocat + une poignée de verdure',pl:'Omlet z 2–3 jaj + awokado + garść zieleniny',it:'Omelette di 2–3 uova + avocado + una manciata di verdure',he:'חביתה מ-2–3 ביצים + אבוקדו + חופן ירקות עלים',ja:'卵2〜3個のオムレツ + アボカド + 青菜ひとつかみ',ko:'달걀 2~3개 오믈렛 + 아보카도 + 채소 한 줌'}),
      L({ru:'Творог 5% ~180 г + ягоды + 1 ст. л. молотого льна',en:'Cottage cheese ~180 g + berries + 1 tbsp ground flaxseed',uk:'Сир 5% ~180 г + ягоди + 1 ст. л. меленого льону',es:'Requesón ~180 g + bayas + 1 cda de linaza molida',de:'Hüttenkäse ~180 g + Beeren + 1 EL gemahlene Leinsamen',pt:'Queijo cottage ~180 g + frutas vermelhas + 1 c. sopa de linhaça moída',fr:'Fromage blanc ~180 g + baies + 1 c. à s. de graines de lin moulues',pl:'Twaróg ~180 g + jagody + 1 łyżka mielonego lnu',it:'Ricotta ~180 g + frutti di bosco + 1 cucchiaio di semi di lino macinati',he:'גבינת קוטג׳ ~180 גרם + פירות יער + כף זרעי פשתן טחונים',ja:'カッテージチーズ約180g + ベリー + 挽いた亜麻仁大さじ1',ko:'코티지치즈 ~180g + 베리 + 갈은 아마씨 1큰술'}),
      L({ru:'Греческий йогурт + орехи + семена чиа',en:'Greek yogurt + nuts + chia seeds',uk:'Грецький йогурт + горіхи + насіння чіа',es:'Yogur griego + nueces + semillas de chía',de:'Griechischer Joghurt + Nüsse + Chiasamen',pt:'Iogurte grego + nozes + sementes de chia',fr:'Yaourt grec + noix + graines de chia',pl:'Jogurt grecki + orzechy + nasiona chia',it:'Yogurt greco + noci + semi di chia',he:'יוגורט יווני + אגוזים + זרעי צ׳יה',ja:'ギリシャヨーグルト + ナッツ + チアシード',ko:'그릭요거트 + 견과류 + 치아씨드'}),
      L({ru:'Овсянка на воде + порция протеина + ягоды',en:'Oatmeal on water + a scoop of protein + berries',uk:'Вівсянка на воді + порція протеїну + ягоди',es:'Avena con agua + una porción de proteína + bayas',de:'Haferbrei mit Wasser + eine Portion Protein + Beeren',pt:'Aveia na água + uma porção de proteína + frutas vermelhas',fr:'Flocons d’avoine à l’eau + une portion de protéine + baies',pl:'Owsianka na wodzie + porcja białka + jagody',it:'Fiocchi d’avena con acqua + una porzione di proteine + frutti di bosco',he:'דייסת שיבולת שועל על מים + מנת חלבון + פירות יער',ja:'水で作るオートミール + プロテイン1杯 + ベリー',ko:'물로 만든 오트밀 + 프로틴 1스쿱 + 베리'}),
      L({ru:'Цельнозерновой тост + яйцо-пашот + авокадо',en:'Wholegrain toast + poached egg + avocado',uk:'Цільнозерновий тост + яйце-пашот + авокадо',es:'Tostada integral + huevo escalfado + aguacate',de:'Vollkorntoast + pochiertes Ei + Avocado',pt:'Torrada integral + ovo poché + abacate',fr:'Toast complet + œuf poché + avocat',pl:'Tost pełnoziarnisty + jajko w koszulce + awokado',it:'Toast integrale + uovo in camicia + avocado',he:'טוסט מחיטה מלאה + ביצה עלומה + אבוקדו',ja:'全粒トースト + ポーチドエッグ + アボカド',ko:'통곡물 토스트 + 수란 + 아보카도'}),
      L({ru:'Смузи: кефир + ягоды + протеин + 1 ст. л. льна',en:'Smoothie: kefir + berries + protein + 1 tbsp flaxseed',uk:'Смузі: кефір + ягоди + протеїн + 1 ст. л. льону',es:'Batido: kéfir + bayas + proteína + 1 cda de linaza',de:'Smoothie: Kefir + Beeren + Protein + 1 EL Leinsamen',pt:'Vitamina: kefir + frutas vermelhas + proteína + 1 c. sopa de linhaça',fr:'Smoothie : kéfir + baies + protéine + 1 c. à s. de lin',pl:'Koktajl: kefir + jagody + białko + 1 łyżka lnu',it:'Frullato: kefir + frutti di bosco + proteine + 1 cucchiaio di lino',he:'שייק: קפיר + פירות יער + חלבון + כף זרעי פשתן',ja:'スムージー：ケフィア + ベリー + プロテイン + 亜麻仁大さじ1',ko:'스무디: 케피어 + 베리 + 프로틴 + 아마씨 1큰술'})
    ];
    var supp=isMale?[
      L({ru:'Витамин D3 + K2 с жирной едой — ориентир, значение индивидуально',en:'Vitamin D3 + K2 with a fatty meal — a guideline, individual amounts vary',uk:'Вітамін D3 + K2 з жирною їжею — орієнтир, значення індивідуальне',es:'Vitamina D3 + K2 con una comida grasa — una guía, la cantidad es individual',de:'Vitamin D3 + K2 zu einer fetthaltigen Mahlzeit — ein Richtwert, individuell verschieden',pt:'Vitamina D3 + K2 com uma refeição gordurosa — uma referência, quantidade individual',fr:'Vitamine D3 + K2 avec un repas gras — un repère, quantité individuelle',pl:'Witamina D3 + K2 z tłustym posiłkiem — orientacyjnie, ilość indywidualna',it:'Vitamina D3 + K2 con un pasto grasso — un riferimento, la quantità è individuale',he:'ויטמין D3 + K2 עם ארוחה שומנית — הכוונה, הכמות אישית',ja:'ビタミンD3 + K2 を脂質のある食事と — 目安、量は個人差',ko:'비타민 D3 + K2 지방이 있는 식사와 함께 — 기준일 뿐, 양은 개인차'}),
      L({ru:'Омега-3 ~2 г с едой — сердце и мозг',en:'Omega-3 ~2 g with food — heart and brain',uk:'Омега-3 ~2 г з їжею — серце і мозок',es:'Omega-3 ~2 g con la comida — corazón y cerebro',de:'Omega-3 ~2 g zum Essen — Herz und Gehirn',pt:'Ômega-3 ~2 g com a comida — coração e cérebro',fr:'Oméga-3 ~2 g avec le repas — cœur et cerveau',pl:'Omega-3 ~2 g z jedzeniem — serce i mózg',it:'Omega-3 ~2 g con il cibo — cuore e cervello',he:'אומגה-3 ~2 גרם עם אוכל — לב ומוח',ja:'オメガ3 約2g を食事と — 心臓と脳',ko:'오메가-3 ~2g 식사와 함께 — 심장과 뇌'}),
      L({ru:'Цинк — из еды (тыквенные семечки, яйца); добавкой лишь при недостатке',en:'Zinc — from food (pumpkin seeds, eggs); a supplement only if lacking',uk:'Цинк — з їжі (гарбузове насіння, яйця); добавкою лише за нестачі',es:'Zinc — de la comida (semillas de calabaza, huevos); suplemento solo si falta',de:'Zink — aus der Nahrung (Kürbiskerne, Eier); Supplement nur bei Mangel',pt:'Zinco — da comida (sementes de abóbora, ovos); suplemento só se faltar',fr:'Zinc — via l’alimentation (graines de courge, œufs) ; complément seulement en cas de carence',pl:'Cynk — z jedzenia (pestki dyni, jajka); suplement tylko przy niedoborze',it:'Zinco — dal cibo (semi di zucca, uova); integratore solo se carente',he:'אבץ — מהמזון (גרעיני דלעת, ביצים); תוסף רק במחסור',ja:'亜鉛 — 食事から（かぼちゃの種、卵）；不足時のみ補助',ko:'아연 — 음식으로(호박씨, 달걀); 부족할 때만 보충제'})
    ]:[
      L({ru:'Витамин D3 + K2 с жирной едой — ориентир, значение индивидуально',en:'Vitamin D3 + K2 with a fatty meal — a guideline, individual amounts vary',uk:'Вітамін D3 + K2 з жирною їжею — орієнтир, значення індивідуальне',es:'Vitamina D3 + K2 con una comida grasa — una guía, la cantidad es individual',de:'Vitamin D3 + K2 zu einer fetthaltigen Mahlzeit — ein Richtwert, individuell verschieden',pt:'Vitamina D3 + K2 com uma refeição gordurosa — uma referência, quantidade individual',fr:'Vitamine D3 + K2 avec un repas gras — un repère, quantité individuelle',pl:'Witamina D3 + K2 z tłustym posiłkiem — orientacyjnie, ilość indywidualna',it:'Vitamina D3 + K2 con un pasto grasso — un riferimento, la quantità è individuale',he:'ויטמין D3 + K2 עם ארוחה שומנית — הכוונה, הכמות אישית',ja:'ビタミンD3 + K2 を脂質のある食事と — 目安、量は個人差',ko:'비타민 D3 + K2 지방이 있는 식사와 함께 — 기준일 뿐, 양은 개인차'}),
      L({ru:'Омега-3 ~2 г с едой',en:'Omega-3 ~2 g with food',uk:'Омега-3 ~2 г з їжею',es:'Omega-3 ~2 g con la comida',de:'Omega-3 ~2 g zum Essen',pt:'Ômega-3 ~2 g com a comida',fr:'Oméga-3 ~2 g avec le repas',pl:'Omega-3 ~2 g z jedzeniem',it:'Omega-3 ~2 g con il cibo',he:'אומגה-3 ~2 גרם עם אוכל',ja:'オメガ3 約2g を食事と',ko:'오메가-3 ~2g 식사와 함께'}),
      L({ru:'1 ст. л. молотого льна — мягкая растительная поддержка баланса',en:'1 tbsp ground flaxseed — gentle plant support for inner balance',uk:'1 ст. л. меленого льону — м’яка рослинна підтримка балансу',es:'1 cda de linaza molida — apoyo vegetal suave para el equilibrio',de:'1 EL gemahlene Leinsamen — sanfte pflanzliche Unterstützung des Gleichgewichts',pt:'1 c. sopa de linhaça moída — apoio vegetal suave para o equilíbrio',fr:'1 c. à s. de lin moulu — soutien végétal doux pour l’équilibre',pl:'1 łyżka mielonego lnu — łagodne roślinne wsparcie równowagi',it:'1 cucchiaio di lino macinato — supporto vegetale delicato per l’equilibrio',he:'כף זרעי פשתן טחונים — תמיכה צמחית עדינה לאיזון',ja:'挽いた亜麻仁大さじ1 — バランスへの穏やかな植物性サポート',ko:'갈은 아마씨 1큰술 — 균형을 위한 부드러운 식물성 지원'})
    ];
    return [
      {title:L({ru:'Начните утро спокойно',en:'Start your morning calmly',uk:'Почніть ранок спокійно',es:'Empieza la mañana con calma',de:'Beginne den Morgen ruhig',pt:'Comece a manhã com calma',fr:'Commencez la matinée calmement',pl:'Zacznij poranek spokojnie',it:'Inizia la mattina con calma',he:'התחילו את הבוקר ברוגע',ja:'穏やかに朝を始める',ko:'차분하게 아침을 시작하기'}), items:[
        L({ru:'Стакан воды 250–300 мл сразу после пробуждения',en:'A glass of water 250–300 ml right after waking',uk:'Склянка води 250–300 мл одразу після пробудження',es:'Un vaso de agua 250–300 ml justo al despertar',de:'Ein Glas Wasser 250–300 ml direkt nach dem Aufwachen',pt:'Um copo de água 250–300 ml logo ao acordar',fr:'Un verre d’eau 250–300 ml juste au réveil',pl:'Szklanka wody 250–300 ml zaraz po przebudzeniu',it:'Un bicchiere d’acqua 250–300 ml appena sveglio',he:'כוס מים 250–300 מ״ל מיד עם היקיצה',ja:'起床直後に水250〜300ml',ko:'기상 직후 물 250~300ml'}),
        L({ru:'Дневной свет 10–15 мин в первый час — бодрость и вечерний сон',en:'Daylight 10–15 min in the first hour — alertness and evening sleep',uk:'Денне світло 10–15 хв у першу годину — бадьорість і вечірній сон',es:'Luz natural 10–15 min en la primera hora — energía y sueño nocturno',de:'Tageslicht 10–15 Min in der ersten Stunde — Wachheit und Abendschlaf',pt:'Luz do dia 10–15 min na primeira hora — disposição e sono à noite',fr:'Lumière du jour 10–15 min dans la première heure — vigilance et sommeil du soir',pl:'Światło dzienne 10–15 min w pierwszej godzinie — pobudzenie i wieczorny sen',it:'Luce del giorno 10–15 min nella prima ora — energia e sonno serale',he:'אור יום 10–15 דק׳ בשעה הראשונה — ערנות ושינה בערב',ja:'起床後1時間以内に日光を10〜15分 — 目覚めと夜の睡眠',ko:'기상 후 첫 시간에 햇빛 10~15분 — 각성과 저녁 수면'}),
        L({ru:'Кофе лучше через 60–90 мин после подъёма, не натощак',en:'Coffee is better 60–90 min after waking, not on an empty stomach',uk:'Кава краще через 60–90 хв після підйому, не натщесерце',es:'El café mejor 60–90 min tras despertar, no en ayunas',de:'Kaffee besser 60–90 Min nach dem Aufstehen, nicht nüchtern',pt:'Café melhor 60–90 min após acordar, não em jejum',fr:'Le café de préférence 60–90 min après le réveil, pas à jeun',pl:'Kawa lepiej 60–90 min po wstaniu, nie na czczo',it:'Il caffè meglio 60–90 min dopo il risveglio, non a stomaco vuoto',he:'קפה עדיף 60–90 דק׳ אחרי היקיצה, לא על קיבה ריקה',ja:'コーヒーは起床後60〜90分、空腹時は避ける',ko:'커피는 기상 후 60~90분, 공복은 피하기'})
      ]},
      {title:L({ru:'Разомнитесь',en:'Warm up',uk:'Розімніться',es:'Haz un poco de movimiento',de:'Beweg dich kurz',pt:'Faça um aquecimento',fr:'Échauffez-vous',pl:'Rozgrzej się',it:'Fai un po’ di movimento',he:'התחממו קלות',ja:'軽く体を動かす',ko:'가볍게 몸풀기'}), items:[
        L({ru:'Лёгкая разминка или короткая прогулка 5–10 мин',en:'Light warm-up or a short 5–10 min walk',uk:'Легка розминка або коротка прогулянка 5–10 хв',es:'Calentamiento ligero o un paseo corto de 5–10 min',de:'Leichtes Aufwärmen oder ein kurzer 5–10-Min-Spaziergang',pt:'Aquecimento leve ou uma caminhada curta de 5–10 min',fr:'Échauffement léger ou une courte marche de 5–10 min',pl:'Lekka rozgrzewka lub krótki spacer 5–10 min',it:'Riscaldamento leggero o una breve camminata di 5–10 min',he:'חימום קל או הליכה קצרה 5–10 דק׳',ja:'軽い準備運動か5〜10分の短い散歩',ko:'가벼운 준비운동 또는 5~10분 짧은 산책'}),
        L({ru:'3–5 глубоких вдохов с длинным выдохом — спокойный тонус',en:'3–5 deep breaths with a long exhale — calm tone',uk:'3–5 глибоких вдихів із довгим видихом — спокійний тонус',es:'3–5 respiraciones profundas con exhalación larga — tono tranquilo',de:'3–5 tiefe Atemzüge mit langem Ausatmen — ruhiger Tonus',pt:'3–5 respirações profundas com expiração longa — tônus calmo',fr:'3–5 respirations profondes avec longue expiration — tonus calme',pl:'3–5 głębokich wdechów z długim wydechem — spokojny tonus',it:'3–5 respiri profondi con espirazione lunga — tono calmo',he:'3–5 נשימות עמוקות עם נשיפה ארוכה — טונוס רגוע',ja:'長く吐く深呼吸を3〜5回 — 穏やかなトーン',ko:'긴 날숨과 함께 깊은 호흡 3~5회 — 차분한 상태'})
      ]},
      {title:L({ru:'Завтрак · выберите один (~'+per+' г белка)',en:'Breakfast · pick one (~'+per+' g protein)',uk:'Сніданок · оберіть один (~'+per+' г білка)',es:'Desayuno · elige uno (~'+per+' g de proteína)',de:'Frühstück · wähle eines (~'+per+' g Protein)',pt:'Café da manhã · escolha um (~'+per+' g de proteína)',fr:'Petit-déjeuner · choisissez-en un (~'+per+' g de protéines)',pl:'Śniadanie · wybierz jedno (~'+per+' g białka)',it:'Colazione · scegline uno (~'+per+' g di proteine)',he:'ארוחת בוקר · בחרו אחת (~'+per+' גרם חלבון)',ja:'朝食 · 1つ選ぶ（タンパク質約'+per+'g）',ko:'아침 · 하나 선택 (단백질 ~'+per+'g)'}), variants:true, items:bf},
      {title:L({ru:'Если уже принимаете добавки (утро)',en:'If you already take supplements (morning)',uk:'Якщо вже приймаєте добавки (ранок)',es:'Si ya tomas suplementos (mañana)',de:'Falls du bereits Supplemente nimmst (morgens)',pt:'Se você já toma suplementos (manhã)',fr:'Si vous prenez déjà des compléments (matin)',pl:'Jeśli już bierzesz suplementy (rano)',it:'Se già assumi integratori (mattina)',he:'אם כבר נוטלים תוספים (בוקר)',ja:'すでにサプリを摂っている場合（朝）',ko:'이미 보충제를 드시는 경우 (아침)'}), items:supp}
    ];
  }
  if(id==='lunch'){
    return [
      {title:L({ru:'Обед · выберите один (~'+per+' г белка + овощи + медленные углеводы)',en:'Lunch · pick one (~'+per+' g protein + vegetables + slow carbs)',uk:'Обід · оберіть один (~'+per+' г білка + овочі + повільні вуглеводи)',es:'Almuerzo · elige uno (~'+per+' g de proteína + verduras + carbohidratos lentos)',de:'Mittagessen · wähle eines (~'+per+' g Protein + Gemüse + langsame Kohlenhydrate)',pt:'Almoço · escolha um (~'+per+' g de proteína + legumes + carboidratos lentos)',fr:'Déjeuner · choisissez-en un (~'+per+' g de protéines + légumes + glucides lents)',pl:'Obiad · wybierz jedno (~'+per+' g białka + warzywa + wolne węglowodany)',it:'Pranzo · scegline uno (~'+per+' g di proteine + verdure + carboidrati lenti)',he:'ארוחת צהריים · בחרו אחת (~'+per+' גרם חלבון + ירקות + פחמימות איטיות)',ja:'昼食 · 1つ選ぶ（タンパク質約'+per+'g + 野菜 + 遅い炭水化物）',ko:'점심 · 하나 선택 (단백질 ~'+per+'g + 채소 + 느린 탄수화물)'}), variants:true, items:[
        L({ru:'Индейка/курица ~130 г + гречка + большой салат с оливковым маслом',en:'Turkey/chicken ~130 g + buckwheat + a large salad with olive oil',uk:'Індичка/курка ~130 г + гречка + великий салат з оливковою олією',es:'Pavo/pollo ~130 g + trigo sarraceno + una ensalada grande con aceite de oliva',de:'Pute/Hähnchen ~130 g + Buchweizen + ein großer Salat mit Olivenöl',pt:'Peru/frango ~130 g + trigo-sarraceno + uma salada grande com azeite',fr:'Dinde/poulet ~130 g + sarrasin + une grande salade à l’huile d’olive',pl:'Indyk/kurczak ~130 g + kasza gryczana + duża sałatka z oliwą',it:'Tacchino/pollo ~130 g + grano saraceno + una grande insalata con olio d’oliva',he:'הודו/עוף ~130 גרם + כוסמת + סלט גדול עם שמן זית',ja:'七面鳥/鶏肉約130g + そばの実 + オリーブオイルの大きなサラダ',ko:'칠면조/닭고기 ~130g + 메밀 + 올리브오일 곁들인 큰 샐러드'}),
        L({ru:'Лосось/тунец ~140 г + бурый рис + брокколи',en:'Salmon/tuna ~140 g + brown rice + broccoli',uk:'Лосось/тунець ~140 г + бурий рис + броколі',es:'Salmón/atún ~140 g + arroz integral + brócoli',de:'Lachs/Thunfisch ~140 g + brauner Reis + Brokkoli',pt:'Salmão/atum ~140 g + arroz integral + brócolis',fr:'Saumon/thon ~140 g + riz complet + brocoli',pl:'Łosoś/tuńczyk ~140 g + brązowy ryż + brokuły',it:'Salmone/tonno ~140 g + riso integrale + broccoli',he:'סלמון/טונה ~140 גרם + אורז מלא + ברוקולי',ja:'サーモン/マグロ約140g + 玄米 + ブロッコリー',ko:'연어/참치 ~140g + 현미 + 브로콜리'}),
        L({ru:'Чечевица/нут + тушёные овощи + зелень (растительный день)',en:'Lentils/chickpeas + stewed vegetables + greens (plant-based day)',uk:'Сочевиця/нут + тушковані овочі + зелень (рослинний день)',es:'Lentejas/garbanzos + verduras guisadas + verduras de hoja (día vegetal)',de:'Linsen/Kichererbsen + geschmortes Gemüse + Grünzeug (pflanzlicher Tag)',pt:'Lentilha/grão-de-bico + legumes refogados + verduras (dia vegetal)',fr:'Lentilles/pois chiches + légumes mijotés + verdure (journée végétale)',pl:'Soczewica/ciecierzyca + duszone warzywa + zielenina (dzień roślinny)',it:'Lenticchie/ceci + verdure stufate + verdure a foglia (giorno vegetale)',he:'עדשים/חומוס + ירקות מבושלים + ירקות עלים (יום צמחי)',ja:'レンズ豆/ひよこ豆 + 蒸し煮野菜 + 青菜（植物性の日）',ko:'렌틸/병아리콩 + 채소 조림 + 잎채소 (식물성의 날)'}),
        L({ru:'Постная говядина + запечённый батат + листовые овощи',en:'Lean beef + baked sweet potato + leafy greens',uk:'Пісна яловичина + запечений батат + листові овочі',es:'Carne magra de res + boniato al horno + verduras de hoja',de:'Mageres Rindfleisch + gebackene Süßkartoffel + Blattgemüse',pt:'Carne magra + batata-doce assada + folhas verdes',fr:'Bœuf maigre + patate douce au four + légumes-feuilles',pl:'Chuda wołowina + pieczony batat + zielone warzywa liściaste',it:'Manzo magro + patata dolce al forno + verdure a foglia',he:'בקר רזה + בטטה אפויה + ירקות עלים',ja:'赤身牛肉 + 焼きさつまいも + 葉物野菜',ko:'살코기 소고기 + 구운 고구마 + 잎채소'}),
        L({ru:'Куриная грудка + киноа + овощи-гриль',en:'Chicken breast + quinoa + grilled vegetables',uk:'Куряча грудка + кіноа + овочі-гриль',es:'Pechuga de pollo + quinoa + verduras a la parrilla',de:'Hähnchenbrust + Quinoa + gegrilltes Gemüse',pt:'Peito de frango + quinoa + legumes grelhados',fr:'Blanc de poulet + quinoa + légumes grillés',pl:'Pierś z kurczaka + komosa ryżowa + warzywa z grilla',it:'Petto di pollo + quinoa + verdure grigliate',he:'חזה עוף + קינואה + ירקות בגריל',ja:'鶏むね肉 + キヌア + 焼き野菜',ko:'닭가슴살 + 퀴노아 + 구운 채소'}),
        L({ru:'Тёплый салат: фасоль + яйцо + авокадо + зелень',en:'Warm salad: beans + egg + avocado + greens',uk:'Теплий салат: квасоля + яйце + авокадо + зелень',es:'Ensalada tibia: alubias + huevo + aguacate + verduras',de:'Warmer Salat: Bohnen + Ei + Avocado + Grünzeug',pt:'Salada morna: feijão + ovo + abacate + verduras',fr:'Salade tiède : haricots + œuf + avocat + verdure',pl:'Ciepła sałatka: fasola + jajko + awokado + zielenina',it:'Insalata tiepida: fagioli + uovo + avocado + verdure',he:'סלט חמים: שעועית + ביצה + אבוקדו + ירקות עלים',ja:'温サラダ：豆 + 卵 + アボカド + 青菜',ko:'따뜻한 샐러드: 콩 + 달걀 + 아보카도 + 채소'})
      ]},
      {title:L({ru:'Если уже принимаете добавки (обед)',en:'If you already take supplements (lunch)',uk:'Якщо вже приймаєте добавки (обід)',es:'Si ya tomas suplementos (almuerzo)',de:'Falls du bereits Supplemente nimmst (mittags)',pt:'Se você já toma suplementos (almoço)',fr:'Si vous prenez déjà des compléments (midi)',pl:'Jeśli już bierzesz suplementy (obiad)',it:'Se già assumi integratori (pranzo)',he:'אם כבר נוטלים תוספים (צהריים)',ja:'すでにサプリを摂っている場合（昼）',ko:'이미 보충제를 드시는 경우 (점심)'}), items:[
        L({ru:'Обычно дополнительно не нужно — фокус на цельной еде',en:'Usually nothing extra is needed — focus on whole food',uk:'Зазвичай додатково не потрібно — фокус на цільній їжі',es:'Normalmente no hace falta nada extra — enfócate en comida real',de:'Meist ist nichts Zusätzliches nötig — Fokus auf vollwertige Kost',pt:'Normalmente nada extra é preciso — foco na comida integral',fr:'En général rien de plus n’est nécessaire — misez sur les aliments complets',pl:'Zwykle nic dodatkowego nie trzeba — postaw na pełnowartościowe jedzenie',it:'Di solito non serve nulla in più — punta sul cibo integrale',he:'בדרך כלל אין צורך בתוספת — התמקדו במזון מלא',ja:'通常は追加は不要 — 未加工の食事を重視',ko:'보통 추가는 필요 없음 — 자연식품에 집중'}),
        L({ru:'Клетчатка: добавьте зелень/овощи для ровного пищеварения',en:'Fiber: add greens/vegetables for smooth digestion',uk:'Клітковина: додайте зелень/овочі для рівного травлення',es:'Fibra: añade verduras/hortalizas para una digestión suave',de:'Ballaststoffe: Grünzeug/Gemüse für eine ruhige Verdauung',pt:'Fibra: adicione verduras/legumes para uma digestão tranquila',fr:'Fibres : ajoutez de la verdure/des légumes pour une digestion douce',pl:'Błonnik: dodaj zieleninę/warzywa dla równego trawienia',it:'Fibra: aggiungi verdure per una digestione regolare',he:'סיבים: הוסיפו ירקות עלים/ירקות לעיכול חלק',ja:'食物繊維：青菜/野菜を加えて消化を穏やかに',ko:'식이섬유: 잎채소/채소를 더해 소화를 부드럽게'})
      ]}
    ];
  }
  if(id==='evening'){
    var din=isMale?[
      L({ru:'Белая рыба + тушёные овощи',en:'White fish + stewed vegetables',uk:'Біла риба + тушковані овочі',es:'Pescado blanco + verduras guisadas',de:'Weißer Fisch + geschmortes Gemüse',pt:'Peixe branco + legumes refogados',fr:'Poisson blanc + légumes mijotés',pl:'Biała ryba + duszone warzywa',it:'Pesce bianco + verdure stufate',he:'דג לבן + ירקות מבושלים',ja:'白身魚 + 蒸し煮野菜',ko:'흰살생선 + 채소 조림'}),L({ru:'Куриная грудка + большой салат',en:'Chicken breast + a large salad',uk:'Куряча грудка + великий салат',es:'Pechuga de pollo + una ensalada grande',de:'Hähnchenbrust + ein großer Salat',pt:'Peito de frango + uma salada grande',fr:'Blanc de poulet + une grande salade',pl:'Pierś z kurczaka + duża sałatka',it:'Petto di pollo + una grande insalata',he:'חזה עוף + סלט גדול',ja:'鶏むね肉 + 大きなサラダ',ko:'닭가슴살 + 큰 샐러드'}),L({ru:'Омлет + овощи-гриль',en:'Omelette + grilled vegetables',uk:'Омлет + овочі-гриль',es:'Tortilla + verduras a la parrilla',de:'Omelett + gegrilltes Gemüse',pt:'Omelete + legumes grelhados',fr:'Omelette + légumes grillés',pl:'Omlet + warzywa z grilla',it:'Omelette + verdure grigliate',he:'חביתה + ירקות בגריל',ja:'オムレツ + 焼き野菜',ko:'오믈렛 + 구운 채소'}),L({ru:'Тёплый овощной суп + порция белка',en:'Warm vegetable soup + a portion of protein',uk:'Теплий овочевий суп + порція білка',es:'Sopa de verduras tibia + una porción de proteína',de:'Warme Gemüsesuppe + eine Portion Protein',pt:'Sopa de legumes morna + uma porção de proteína',fr:'Soupe de légumes tiède + une portion de protéine',pl:'Ciepła zupa warzywna + porcja białka',it:'Zuppa di verdure calda + una porzione di proteine',he:'מרק ירקות חם + מנת חלבון',ja:'温野菜スープ + タンパク質1品',ko:'따뜻한 채소 수프 + 단백질 한 접시'}),L({ru:'Индейка + тушёная капуста',en:'Turkey + stewed cabbage',uk:'Індичка + тушкована капуста',es:'Pavo + col guisada',de:'Pute + geschmorter Kohl',pt:'Peru + repolho refogado',fr:'Dinde + chou mijoté',pl:'Indyk + duszona kapusta',it:'Tacchino + cavolo stufato',he:'הודו + כרוב מבושל',ja:'七面鳥 + キャベツの蒸し煮',ko:'칠면조 + 양배추 조림'}),L({ru:'Творог + орехи (лёгкий поздний вариант)',en:'Cottage cheese + nuts (light late option)',uk:'Сир + горіхи (легкий пізній варіант)',es:'Requesón + nueces (opción ligera para tarde)',de:'Hüttenkäse + Nüsse (leichte späte Option)',pt:'Queijo cottage + nozes (opção leve para tarde)',fr:'Fromage blanc + noix (option légère tardive)',pl:'Twaróg + orzechy (lekka późna opcja)',it:'Ricotta + noci (opzione leggera serale)',he:'גבינת קוטג׳ + אגוזים (אפשרות קלה מאוחרת)',ja:'カッテージチーズ + ナッツ（軽い遅めの選択）',ko:'코티지치즈 + 견과류 (가벼운 늦은 옵션)'})
    ]:[
      L({ru:'Белая рыба + тушёные овощи',en:'White fish + stewed vegetables',uk:'Біла риба + тушковані овочі',es:'Pescado blanco + verduras guisadas',de:'Weißer Fisch + geschmortes Gemüse',pt:'Peixe branco + legumes refogados',fr:'Poisson blanc + légumes mijotés',pl:'Biała ryba + duszone warzywa',it:'Pesce bianco + verdure stufate',he:'דג לבן + ירקות מבושלים',ja:'白身魚 + 蒸し煮野菜',ko:'흰살생선 + 채소 조림'}),L({ru:'Творог + зелень + 1 ст. л. льна',en:'Cottage cheese + greens + 1 tbsp flaxseed',uk:'Сир + зелень + 1 ст. л. льону',es:'Requesón + verduras + 1 cda de linaza',de:'Hüttenkäse + Grünzeug + 1 EL Leinsamen',pt:'Queijo cottage + verduras + 1 c. sopa de linhaça',fr:'Fromage blanc + verdure + 1 c. à s. de lin',pl:'Twaróg + zielenina + 1 łyżka lnu',it:'Ricotta + verdure + 1 cucchiaio di lino',he:'גבינת קוטג׳ + ירקות עלים + כף זרעי פשתן',ja:'カッテージチーズ + 青菜 + 亜麻仁大さじ1',ko:'코티지치즈 + 채소 + 아마씨 1큰술'}),L({ru:'Омлет + большой салат',en:'Omelette + a large salad',uk:'Омлет + великий салат',es:'Tortilla + una ensalada grande',de:'Omelett + ein großer Salat',pt:'Omelete + uma salada grande',fr:'Omelette + une grande salade',pl:'Omlet + duża sałatka',it:'Omelette + una grande insalata',he:'חביתה + סלט גדול',ja:'オムレツ + 大きなサラダ',ko:'오믈렛 + 큰 샐러드'}),L({ru:'Тёплый овощной суп + порция белка',en:'Warm vegetable soup + a portion of protein',uk:'Теплий овочевий суп + порція білка',es:'Sopa de verduras tibia + una porción de proteína',de:'Warme Gemüsesuppe + eine Portion Protein',pt:'Sopa de legumes morna + uma porção de proteína',fr:'Soupe de légumes tiède + une portion de protéine',pl:'Ciepła zupa warzywna + porcja białka',it:'Zuppa di verdure calda + una porzione di proteine',he:'מרק ירקות חם + מנת חלבון',ja:'温野菜スープ + タンパク質1品',ko:'따뜻한 채소 수프 + 단백질 한 접시'}),L({ru:'Запечённая курица + брокколи на пару',en:'Baked chicken + steamed broccoli',uk:'Запечена курка + броколі на парі',es:'Pollo al horno + brócoli al vapor',de:'Gebackenes Hähnchen + gedämpfter Brokkoli',pt:'Frango assado + brócolis no vapor',fr:'Poulet au four + brocoli vapeur',pl:'Pieczony kurczak + brokuły na parze',it:'Pollo al forno + broccoli al vapore',he:'עוף אפוי + ברוקולי מאודה',ja:'焼き鶏 + 蒸しブロッコリー',ko:'구운 닭고기 + 찐 브로콜리'}),L({ru:'Греческий йогурт + орехи (лёгкий поздний вариант)',en:'Greek yogurt + nuts (light late option)',uk:'Грецький йогурт + горіхи (легкий пізній варіант)',es:'Yogur griego + nueces (opción ligera para tarde)',de:'Griechischer Joghurt + Nüsse (leichte späte Option)',pt:'Iogurte grego + nozes (opção leve para tarde)',fr:'Yaourt grec + noix (option légère tardive)',pl:'Jogurt grecki + orzechy (lekka późna opcja)',it:'Yogurt greco + noci (opzione leggera serale)',he:'יוגורט יווני + אגוזים (אפשרות קלה מאוחרת)',ja:'ギリシャヨーグルト + ナッツ（軽い遅めの選択）',ko:'그릭요거트 + 견과류 (가벼운 늦은 옵션)'})
    ];
    return [
      {title:L({ru:'Ужин за ~3 ч до сна · выберите один (легче)',en:'Dinner ~3 h before sleep · pick one (lighter)',uk:'Вечеря за ~3 год до сну · оберіть один (легше)',es:'Cena ~3 h antes de dormir · elige una (más ligera)',de:'Abendessen ~3 Std vor dem Schlaf · wähle eines (leichter)',pt:'Jantar ~3 h antes de dormir · escolha um (mais leve)',fr:'Dîner ~3 h avant le coucher · choisissez-en un (plus léger)',pl:'Kolacja ~3 h przed snem · wybierz jedno (lżejsze)',it:'Cena ~3 h prima di dormire · scegline uno (più leggero)',he:'ארוחת ערב ~3 שע׳ לפני השינה · בחרו אחת (קלה יותר)',ja:'就寝の約3時間前の夕食 · 1つ選ぶ（軽め）',ko:'취침 ~3시간 전 저녁 · 하나 선택 (가볍게)'}), variants:true, items:din},
      {title:L({ru:'Учтите вечером',en:'Keep in mind tonight',uk:'Врахуйте ввечері',es:'Ten en cuenta esta noche',de:'Beachte am Abend',pt:'Leve em conta à noite',fr:'À garder en tête ce soir',pl:'Weź pod uwagę wieczorem',it:'Tieni a mente stasera',he:'קחו בחשבון הערב',ja:'今夜の注意点',ko:'오늘 저녁 유의사항'}), items:[L({ru:'Без позднего кофеина и алкоголя — они «съедают» глубокий сон',en:'No late caffeine or alcohol — they eat into deep sleep',uk:'Без пізнього кофеїну й алкоголю — вони «з’їдають» глибокий сон',es:'Sin cafeína ni alcohol tardíos — se «comen» el sueño profundo',de:'Kein später Koffein oder Alkohol — sie „fressen“ den Tiefschlaf',pt:'Sem cafeína ou álcool tardios — eles «comem» o sono profundo',fr:'Pas de caféine ni d’alcool tardifs — ils « grignotent » le sommeil profond',pl:'Bez późnej kofeiny i alkoholu — «zjadają» głęboki sen',it:'Niente caffeina o alcol a tarda ora — «mangiano» il sonno profondo',he:'בלי קפאין ואלכוהול מאוחרים — הם «אוכלים» את השינה העמוקה',ja:'遅い時間のカフェインとアルコールは避ける — 深い睡眠を「奪う」',ko:'늦은 카페인과 알코올은 피하기 — 깊은 수면을 «갉아먹음»'})]},
      {title:L({ru:'Если уже принимаете добавки (вечер)',en:'If you already take supplements (evening)',uk:'Якщо вже приймаєте добавки (вечір)',es:'Si ya tomas suplementos (noche)',de:'Falls du bereits Supplemente nimmst (abends)',pt:'Se você já toma suplementos (noite)',fr:'Si vous prenez déjà des compléments (soir)',pl:'Jeśli już bierzesz suplementy (wieczór)',it:'Se già assumi integratori (sera)',he:'אם כבר נוטלים תוספים (ערב)',ja:'すでにサプリを摂っている場合（夜）',ko:'이미 보충제를 드시는 경우 (저녁)'}), items:[
        L({ru:'Магний — стандартный ориентир ~400 мг для спокойствия перед сном (форму обсудите со специалистом)',en:'Magnesium — a common guideline ~400 mg for calm before sleep (discuss the form with a specialist)',uk:'Магній — стандартний орієнтир ~400 мг для спокою перед сном (форму обговоріть зі спеціалістом)',es:'Magnesio — referencia común ~400 mg para calmarse antes de dormir (consulta la forma con un especialista)',de:'Magnesium — üblicher Richtwert ~400 mg für Ruhe vor dem Schlaf (Form mit einem Spezialisten besprechen)',pt:'Magnésio — referência comum ~400 mg para calma antes de dormir (discuta a forma com um especialista)',fr:'Magnésium — repère courant ~400 mg pour le calme avant le sommeil (voir la forme avec un spécialiste)',pl:'Magnez — typowy orientacyjnie ~400 mg dla spokoju przed snem (formę omów ze specjalistą)',it:'Magnesio — riferimento comune ~400 mg per la calma prima di dormire (valuta la forma con uno specialista)',he:'מגנזיום — הכוונה נפוצה ~400 מ״ג לרוגע לפני השינה (התייעצו עם מומחה לגבי הצורה)',ja:'マグネシウム — 就寝前の落ち着きに一般的な目安約400mg（形態は専門家と相談）',ko:'마그네슘 — 취침 전 안정에 일반적 기준 ~400mg (형태는 전문가와 상담)'}),
        L({ru:'Чай ромашка/мелисса — мягкое расслабление',en:'Chamomile/lemon balm tea — gentle relaxation',uk:'Чай ромашка/меліса — м’яке розслаблення',es:'Té de manzanilla/melisa — relajación suave',de:'Kamillen-/Melissentee — sanfte Entspannung',pt:'Chá de camomila/melissa — relaxamento suave',fr:'Tisane camomille/mélisse — détente douce',pl:'Herbata rumianek/melisa — łagodne odprężenie',it:'Tisana camomilla/melissa — rilassamento delicato',he:'תה קמומיל/מליסה — הרפיה עדינה',ja:'カモミール/メリッサのお茶 — 穏やかなリラックス',ko:'캐모마일/레몬밤 차 — 부드러운 이완'})
      ]}
    ];
  }
  if(id==='activity'){
    var it=[];
    it.push(over40?L({ru:'Силовые 2–3×/нед — ключевая основа с возрастом (сила мышц и крепость костей). Начните с малого: 2–3 подхода простых упражнений.',en:'Strength 2–3×/week — a key foundation with age (muscle strength and bone sturdiness). Start small: 2–3 sets of simple moves.',uk:'Силові 2–3×/тиж — ключова основа з віком (сила м’язів і міцність кісток). Почніть з малого: 2–3 підходи простих вправ.',es:'Fuerza 2–3×/sem — base clave con la edad (fuerza muscular y solidez ósea). Empieza con poco: 2–3 series de ejercicios simples.',de:'Krafttraining 2–3×/Woche — mit dem Alter eine Schlüsselgrundlage (Muskelkraft und Knochenfestigkeit). Klein anfangen: 2–3 Sätze einfacher Übungen.',pt:'Força 2–3×/sem — base essencial com a idade (força muscular e solidez óssea). Comece devagar: 2–3 séries de exercícios simples.',fr:'Renforcement 2–3×/sem — base essentielle avec l’âge (force musculaire et solidité osseuse). Commencez petit : 2–3 séries d’exercices simples.',pl:'Siła 2–3×/tydz — kluczowa podstawa z wiekiem (siła mięśni i mocne kości). Zacznij od małego: 2–3 serie prostych ćwiczeń.',it:'Forza 2–3×/sett — base fondamentale con l’età (forza muscolare e robustezza ossea). Inizia piano: 2–3 serie di esercizi semplici.',he:'כוח 2–3 בשבוע — בסיס מרכזי עם הגיל (כוח שרירים וחוזק עצם). התחילו בקטן: 2–3 סטים של תרגילים פשוטים.',ja:'筋トレ週2〜3回 — 年齢とともに要となる基盤（筋力と骨の丈夫さ）。小さく始める：簡単な種目を2〜3セット。',ko:'근력 주 2~3회 — 나이가 들수록 핵심 기반(근력과 뼈 강도). 작게 시작: 간단한 운동 2~3세트.'}):L({ru:'Силовые 2–3×/нед — фундамент тонуса и формы, маленькими шагами.',en:'Strength 2–3×/week — the base of tone and shape, in small steps.',uk:'Силові 2–3×/тиж — фундамент тонусу і форми, маленькими кроками.',es:'Fuerza 2–3×/sem — la base del tono y la forma, con pequeños pasos.',de:'Krafttraining 2–3×/Woche — die Basis für Tonus und Form, in kleinen Schritten.',pt:'Força 2–3×/sem — a base do tônus e da forma, em pequenos passos.',fr:'Renforcement 2–3×/sem — la base du tonus et de la forme, à petits pas.',pl:'Siła 2–3×/tydz — podstawa napięcia i formy, małymi krokami.',it:'Forza 2–3×/sett — la base di tono e forma, a piccoli passi.',he:'כוח 2–3 בשבוע — הבסיס לטונוס ולכושר, בצעדים קטנים.',ja:'筋トレ週2〜3回 — 引き締めと体型の土台、小さな一歩から。',ko:'근력 주 2~3회 — 탄력과 몸매의 토대, 작은 걸음으로.'}));
    it.push(L({ru:'Ходьба 10–15 мин сразу после еды — лучший момент для ровной энергии.',en:'A 10–15 min walk right after meals — the best moment for steady energy.',uk:'Ходьба 10–15 хв одразу після їжі — найкращий момент для рівної енергії.',es:'Caminar 10–15 min justo después de comer — el mejor momento para una energía estable.',de:'10–15 Min Gehen direkt nach dem Essen — der beste Moment für gleichmäßige Energie.',pt:'Caminhar 10–15 min logo após comer — o melhor momento para energia estável.',fr:'Marcher 10–15 min juste après les repas — le meilleur moment pour une énergie stable.',pl:'Spacer 10–15 min zaraz po jedzeniu — najlepszy moment na równą energię.',it:'Camminare 10–15 min subito dopo i pasti — il momento migliore per un’energia stabile.',he:'הליכה 10–15 דק׳ מיד אחרי האוכל — הרגע הטוב ביותר לאנרגיה יציבה.',ja:'食後すぐ10〜15分の歩行 — 安定したエネルギーに最適。',ko:'식후 바로 10~15분 걷기 — 안정적인 에너지에 가장 좋은 순간.'}));
    it.push(L({ru:'Йога/растяжка — для нервной системы и восстановления.',en:'Yoga/stretching — for the nervous system and recovery.',uk:'Йога/розтяжка — для нервової системи та відновлення.',es:'Yoga/estiramientos — para el sistema nervioso y la recuperación.',de:'Yoga/Dehnen — für Nervensystem und Erholung.',pt:'Yoga/alongamento — para o sistema nervoso e a recuperação.',fr:'Yoga/étirements — pour le système nerveux et la récupération.',pl:'Joga/rozciąganie — dla układu nerwowego i regeneracji.',it:'Yoga/stretching — per il sistema nervoso e il recupero.',he:'יוגה/מתיחות — למערכת העצבים ולהתאוששות.',ja:'ヨガ/ストレッチ — 神経系と回復のために。',ko:'요가/스트레칭 — 신경계와 회복을 위해.'}));
    if(data.act_recovery==='exhausted') it.push(L({ru:'Вы отмечаете истощение после нагрузок — снизьте интенсивность, добавьте день полного отдыха и приоритет сну.',en:'You note exhaustion after workouts — lower intensity, add a full rest day and prioritize sleep.',uk:'Ви відмічаєте виснаження після навантажень — знизьте інтенсивність, додайте день повного відпочинку і пріоритет сну.',es:'Notas agotamiento tras el ejercicio — baja la intensidad, añade un día de descanso total y prioriza el sueño.',de:'Du bemerkst Erschöpfung nach dem Training — senke die Intensität, füge einen vollen Ruhetag hinzu und priorisiere Schlaf.',pt:'Você nota esgotamento após os treinos — reduza a intensidade, adicione um dia de descanso total e priorize o sono.',fr:'Vous notez de l’épuisement après l’effort — baissez l’intensité, ajoutez un jour de repos complet et priorisez le sommeil.',pl:'Zauważasz wyczerpanie po wysiłku — obniż intensywność, dodaj dzień pełnego odpoczynku i priorytet dla snu.',it:'Noti spossatezza dopo gli allenamenti — abbassa l’intensità, aggiungi un giorno di riposo totale e dai priorità al sonno.',he:'אתם מבחינים בתשישות אחרי מאמץ — הפחיתו עצימות, הוסיפו יום מנוחה מלא ותנו עדיפות לשינה.',ja:'運動後に消耗を感じる — 強度を下げ、完全休養日を設け、睡眠を優先。',ko:'운동 후 탈진을 느낀다면 — 강도를 낮추고 완전 휴식일을 추가하며 수면을 우선하세요.'}));
    if(f==='0'||f==='low') it.push(L({ru:'Старт: ежедневная прогулка + 1 короткая силовая, наращивайте постепенно.',en:'Start: a daily walk + 1 short strength session, build up gradually.',uk:'Старт: щоденна прогулянка + 1 коротка силова, нарощуйте поступово.',es:'Inicio: un paseo diario + 1 sesión de fuerza corta, aumenta poco a poco.',de:'Start: täglicher Spaziergang + 1 kurze Krafteinheit, steigere allmählich.',pt:'Início: caminhada diária + 1 sessão de força curta, aumente aos poucos.',fr:'Début : une marche quotidienne + 1 courte séance de force, augmentez progressivement.',pl:'Start: codzienny spacer + 1 krótki trening siłowy, zwiększaj stopniowo.',it:'Inizio: camminata quotidiana + 1 breve sessione di forza, aumenta gradualmente.',he:'התחלה: הליכה יומית + אימון כוח קצר אחד, הגבירו בהדרגה.',ja:'スタート：毎日の散歩 + 短い筋トレ1回、徐々に増やす。',ko:'시작: 매일 산책 + 짧은 근력 1회, 점진적으로 늘리기.'}));
    else if(f==='high') it.push(L({ru:'Высокая активность — следите за восстановлением: 1–2 дня отдыха, достаточно белка и сна.',en:'High activity — watch recovery: 1–2 rest days, enough protein and sleep.',uk:'Висока активність — стежте за відновленням: 1–2 дні відпочинку, достатньо білка і сну.',es:'Actividad alta — cuida la recuperación: 1–2 días de descanso, suficiente proteína y sueño.',de:'Hohe Aktivität — achte auf Erholung: 1–2 Ruhetage, genug Protein und Schlaf.',pt:'Atividade alta — cuide da recuperação: 1–2 dias de descanso, proteína e sono suficientes.',fr:'Activité élevée — surveillez la récupération : 1–2 jours de repos, assez de protéines et de sommeil.',pl:'Wysoka aktywność — pilnuj regeneracji: 1–2 dni odpoczynku, dość białka i snu.',it:'Attività alta — cura il recupero: 1–2 giorni di riposo, proteine e sonno a sufficienza.',he:'פעילות גבוהה — שימו לב להתאוששות: 1–2 ימי מנוחה, מספיק חלבון ושינה.',ja:'高い活動量 — 回復に注意：休養1〜2日、十分なタンパク質と睡眠。',ko:'높은 활동량 — 회복에 유의: 휴식 1~2일, 충분한 단백질과 수면.'}));
    it.push(isMale?L({ru:'Комбо силовая + короткое кардио поддерживает тонус и обмен.',en:'A combo of strength + short cardio supports tone and metabolism.',uk:'Комбо силова + коротке кардіо підтримує тонус і обмін.',es:'Combo de fuerza + cardio corto mantiene el tono y el metabolismo.',de:'Kombi aus Kraft + kurzem Cardio hält Tonus und Stoffwechsel.',pt:'Combo de força + cardio curto mantém o tônus e o metabolismo.',fr:'Le combo force + cardio court soutient le tonus et le métabolisme.',pl:'Combo siła + krótkie cardio wspiera napięcie i metabolizm.',it:'Combo forza + cardio breve sostiene tono e metabolismo.',he:'שילוב כוח + קרדיו קצר שומר על טונוס וחילוף חומרים.',ja:'筋トレ + 短い有酸素の組み合わせが引き締めと代謝を支える。',ko:'근력 + 짧은 유산소 조합이 탄력과 대사를 지원.'}):L({ru:'Опорная и силовая берегут крепость костей; избегайте резких скручиваний с весом.',en:'Weight-bearing and strength protect bone sturdiness; avoid sharp loaded twists.',uk:'Опорна і силова бережуть міцність кісток; уникайте різких скручувань із вагою.',es:'El trabajo de carga y fuerza cuida la solidez ósea; evita giros bruscos con peso.',de:'Belastungs- und Krafttraining schützen die Knochenfestigkeit; vermeide ruckartige Drehungen mit Gewicht.',pt:'Exercícios de carga e força protegem a solidez óssea; evite torções bruscas com peso.',fr:'Le travail en charge et en force protège la solidité osseuse ; évitez les torsions brusques avec du poids.',pl:'Ćwiczenia obciążające i siłowe chronią mocne kości; unikaj gwałtownych skrętów z ciężarem.',it:'Il lavoro di carico e forza protegge la robustezza ossea; evita torsioni brusche con peso.',he:'עבודת נשיאת משקל וכוח שומרות על חוזק העצם; הימנעו מפיתולים חדים עם משקל.',ja:'荷重と筋力トレーニングが骨の丈夫さを守る；重りをかけた急なひねりは避ける。',ko:'체중 부하와 근력 운동이 뼈 강도를 지킴; 무게를 실은 급격한 비틀기는 피하세요.'}));
    it.push(L({ru:'Интенсивное — лучше утром/днём; вечером — мягкое (йога, прогулка), чтобы не мешать сну.',en:'Intense work is better in the morning/day; evenings — gentle (yoga, a walk) so sleep is undisturbed.',uk:'Інтенсивне — краще вранці/удень; увечері — м’яке (йога, прогулянка), щоб не заважати сну.',es:'Lo intenso mejor por la mañana/tarde; por la noche algo suave (yoga, paseo) para no afectar el sueño.',de:'Intensives besser morgens/tagsüber; abends sanft (Yoga, Spaziergang), um den Schlaf nicht zu stören.',pt:'O intenso melhor de manhã/à tarde; à noite algo suave (yoga, caminhada) para não atrapalhar o sono.',fr:'L’intense de préférence le matin/la journée ; le soir, du doux (yoga, marche) pour ne pas gêner le sommeil.',pl:'Intensywne lepiej rano/w dzień; wieczorem łagodne (joga, spacer), by nie zaburzać snu.',it:'L’intenso meglio al mattino/di giorno; la sera qualcosa di dolce (yoga, camminata) per non disturbare il sonno.',he:'אימון עצים עדיף בבוקר/ביום; בערב עדין (יוגה, הליכה) כדי לא להפריע לשינה.',ja:'高強度は朝〜日中に；夜は軽め（ヨガ、散歩）で睡眠を妨げない。',ko:'고강도는 아침/낮에; 저녁은 부드럽게(요가, 산책) 수면을 방해하지 않도록.'}));
    return [{title:L({ru:'Добавьте движение',en:'Add movement',uk:'Додайте рух',es:'Añade movimiento',de:'Bring Bewegung rein',pt:'Adicione movimento',fr:'Ajoutez du mouvement',pl:'Dodaj ruch',it:'Aggiungi movimento',he:'הוסיפו תנועה',ja:'動きを取り入れる',ko:'움직임 더하기'}), items:it}];
  }
  if(id==='water'){
    var target=(w*35/1000).toFixed(1);
    return [{title:L({ru:'Поддерживайте водный баланс',en:'Keep up your water balance',uk:'Підтримуйте водний баланс',es:'Mantén tu equilibrio hídrico',de:'Halte deinen Wasserhaushalt',pt:'Mantenha o equilíbrio hídrico',fr:'Maintenez votre équilibre hydrique',pl:'Utrzymuj bilans wodny',it:'Mantieni l’equilibrio idrico',he:'שמרו על מאזן הנוזלים',ja:'水分バランスを保つ',ko:'수분 균형 유지하기'}), items:[
      L({ru:'Ваш ориентир: ≈ '+target+' л/день (≈ 35 мл на кг массы тела '+w+' кг)',en:'Your guideline: ≈ '+target+' L/day (≈ 35 ml per kg of body weight, '+w+' kg)',uk:'Ваш орієнтир: ≈ '+target+' л/день (≈ 35 мл на кг маси тіла '+w+' кг)',es:'Tu referencia: ≈ '+target+' L/día (≈ 35 ml por kg de peso corporal, '+w+' kg)',de:'Dein Richtwert: ≈ '+target+' L/Tag (≈ 35 ml pro kg Körpergewicht, '+w+' kg)',pt:'Sua referência: ≈ '+target+' L/dia (≈ 35 ml por kg de peso corporal, '+w+' kg)',fr:'Votre repère : ≈ '+target+' L/jour (≈ 35 ml par kg de poids corporel, '+w+' kg)',pl:'Twój cel orientacyjny: ≈ '+target+' l/dzień (≈ 35 ml na kg masy ciała, '+w+' kg)',it:'Il tuo riferimento: ≈ '+target+' L/giorno (≈ 35 ml per kg di peso corporeo, '+w+' kg)',he:'ההכוונה שלכם: ≈ '+target+' ל׳/יום (≈ 35 מ״ל לכל ק״ג משקל גוף, '+w+' ק״ג)',ja:'目安：約'+target+' L/日（体重1kgあたり約35ml、'+w+' kg）',ko:'기준: ≈ '+target+' L/일 (체중 1kg당 ≈ 35ml, '+w+' kg)'}),
      L({ru:'В активные дни и в жару +250–500 мл',en:'On active days and in heat +250–500 ml',uk:'В активні дні та у спеку +250–500 мл',es:'En días activos y con calor +250–500 ml',de:'An aktiven Tagen und bei Hitze +250–500 ml',pt:'Em dias ativos e no calor +250–500 ml',fr:'Les jours actifs et par forte chaleur +250–500 ml',pl:'W dni aktywne i w upał +250–500 ml',it:'Nei giorni attivi e col caldo +250–500 ml',he:'בימים פעילים ובחום +250–500 מ״ל',ja:'活動的な日や暑い日は+250〜500ml',ko:'활동적인 날과 더울 때 +250~500ml'}),
      L({ru:'По стакану каждые 1.5–2 ч до 19:00 — чтобы не будить себя ночью',en:'A glass every 1.5–2 h until 7 pm — so you don’t wake yourself at night',uk:'По склянці кожні 1.5–2 год до 19:00 — щоб не будити себе вночі',es:'Un vaso cada 1,5–2 h hasta las 19:00 — para no despertarte de noche',de:'Ein Glas alle 1,5–2 Std bis 19 Uhr — um nachts nicht aufzuwachen',pt:'Um copo a cada 1,5–2 h até as 19h — para não acordar à noite',fr:'Un verre toutes les 1,5–2 h jusqu’à 19 h — pour ne pas se réveiller la nuit',pl:'Szklanka co 1,5–2 h do 19:00 — by nie budzić się w nocy',it:'Un bicchiere ogni 1,5–2 h fino alle 19 — per non svegliarti di notte',he:'כוס כל 1.5–2 שע׳ עד 19:00 — כדי לא להתעורר בלילה',ja:'19時まで1.5〜2時間ごとにコップ1杯 — 夜中に目覚めないように',ko:'19시까지 1.5~2시간마다 한 잔 — 밤에 깨지 않도록'}),
      L({ru:'Источники: чистая вода, травяные чаи без сахара',en:'Sources: plain water, unsweetened herbal teas',uk:'Джерела: чиста вода, трав’яні чаї без цукру',es:'Fuentes: agua pura, infusiones de hierbas sin azúcar',de:'Quellen: reines Wasser, ungesüßte Kräutertees',pt:'Fontes: água pura, chás de ervas sem açúcar',fr:'Sources : eau pure, tisanes sans sucre',pl:'Źródła: czysta woda, herbaty ziołowe bez cukru',it:'Fonti: acqua pura, tisane senza zucchero',he:'מקורות: מים נקיים, תה צמחים ללא סוכר',ja:'水分源：純水、無糖のハーブティー',ko:'공급원: 맑은 물, 무설탕 허브차'})
    ]}];
  }
  if(id==='sleep'){
    var base=[
      L({ru:'Фиксированное время подъёма — главный якорь ритма (даже в выходные)',en:'A fixed wake-up time — the main anchor of rhythm (even on weekends)',uk:'Фіксований час підйому — головний якір ритму (навіть у вихідні)',es:'Hora fija de despertar — el ancla principal del ritmo (incluso el finde)',de:'Feste Aufwachzeit — der Hauptanker des Rhythmus (auch am Wochenende)',pt:'Horário fixo de acordar — a âncora principal do ritmo (mesmo no fim de semana)',fr:'Heure de réveil fixe — l’ancre principale du rythme (même le week-end)',pl:'Stała pora pobudki — główna kotwica rytmu (nawet w weekend)',it:'Ora di sveglia fissa — l’ancora principale del ritmo (anche nel weekend)',he:'שעת יקיצה קבועה — העוגן המרכזי של המקצב (גם בסופ״ש)',ja:'起床時刻を固定 — リズムの主要な錨（週末も）',ko:'고정된 기상 시간 — 리듬의 핵심 닻(주말에도)'}),
      L({ru:'Кровать — только для сна. Не спится ~20 мин → встать, тихое тусклое занятие, вернуться при сонливости',en:'Bed is only for sleep. Not sleeping ~20 min → get up, a quiet dim activity, return when drowsy',uk:'Ліжко — тільки для сну. Не спиться ~20 хв → встати, тихе тьмяне заняття, повернутися при сонливості',es:'La cama solo para dormir. Sin sueño ~20 min → levántate, algo tranquilo con luz tenue, vuelve al tener sueño',de:'Das Bett nur zum Schlafen. Kein Schlaf ~20 Min → aufstehen, ruhige gedämpfte Tätigkeit, bei Müdigkeit zurück',pt:'A cama só para dormir. Sem sono ~20 min → levante-se, algo calmo com pouca luz, volte com sono',fr:'Le lit seulement pour dormir. Pas de sommeil ~20 min → levez-vous, activité calme et tamisée, revenez à la somnolence',pl:'Łóżko tylko do spania. Bez snu ~20 min → wstań, ciche przygaszone zajęcie, wróć przy senności',it:'Il letto solo per dormire. Non prende sonno ~20 min → alzati, attività tranquilla e soffusa, torna con la sonnolenza',he:'המיטה רק לשינה. לא נרדמים ~20 דק׳ → לקום, פעילות שקטה ועמומה, לחזור עם הנמנום',ja:'ベッドは睡眠だけに。20分ほど眠れなければ → 起きて薄明かりで静かに過ごし、眠くなったら戻る',ko:'침대는 잠잘 때만. ~20분 잠이 안 오면 → 일어나 어두운 곳에서 조용한 활동, 졸리면 돌아오기'}),
      L({ru:'Не смотрите на часы ночью — снижает тревогу о сне',en:'Don’t check the clock at night — it lowers anxiety about sleep',uk:'Не дивіться на годинник вночі — знижує тривогу про сон',es:'No mires el reloj de noche — reduce la ansiedad por el sueño',de:'Nachts nicht auf die Uhr schauen — senkt die Angst um den Schlaf',pt:'Não olhe o relógio à noite — reduz a ansiedade com o sono',fr:'Ne regardez pas l’heure la nuit — réduit l’anxiété liée au sommeil',pl:'Nie patrz nocą na zegar — obniża lęk o sen',it:'Non guardare l’orologio di notte — riduce l’ansia sul sonno',he:'אל תסתכלו על השעון בלילה — מפחית חרדת שינה',ja:'夜中に時計を見ない — 睡眠への不安を下げる',ko:'밤에 시계를 보지 않기 — 수면 불안을 낮춤'}),
      L({ru:'Прохладная тёмная спальня, ритуал спокойствия за час до сна',en:'A cool dark bedroom, a calming ritual an hour before sleep',uk:'Прохолодна темна спальня, ритуал спокою за годину до сну',es:'Dormitorio fresco y oscuro, un ritual de calma una hora antes',de:'Kühles dunkles Schlafzimmer, ein Ruheritual eine Stunde vor dem Schlaf',pt:'Quarto fresco e escuro, um ritual de calma uma hora antes',fr:'Chambre fraîche et sombre, un rituel de calme une heure avant',pl:'Chłodna ciemna sypialnia, rytuał wyciszenia godzinę przed snem',it:'Camera fresca e buia, un rituale di calma un’ora prima',he:'חדר שינה קריר וחשוך, טקס הרגעה שעה לפני השינה',ja:'涼しく暗い寝室、就寝1時間前の落ち着くルーティン',ko:'서늘하고 어두운 침실, 취침 1시간 전 진정 루틴'}),
      L({ru:'Дыхание 4-7-8 перед сном',en:'4-7-8 breathing before sleep',uk:'Дихання 4-7-8 перед сном',es:'Respiración 4-7-8 antes de dormir',de:'4-7-8-Atmung vor dem Schlaf',pt:'Respiração 4-7-8 antes de dormir',fr:'Respiration 4-7-8 avant le coucher',pl:'Oddychanie 4-7-8 przed snem',it:'Respirazione 4-7-8 prima di dormire',he:'נשימת 4-7-8 לפני השינה',ja:'就寝前に4-7-8呼吸',ko:'취침 전 4-7-8 호흡'}),
      L({ru:'Продукты с магнием вечером; без позднего кофеина и алкоголя',en:'Magnesium-rich foods in the evening; no late caffeine or alcohol',uk:'Продукти з магнієм увечері; без пізнього кофеїну й алкоголю',es:'Alimentos con magnesio por la noche; sin cafeína ni alcohol tardíos',de:'Magnesiumreiche Lebensmittel abends; kein später Koffein oder Alkohol',pt:'Alimentos com magnésio à noite; sem cafeína ou álcool tardios',fr:'Aliments riches en magnésium le soir ; pas de caféine ni d’alcool tardifs',pl:'Produkty z magnezem wieczorem; bez późnej kofeiny i alkoholu',it:'Alimenti con magnesio la sera; niente caffeina o alcol a tarda ora',he:'מזון עשיר במגנזיום בערב; בלי קפאין ואלכוהול מאוחרים',ja:'夜はマグネシウムの多い食品；遅いカフェインとアルコールは控える',ko:'저녁에 마그네슘이 풍부한 음식; 늦은 카페인과 알코올은 피하기'})
    ];
    var pers=[];
    if(data.hf_count==='mid'||data.hf_count==='high'||data.hf_count==='veryhigh') pers.push(L({ru:'Приливы и ночная потливость: прохладная спальня, лёгкий ужин, дышащая ткань — спокойнее спится.',en:'For hot flashes: a cool bedroom, a light dinner, breathable fabric — easier, calmer sleep.',uk:'Припливи та нічна пітливість: прохолодна спальня, легка вечеря, дихаюча тканина — спокійніше спиться.',es:'Sofocos y sudores nocturnos: dormitorio fresco, cena ligera, tejidos transpirables — se duerme más tranquilo.',de:'Hitzewallungen und Nachtschweiß: kühles Schlafzimmer, leichtes Abendessen, atmungsaktive Stoffe — ruhigerer Schlaf.',pt:'Fogachos e suor noturno: quarto fresco, jantar leve, tecido respirável — sono mais tranquilo.',fr:'Bouffées de chaleur et sueurs nocturnes : chambre fraîche, dîner léger, tissus respirants — sommeil plus paisible.',pl:'Uderzenia gorąca i nocne poty: chłodna sypialnia, lekka kolacja, oddychające tkaniny — spokojniejszy sen.',it:'Vampate e sudorazione notturna: camera fresca, cena leggera, tessuti traspiranti — sonno più tranquillo.',he:'גלי חום והזעות לילה: חדר שינה קריר, ארוחת ערב קלה, בד נושם — שינה רגועה יותר.',ja:'ほてりと寝汗：涼しい寝室、軽い夕食、通気性のよい生地 — より穏やかに眠れる。',ko:'홍조와 야간 발한: 서늘한 침실, 가벼운 저녁, 통기성 좋은 소재 — 더 편안한 잠.'}));
    if(data.wake==='early') pers.push(L({ru:'Ранние подъёмы: лёгкий белковый перекус вечером и продукты с магнием.',en:'Early rising: a light protein snack in the evening and magnesium-rich foods.',uk:'Ранні підйоми: легкий білковий перекус увечері та продукти з магнієм.',es:'Despertares tempranos: un tentempié proteico ligero por la noche y alimentos con magnesio.',de:'Frühes Erwachen: ein leichter Protein-Snack am Abend und magnesiumreiche Lebensmittel.',pt:'Despertar cedo: um lanche proteico leve à noite e alimentos com magnésio.',fr:'Réveils précoces : une petite collation protéinée le soir et des aliments riches en magnésium.',pl:'Wczesne pobudki: lekka białkowa przekąska wieczorem i produkty z magnezem.',it:'Risvegli precoci: uno spuntino proteico leggero la sera e alimenti con magnesio.',he:'יקיצות מוקדמות: חטיף חלבון קל בערב ומזון עשיר במגנזיום.',ja:'早朝覚醒：夜は軽いタンパク質の間食とマグネシウムの多い食品。',ko:'이른 기상: 저녁에 가벼운 단백질 간식과 마그네슘이 풍부한 음식.'}));
    if(/high|выс/i.test(data.stress||'')||(parseInt(data.anxiety)||0)>=5) pers.push(L({ru:'Спокойствие ума: 5 мин майндфулнес днём и дыхание вечером — легче отпускать мысли.',en:'A calmer mind: 5 min of mindfulness by day and breathing in the evening — easier to let thoughts go.',uk:'Спокій розуму: 5 хв майндфулнес удень і дихання ввечері — легше відпускати думки.',es:'Mente en calma: 5 min de mindfulness de día y respiración por la noche — más fácil soltar los pensamientos.',de:'Ruhiger Geist: 5 Min Achtsamkeit tagsüber und Atmung abends — Gedanken leichter loslassen.',pt:'Mente calma: 5 min de mindfulness de dia e respiração à noite — mais fácil soltar os pensamentos.',fr:'Esprit calme : 5 min de pleine conscience le jour et respiration le soir — plus facile de lâcher les pensées.',pl:'Spokojny umysł: 5 min uważności w dzień i oddech wieczorem — łatwiej odpuścić myśli.',it:'Mente calma: 5 min di mindfulness di giorno e respirazione la sera — più facile lasciar andare i pensieri.',he:'רוגע נפשי: 5 דק׳ מיינדפולנס ביום ונשימה בערב — קל יותר לשחרר מחשבות.',ja:'穏やかな心：日中5分のマインドフルネスと夜の呼吸 — 考えを手放しやすく。',ko:'차분한 마음: 낮에 5분 마음챙김과 저녁 호흡 — 생각을 놓기 더 쉬움.'}));
    var secs=[{title:L({ru:'Подготовьтесь ко сну',en:'Prepare for sleep',uk:'Підготуйтеся до сну',es:'Prepárate para dormir',de:'Bereite dich auf den Schlaf vor',pt:'Prepare-se para dormir',fr:'Préparez-vous au sommeil',pl:'Przygotuj się do snu',it:'Preparati al sonno',he:'התכוננו לשינה',ja:'眠りの準備をする',ko:'잠잘 준비하기'}), items:base}];
    if(pers.length) secs.push({title:L({ru:'Для вечернего комфорта',en:'For evening comfort',uk:'Для вечірнього комфорту',es:'Para el confort nocturno',de:'Für den Abendkomfort',pt:'Para o conforto à noite',fr:'Pour le confort du soir',pl:'Dla wieczornego komfortu',it:'Per il comfort serale',he:'לנוחות הערב',ja:'夜の快適さのために',ko:'저녁 편안함을 위해'}), items:pers});
    secs.push({title:L({ru:'Важно',en:'Important',uk:'Важливо',es:'Importante',de:'Wichtig',pt:'Importante',fr:'Important',pl:'Ważne',it:'Importante',he:'חשוב',ja:'重要',ko:'중요'}), items:[L({ru:'Опора — вечерние привычки и спокойный ритм, а не только добавки. Данные носимых бывают неточны — ориентируйтесь на самочувствие днём.',en:'The base is evening habits and a calm rhythm, not just supplements. Wearable data can be inaccurate — go by how you feel during the day.',uk:'Опора — вечірні звички і спокійний ритм, а не лише добавки. Дані носимих бувають неточні — орієнтуйтеся на самопочуття вдень.',es:'La base son los hábitos nocturnos y un ritmo tranquilo, no solo los suplementos. Los datos de wearables pueden ser imprecisos — guíate por cómo te sientes de día.',de:'Die Basis sind Abendgewohnheiten und ein ruhiger Rhythmus, nicht nur Supplemente. Wearable-Daten können ungenau sein — orientiere dich am Tagesbefinden.',pt:'A base são os hábitos noturnos e um ritmo calmo, não só suplementos. Dados de wearables podem ser imprecisos — guie-se pelo que sente durante o dia.',fr:'La base, ce sont les habitudes du soir et un rythme calme, pas seulement les compléments. Les données des wearables peuvent être imprécises — fiez-vous à votre ressenti dans la journée.',pl:'Podstawą są wieczorne nawyki i spokojny rytm, nie tylko suplementy. Dane z urządzeń bywają niedokładne — kieruj się samopoczuciem w ciągu dnia.',it:'La base sono le abitudini serali e un ritmo calmo, non solo gli integratori. I dati dei wearable possono essere imprecisi — regolati su come stai di giorno.',he:'הבסיס הוא הרגלי ערב ומקצב רגוע, לא רק תוספים. נתוני מכשירים לבישים עלולים להיות לא מדויקים — היעזרו בתחושה ביום.',ja:'土台は夜の習慣と穏やかなリズムで、サプリだけではありません。ウェアラブルのデータは不正確なこともある — 日中の体調を目安に。',ko:'기반은 저녁 습관과 차분한 리듬이지 보충제만이 아닙니다. 웨어러블 데이터는 부정확할 수 있어요 — 낮의 컨디션을 기준으로.'})]});
    return secs;
  }
  return [];
}
// Фото-каталог блюд «Памятки дня» (docs/FOOD-PHOTO-SPEC.md): воркер помечает вариант меню
// меткой [dish:KEY] в конце пункта → здесь вырезаем метку и рендерим фото interpreter/food/KEY.webp
// + ориентир БЖУ стандартной порции (числа языконезависимы; персональная граммовка белка — в тексте ИИ).
// Пункт без метки / с неизвестным KEY / без фото (onerror) рендерится текстом, как раньше.
var _DISH={
  bf_eggs_veg:{p:28,f:12,c:30}, bf_omelet_cheese:{p:29,f:13,c:30}, bf_cottage_berries:{p:26,f:14,c:28},
  bf_yogurt_fruit:{p:27,f:9,c:34}, bf_buckwheat_chicken:{p:33,f:8,c:28}, bf_salmon_plate:{p:27,f:17,c:26},
  ln_salmon_quinoa:{p:32,f:17,c:28}, ln_chicken_salad:{p:35,f:12,c:26}, ln_beef_rice:{p:34,f:14,c:30},
  ln_whitefish_veg:{p:28,f:8,c:26}, ln_legumes:{p:18,f:9,c:52}, ln_tofu_rice:{p:20,f:12,c:30},
  dn_baked_fish:{p:23,f:9,c:10}, dn_turkey_broccoli:{p:32,f:6,c:8}, dn_egg_avocado:{p:13,f:18,c:18},
  dn_cottage_light:{p:22,f:12,c:18}, dn_chicken_light:{p:30,f:7,c:15}, dn_soup_fish:{p:20,f:6,c:12},
  sn_nuts_fruit:{p:6,f:16,c:22}, sn_yogurt_berries:{p:10,f:4,c:12}, sn_hummus_veg:{p:8,f:12,c:18}, sn_eggs_cucumber:{p:13,f:10,c:3},
  // Достроено 2026-09-06: фото есть у всех 50 блюд каталога, а БЖУ было только у 22 —
  // остальные показывались «голой» карточкой. Оценки по составу порции, как и выше (≈).
  bf_eggs_gf_toast:{p:16,f:13,c:22}, bf_gf_oat_berries:{p:12,f:18,c:46}, bf_rice_porridge_egg:{p:11,f:6,c:50},
  bf_vegan_tofu_scramble:{p:21,f:12,c:20}, bf_vegan_chia_berries:{p:9,f:20,c:26}, bf_ovo_eggs_potato:{p:16,f:11,c:36},
  bf_sardines_toast:{p:26,f:12,c:18},
  ln_liver_pepper:{p:36,f:8,c:46}, ln_lowfod_chicken_rice:{p:35,f:6,c:50}, ln_lentil_veg:{p:24,f:7,c:54},
  ln_vegan_falafel_quinoa:{p:19,f:14,c:58}, ln_vegan_chickpea_roast:{p:21,f:7,c:60},
  ln_vegan_tofu_zucchini_rice:{p:20,f:11,c:42}, ln_vegan_pumpkin_curry:{p:14,f:8,c:58},
  ln_lacto_salad_feta:{p:18,f:20,c:40}, ln_ovo_egg_rice_bowl:{p:18,f:11,c:48}, ln_sardine_potato:{p:26,f:12,c:36},
  dn_lowfod_fish_zucchini:{p:28,f:3,c:34}, dn_turkey_potato_carrot:{p:34,f:4,c:30}, dn_tofu_greens:{p:22,f:11,c:28},
  dn_vegan_lentil_stew:{p:18,f:4,c:40}, dn_vegan_tempeh_rice:{p:26,f:12,c:35}, dn_vegan_pumpkin_soup:{p:8,f:12,c:26},
  dn_lacto_cheese_veg:{p:20,f:17,c:30}, dn_ovo_frittata_veg:{p:19,f:15,c:8}, dn_omelet_zucchini:{p:18,f:14,c:8},
  sn_kiwi_walnuts:{p:4,f:13,c:22}, sn_ricecake_cheese:{p:11,f:12,c:18},
  // Пятая партия 2026-09-22 (docs/DISH-CATALOG-SPEC.md §7) — оценки по составу порции (≈).
  bf_vegan_buckwheat_seeds:{p:12,f:14,c:48}, bf_vegan_rice_peanut_banana:{p:11,f:14,c:62},
  bf_lacto_cheese_gf_toast:{p:20,f:14,c:30},
  ln_vegan_tempeh_quinoa_veg:{p:26,f:14,c:40}, ln_lacto_feta_rice_zucchini:{p:16,f:14,c:48},
  ln_ovo_omelet_potato_spinach:{p:20,f:14,c:32}, ln_lowfod_beef_potato:{p:32,f:12,c:38},
  dn_vegan_tofu_greenbeans_potato:{p:22,f:12,c:30}, dn_vegan_quinoa_zucchini_seeds:{p:14,f:13,c:38},
  dn_lacto_cheese_rice_carrot:{p:18,f:12,c:40}, dn_lowfod_chicken_rice_beans:{p:33,f:6,c:38},
  sn_ricecake_peanut_strawberry:{p:8,f:12,c:28}, sn_cheese_grapes:{p:13,f:14,c:16},
  sn_pumpkinseeds_orange:{p:9,f:14,c:18}
};
// Страховка от забытой метки (баг владельца 2026-07-13: «творог+груша+семечки» без фото, хотя это
// dn_cottage_light): пункт без [dish:KEY] сверяем с каталогом по ключевым продуктам (ru/uk/en — осн.
// языки + en-фолбэк остальных). Фото ставится ТОЛЬКО при однозначном совпадении (ровно одно блюдо).
var _DISH_SIG=[
  ['bf_eggs_veg',[/яичниц|яєчн|fried egg|scrambl/i,/шпинат|черри|spinach|cherry|помидор|томат|tomato/i]],
  ['bf_omelet_cheese',[/омлет|omelet/i,/гречк|салат|сыр|сир\b|buckwheat|salad|cheese/i]],
  ['bf_cottage_berries',[/творог|творож|cottage/i,/черник|чорниц|ягод|ягід|малин|смородин|berr/i]],
  ['bf_yogurt_fruit',[/йогурт|yog(h?)urt/i,/банан|banana/i]],
  ['bf_buckwheat_chicken',[/куриц|курин|курк|chicken/i,/гречк|buckwheat/i,/свекл|свёкл|буряк|beet/i]],
  ['bf_salmon_plate',[/лосос|salmon/i,/спарж|asparagus/i]],
  ['ln_salmon_quinoa',[/лосос|salmon/i,/киноа|кіноа|quinoa/i]],
  ['ln_chicken_salad',[/куриц|курин|курк|chicken/i,/батат|sweet potato/i]],
  ['ln_beef_rice',[/говядин|яловичин|beef/i,/рис\b|rice/i]],
  ['ln_whitefish_veg',[/треск|тріск|\bcod\b|бел(ая|ой) рыб|біл(а|ої) риб|white ?fish/i,/перловк|barley|свекл|свёкл|морков|carrot/i]],
  ['ln_legumes',[/\bнут\b|фасол|квасол|chickpea|\bbeans?\b/i,/брокколи|капуст|хлеб|хліб|broccoli|cabbage|bread/i]],
  ['ln_tofu_rice',[/тофу|tofu/i]],
  ['dn_baked_fish',[/форел|trout/i]],
  ['dn_turkey_broccoli',[/индейк|індичк|індик|turkey/i,/брокколи|broccoli/i]],
  ['dn_egg_avocado',[/пашот|poached/i,/авокадо|avocado/i]],
  ['dn_cottage_light',[/творог|творож|cottage/i,/груш|pear/i]],
  ['dn_chicken_light',[/куриц|курин|курк|chicken/i,/огур|огірк|cucumber|помидор|томат|tomato/i]],
  ['dn_soup_fish',[/суп|soup/i,/рыб|риб|fish/i]],
  ['sn_nuts_fruit',[/орех|горіх|минда|мигда|almond|walnut|nuts/i,/яблок|яблук|apple|груш|pear/i]],
  ['sn_yogurt_berries',[/йогурт|кефир|кефір|yog(h?)urt|kefir/i,/черник|чорниц|ягод|ягід|малин|berr/i]],
  ['sn_hummus_veg',[/хумус|hummus/i]],
  ['sn_eggs_cucumber',[/варён|варен|boiled/i,/яйц|яєц|egg/i,/огур|огірк|cucumber/i]]
];

// Разделы базовой памятки на нужном языке. id: morning|lunch|evening|activity|water|sleep
export function bpChapterData(id, data, lang) {
  _L_LANG = String(lang || 'en');
  try { return _bpChapterData(id, data || {}) || []; } catch (e) { return []; }
}
